/* params.js - fogli parametri (ParamsSheetBase): gruppi, etichette, chiavi e default dall'inventario.
   Nel prototipo sono di sola lettura/modifica locale: "Salva parametri" non scrive nulla. */
(function () {
  'use strict';
  var S = window.S;
  // campo: [etichetta, chiave, default, tipo?] tipo: n (numero, default) | b (si/no) | s:opz1|opz2 | u (uscite)
  var P = S.PARAMS = {};
  P.omega = { title: 'Ω Parametri Omega', desc: 'Limiti e unità sono quelli della whitelist del servizio: un valore fuori range viene clampato e dichiarato. «Salva parametri» invia i valori del servizio più le TUE modifiche, non i default della UI.', foot: 'I tre cap (liability/partita, stop-loss, liability aperta) sono OFF di default: Omega è set-and-forget. Mettili > 0 per attivarli.', groups: [
    ['Obiettivo', 'quanto deve produrre la giornata: il servizio ne ricava il target per partita e per gamba.', [['Obiettivo giornaliero (€)', '__daily_goal', 250]]],
    ['Selezione e finestre', '', [['Motore', 'engine', 'legs', 's:due gambe (1T Half Time Score + 2T Correct Score)|v1: una gamba sul Correct Score (kill-switch)'], ['Quota lay MIN', 'price_min', 20], ['Quota lay MAX', 'price_max', 120], ['Gamba 1T: minuto MIN', 'ht_entry_min', 20], ['Gamba 1T: minuto MAX', 'ht_entry_max', 40], ['Gamba 2T: minuto MIN', 'ft_entry_min', 50], ['Gamba 2T: minuto MAX', 'ft_entry_max', 80], ['P(modello) MAX (punti %)', 'model_p_max_pct', 2], ['Distanza minima dal punteggio (gol)', 'model_min_goal_distance', 2], ['Max eventi al giorno', 'max_events', 0], ['Liquidità lay MIN (€)', 'min_lay_liquidity', 5], ['Stake MIN (€)', 'min_stake', 0.5], ['Includi i risultati aggregati ("Any Other …")', 'include_aggregate', false, 'b'], ['Sorgente del minuto', 'entry_window_source', 'score', 's:score (minuto e punteggio dal feed live)|clock (orario del calcio d’inizio)']]],
    ['Motore v1 (una gamba)', 'usati SOLO con motore "v1".', [['v1: minuto MIN', 'entry_minute_min', 30], ['v1: minuto MAX', 'entry_minute_max', 60]]],
    ['Modello e probabilità', '', [['Calibrazione P(modello)', 'model_calibration', 'off', 's:off|auto'], ['Percorso del calibratore', 'model_calibration_path', '', 't'], ['Veto empirico HT→FT (gamba 2T)', 'model_empirical', 'veto', 's:veto|off'], ['Veto empirico: minuto massimo', 'model_empirical_max_minute', 60], ['Fattore di coda su P ≤ 5 %', 'model_tail_factor', 1.3], ['Incertezza sui λ (cv)', 'model_lambda_cv', 0.3], ['Usa i cartellini gialli del feed', 'model_use_yellow_cards', true, 'b'], ['λ impliciti nell’intero mercato (CS + Over/Under)', 'lambda_market_grid', true, 'b'], ['λ dall’Over/Under LIVE se mancano fixture e quote pre-KO', 'lambda_live_fallback', true, 'b'], ['Lambda dalle quote 1X2 pre-KO PRIMA della fixture (O1)', 'lambda_quote_prima', true, 'b'], ['A pari probabilità scegli il risultato più economico da coprire', 'select_cost_aware', true, 'b'], ['Banda di probabilità equivalente (× la più bassa)', 'select_p_band_ratio', 2], ['Selezione conservativa: k × SE', 'select_k_se', 0], ['P di dover coprire (ranking EV)', 'select_p_hedge', 0.5], ['Peso del costo di copertura (ranking EV)', 'select_ev_kappa', 1]]],
    ['Green-up automatico', 'la scommessa diventa un TRADE: il servizio chiude a mercato appena il risultato bancato diventa raggiungibile, oppure TIENE se il modello dice che uscire butta valore.', [['Green-up automatico attivo', 'greenup_enabled', false, 'b'], ['Modalità green-up', 'greenup_mode', 'auto', 's:auto (tiene o chiude per P(perdita) ed EV)|off (nessun green-up)'], ['Scatta a distanza (gol)', 'greenup_trigger_distance', 1], ['Scatta se la quota scende sotto (frazione dell’ingresso)', 'greenup_price_trigger_ratio', 0.5], ['Attesa assestamento dopo il gol (s)', 'greenup_settle_delay_s', 30], ['TIENI se P(perdita) ≤ (frazione 0-1)', 'greenup_hold_max_risk', 0.02], ['Rischio alto se P(perdita) ≥ (frazione 0-1)', 'greenup_risk_cap', 0.15], ['Premio di rischio (frazione della liability)', 'greenup_risk_premium_pct', 0.05], ['Margine EV per tenere (€)', 'greenup_ev_margin', 0.1], ['Incassa a frazione del massimo (0,1-1)', 'greenup_take_profit_frac', 0.9], ['Incassa comunque dal minuto', 'greenup_take_profit_minute', 80], ['Residuo: attesa fra i tentativi (s)', 'greenup_retry_s', 20], ['Residuo: tentativi massimi', 'greenup_max_attempts', 15], ['Quota di fine gara: quante volte il modello', 'greenup_market_floor_max_ratio', 3]]],
    ['Protezioni e cap', 'i tre cap sono OFF di default (Omega è set-and-forget): mettili > 0 per attivarli.', [['Commissione %', 'commission_pct', 5], ['Cap liability per partita (€)', 'max_liability_per_match', 0], ['Stop-loss giornaliero (€)', 'daily_loss_cap', 0], ['Cap liability aperta (€)', 'max_open_liability', 0], ['Stop ai nuovi ingressi a obiettivo raggiunto', 'stop_on_goal', true, 'b']]],
    ['Esecuzione', '', [['Cadenza del ciclo (s)', 'poll_interval_s', 20], ['Percorso di esecuzione', 'execution_mode', 'auto', 's:auto (coda flumine quando il gate passa)|rest (percorso legacy)'], ['PAPER: TTL quasi-FOK (s)', 'paper_fill_ttl_s', 45], ['LIVE via coda flumine (FILL_OR_KILL)', 'omega_live_via_flumine', true, 'b'], ['LIVE: scadenza dell’esito FOK (s)', 'live_fill_deadline_s', 20]]],
    ['Respiro del database', '', [['Feed: rilettura delle quote (s)', 'feed_cache_s', 2], ['Stato dello scanner (s)', 'scanner_status_cache_s', 10], ['Aggregati P&L (s)', 'aggregates_cache_s', 20], ['Gambe già fatte e tentativi (s)', 'sets_cache_s', 30], ['Timbro dei risultati 1T/2T (s)', 'results_every_s', 60], ['Aggiornamento delle missioni (s)', 'missions_every_s', 5], ['Rinfresco della lista eventi (s)', 'events_refresh_s', 1800], ['Statistiche a bot fermo (s)', 'idle_stats_s', 60], ['Ritmo del ciclo a vuoto (s)', 'idle_cycle_s', 60], ['Posizione sul conto Betfair (s)', 'conto_every_s', 120]]],
    ['Motore v3 — il motore di default dal 17/09', 'UN SOLO mercato, il CORRECT SCORE; gamba A 1′-44′, gamba B 46′-85′; lay fisso da 1 €; nessuna chiusura automatica, uscite a proposta.', [['Versione della strategia (2 = v2 legacy, 3 = v3)', 'strategy_version', 3], ['v3: ingresso in LAY (€)', 'v3_stake_eur', 1], ['v3: modello di probabilità', 'v3_modello', 'gamma_poisson', 's:gamma_poisson (bayesiano coniugato) — vincitore del banco|poisson|dixon_coles|dixon_robinson|bivariato (λ3 comune)'], ['v3: fusione col mercato', 'v3_fusione_mercato', 'auto', 's:auto|off'], ['v3: cartellini rossi nel modello (O5)', 'model_red_cards', true, 'b'], ['v3: margine minimo k', 'v3_k_minimo', 1.11], ['v3: tetto della fascia (p implicita, punti %)', 'v3_p_max_pct', 2], ['v3: pavimento della fascia (p implicita, punti %)', 'v3_p_min_pct', 1], ['v3: distanza minima dal punteggio (gol)', 'v3_distanza_minima_gol', 2], ['v3: casi minimi per il veto empirico', 'v3_empirical_min_n', 200], ['v3 gamba A: minuto MIN', 'v3_ht_entry_min', 1], ['v3 gamba A: minuto MAX', 'v3_ht_entry_max', 44], ['v3 gamba B: minuto MIN', 'v3_ft_entry_min', 46], ['v3 gamba B: minuto MAX', 'v3_ft_entry_max', 85], ['v3: liquidità lay MIN (€)', 'v3_min_lay_liquidity', 1], ['v3: cap liability per gamba (€)', 'v3_max_liability_per_leg', 95], ['v3: cap liability per partita (€)', 'v3_max_liability_per_match', 190], ['v3: cap liability aperta (€)', 'v3_max_open_liability', 1000], ['v3: stop-loss giornaliero (€)', 'v3_daily_loss_cap', 300]]],
    ['Uscite — proposte che firmi tu', 'Omega calcola i numeri e scrive una PROPOSTA nella Control Room: la firma è tua.', [['Proposte: P massima tollerata del risultato bancato (punti %)', 'proposta_p_lose_max_pct', 0], ['Uscite calcolate dal bot', 'uscite_protezione', 'man', 'u']]]
  ] };
  P.safe = { title: '🛡️ Parametri bot Safe Strategy', desc: 'Salvati sul database (safe_update_params): valgono per il servizio e per questa schermata. I limiti mostrati sono quelli applicati dal servizio.', foot: 'Strategie in uso dal servizio: base, esatto, punta, tennis. Il database NON viene riallineato sugli altri parametri: dove il valore salvato e quello in uso differiscono, vale sempre quello in uso.', groups: [
    ['Bot', 'Limiti applicati dal servizio.', [['Cadenza loop (s)', 'poll_interval_s', 2], ['Commissione %', 'commission_pct', 5], ['Max trade aperti', 'max_open_trades', 20], ['Liability max per trade €', 'max_liability_per_trade', 300], ['Fattore size abbinabile', 'min_size_available_factor', 1], ['Size minima Betfair €', 'min_stake', 2], ['Spread massimo (lay/back)', 'max_spread_ratio', 1.6], ['Tentativi max di piazzamento', 'place_max_attempts', 3], ['Paper · TTL abbinamento (s)', 'paper_fill_ttl_s', 45], ['Live · attesa abbinamento (s)', 'live_fill_deadline_s', 20], ['Stake LAY di default €', 'stake.laySize', 2], ['Stake BACK di default €', 'stake.backSize', 2]]],
    ['Strategie abilitate', '', [['Base', 'v_base', true, 'b'], ['Risultato Esatto', 'v_esatto', true, 'b'], ['Punta', 'v_punta', true, 'b'], ['Tennis', 'v_tennis', true, 'b']]],
    ['Rischio', 'stop in uso: −20,00 €', [['Cap liability giornaliera €', 'risk.daily_liability_cap', 600], ['Cap liability per evento €', 'risk.per_event_liability_cap', 150], ['Trade max per evento', 'risk.per_event_max_trades', 3], ['Correlazione max (0-1)', 'risk.correlated_cap', 0.6], ['Stop perdita giornaliera €', 'risk.daily_loss_stop', 20], ['Cap liability giornaliera trade di modello €', 'risk.model_daily_liability_cap', 100], ['Max posizioni aperte (rischio)', 'risk.max_open_trades', 10]]],
    ['Proponimi…', '', [['Proponimi le opportunità di MODELLO calcio', 'proponi_model', true, 'b'], ['Proponimi le opportunità di MODELLO tennis', 'proponi_tennis', true, 'b'], ['Proponimi le COMBINAZIONI', 'proponi_combo', true, 'b'], ['Proponimi le ANOMALIE di prezzo', 'proponi_anomaly', true, 'b']]],
    ['Combinazioni incomplete', '', [['Gamba manuale della combo incompleta', 'combo_gamba_manuale', 'Avvisa e proponi la copertura', 's:Avvisa e proponi la copertura|Automatico (se ne occupa il bot)']]],
    ['Modalità per strategia (paper / live)', '', [['Calcio · Base (banca 1X2)', 'strategy_modes.base', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri'], ['Calcio · Risultato Esatto', 'strategy_modes.esatto', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri'], ['Calcio · Punta', 'strategy_modes.punta', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri'], ['Tennis', 'strategy_modes.tennis', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri'], ['Opportunità del modello che approvo (modello / anomalie / combo / tennis)', 'strategy_modes.model', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri'], ['Ordini a mano dalla scheda', 'strategy_modes.manual', 'PAPER', 's:Non dichiarata → PAPER|PAPER — prova, mai soldi veri|LIVE — soldi veri']]],
    ['Opportunità di modello', '', [['Cadenza opportunità (s)', 'opps_interval_s', 10], ['Confidenza minima (0-1)', 'opps_min_confidence', 0.7], ['Edge minimo (0-1)', 'opps_min_edge', 0.03]]],
    ['Tennis / Anomalie', '', [['Stake auto-trade modello / anomalie / tennis €', 'risk.model_stake', 3], ['Stake proposto sulle card €', 'opps_stake', 5]]],
    ['Uscite modello', '', [['Tieni se P(perdita) ≤ (0-1)', 'exits.hold_max_risk', 0.02], ['Rischio alto se P(perdita) ≥ (0-1)', 'exits.risk_cap', 0.1], ['Premio di rischio (frazione della liability)', 'exits.risk_premium_pct', 0.05], ['Margine EV per tenere (€)', 'exits.ev_margin', 0.1], ['Modello · esci in perdita da P(perdita) (0-1)', 'exits.model_exit_p_lose', 0.1], ['Modello · incassa a frazione del max (0-1)', 'exits.model_take_profit_frac', 0.8], ['Modello · cash out gratis sotto P(perdita) (0-1)', 'exits.model_free_cashout_p_lose', 0.005], ['Residuo · attesa fra tentativi (s)', 'exits.residual_retry_s', 20], ['Residuo · tentativi max', 'exits.residual_max_attempts', 15]]],
    ['Condizioni delle strategie', 'Il minuto delle strategie calcio è una SOGLIA: "dal minuto X in poi".', [['BASE · dal minuto', 'base.minuteMin', 55], ['BASE · quota di banca sfavorita MIN', 'base.dogLayMin', 20], ['BASE · quota di banca sfavorita MAX', 'base.dogLayMax', 34], ['BASE · punteggio stabile (s)', 'base.scoreConfirmSec', 30], ['BASE · soglia controllo del gioco', 'base.controlMin', 0.1], ['R. ESATTO · dal minuto', 'esatto.minuteMin', 48], ['R. ESATTO · quota MIN', 'esatto.entryMin', 30], ['R. ESATTO · quota MAX', 'esatto.entryMax', 70], ['R. ESATTO · gol max lato bancato', 'esatto.maxGoalsLaySide', 1], ['PUNTA · dal minuto', 'punta.minuteMin', 66], ['PUNTA · quota MIN', 'punta.entryMin', 1.03], ['PUNTA · quota MAX', 'punta.entryMax', 1.1], ['PUNTA · minuti dopo il gol', 'punta.minMinutesAfterGoal', 3], ['TENNIS · set di vantaggio', 'tennis.setsLeadMin', 1], ['TENNIS · game di vantaggio', 'tennis.gamesLeadMin', 2], ['TENNIS · quota leader MIN', 'tennis.entryMin', 1.02], ['TENNIS · quota leader MAX', 'tennis.entryMax', 1.1], ['TENNIS · super favorito: quota pre-partita sotto', 'tennis.favSuperMax', 1.2], ['TENNIS: escludi gli Slam maschili (5 set)', 'tennis.noSlam', true, 'b'], ['TENNIS: escludi i doppi', 'tennis.noDoubles', true, 'b'], ['BASE: richiedi il controllo del gioco', 'base.requireControl', true, 'b'], ['TENNIS: le chiusure le approvo io', 'tennis_exit_approval', 'man', 'u']]],
    ['Uscite automatiche', '', [['Uscite automatiche attive', 'exits.enabled', true, 'b'], ['BASE · uscita a tempo dal minuto', 'exits.base_exit_minute', 80], ['R. ESATTO · uscita a tempo dal minuto', 'exits.esatto_exit_minute', 72], ['PUNTA · uscita a tempo dal minuto', 'exits.punta_exit_minute', 83], ['Perdita · attesa prima di chiudere (s)', 'exits.loss_wait_s', 30], ['Tentativi max di chiusura', 'exits.max_attempts', 3], ['TENNIS · incassa solo da quota', 'exits.tennis_take_price', 1.03], ['Rosso alla favorita: esci subito', 'exits.red_exit', true, 'b']]]
  ] };
  P.mike = { title: '🎯 Parametri Mike', desc: 'Tutto modificabile. Salva per applicare a caldo: il servizio rilegge i parametri a ogni ciclo. I valori fuori dai limiti vengono riportati nei limiti e te lo diciamo.', foot: 'La modalità (PAPER/LIVE) non è un parametro: si cambia solo dal toggle in alto, con conferma.', groups: [
    ['Generale', 'finestra di lavoro, importo e commissione: valgono per tutte le partite.', [['Stake Under 3.5 (€)', 'stake', 10], ['Commissione %', 'commission_pct', 5], ['Finestra pre-match (ore prima del KO)', 'entry_hours_before_ko', 1], ['Filtro competizioni', 'competition_filter', '', 't'], ['Cadenza decisioni (ms)', 'decide_min_interval_ms', 500], ['Feed: età max riga (s)', 'feed_max_age_s', 45], ['Feed: scanner vivo entro (s)', 'scanner_alive_max_s', 75], ['LIVE: uscita appoggiata attiva', 'live_resting_enabled', true, 'b'], ['Book: visto entro (s)', 'book_seen_max_s', 90], ['Ordine: età max riga (s)', 'order_max_age_s', 20], ['Ordine: scanner vivo entro (s)', 'order_scanner_max_s', 30]]],
    ['Pre-match', 'ingresso Under 3.5 e green-up ciclico prima del calcio d’inizio.', [['Pre-match attivo', 'pre_enabled', true, 'b'], ['Quota Under 3.5 MIN', 'pre_entry_price_min', 1.3], ['Quota Under 3.5 MAX', 'pre_entry_price_max', 3], ['Liquidità min. (× stake)', 'pre_min_back_size_factor', 1], ['Spread max (tick)', 'pre_max_spread_ticks', 6], ['Green-up a (+tick)', 'pre_green_ticks', 2], ['Chiusura pre-match', 'pre_exit_mode', 'resting', 's:resting|taker'], ['TTL ingresso non abbinato (s)', 'pre_entry_ttl_s', 60], ['Cicli max per partita', 'pre_max_cycles', 10], ['Pausa dopo un green (s)', 'pre_reentry_cooldown_s', 60], ['Ultimo ingresso (min prima del KO)', 'pre_last_entry_min', 10], ['Ultimo ingresso a 10 min dal fischio', 'last_entry_persist', true, 'b'], ['Ultimo ingresso: tick sopra il best (NON ATTIVO)', 'last_entry_ticks_above', 0], ['Veto P calibrata Under 3.5 (M1)', 'veto_p_under35_cal', true, 'b'], ['Cancella residuo PERSIST dopo KO (s)', 'cancel_unmatched_after_ko_s', 120]]],
    ['Dal fischio d’inizio', '', [['Uscita al fischio attiva', 'ko_green_enabled', true, 'b'], ['Uscita a (+tick dall’ingresso)', 'ko_green_ticks', 2], ['Finestra dell’uscita (s dal fischio)', 'ko_green_window_s', 180], ['Uscita: ritenta ogni (s) — SENZA EFFETTO dal 16/09', 'ko_green_retry_s', 5], ['Seconda puntata dopo un gol precoce', 'second_entry_enabled', true, 'b'], ['Seconda puntata: % dello stake', 'second_entry_stake_pct', 50], ['Prima tranche dopo (s dal gol)', 'early_goal_cover_delay_s', 120], ['Prima tranche: % della copertura', 'early_goal_cover_pct', 50], ['Seconda tranche dopo (s dalla prima abbinata)', 'early_goal_cover2_delay_s', 180]]],
    ['Copertura (linea 4.5)', 'copertura sulla linea 4.5 in gioco (di serie banca Under 4,5): "intelligente ma non lenta".', [['Copertura attiva', 'cover_enabled', true, 'b'], ['Fattore copertura', 'cover_profit_factor', 1.2], ['Quando coprire', 'cover_policy', 'auto', 's:auto|immediate|wait'], ['Attendi se hazard 3′ ≤', 'cover_wait_hazard_max', 0.06], ['Attendi al massimo fino al minuto', 'cover_wait_max_min', 10], ['Attendi se P(4) mercato ≤', 'cover_wait_p4_max', 0.16], ['Copri subito se Over 4.5 ≥', 'cover_good_price', 7], ['Attendi solo se risparmio atteso ≥ %', 'cover_wait_min_gain_pct', 8], ['Orizzonte del risparmio (min)', 'cover_wait_step_min', 5], ['Dopo un gol attendi (s)', 'cover_postgoal_delay_s', 45], ['Nessuna copertura oltre (gol)', 'cover_max_goals', 2], ['Arrotondamento (se non esatto)', 'cover_rounding', 'ceil', 's:ceil|floor|nearest'], ['Sovracopertura max %', 'cover_max_overshoot_pct', 30], ['Forma della copertura', 'cover_form', 'lay_under45', 's:lay_under45|back_over45'], ['Importi esatti al centesimo', 'exact_sizes', true, 'b'], ['Copertura: rifiuti max prima di fermarsi', 'cover_rifiuti_max', 3], ['Copertura: attesa minima fra tentativi (s)', 'cover_retry_min_s', 15]]],
    ['Cash-out globale', 'chiusura globale a profitto (Under 3.5 + copertura 4.5), soglia e cash out intelligente.', [['Chiudi tutto a profitto ≥ %', 'cashout_profit_pct', 5], ['Base della %', 'cashout_base', 'total', 's:total|under'], ['Chiusura N tick oltre il best', 'cashout_place_at_ticks', 0], ['Copertura: cuscinetto di N tick', 'cover_place_at_ticks', 2], ['Cash-out intelligente', 'cashout_smart_enabled', true, 'b'], ['Uscite automatiche (solo le uscite in perdita)', 'uscite_automatiche', 'man', 'u'], ['Profitto minimo per chiudere prima (%)', 'cashout_smart_min_pct', 2], ['"A un passo" dalla soglia = entro (punti %)', 'cashout_smart_tolerance_pct', 2], ['Fase calda: hazard gol 3′ ≥', 'cashout_smart_hazard_hot', 0.1], ['Fase calda: pressione ≥', 'cashout_smart_pressure_hot', 1.15], ['Punteggio caldo: gol ≥', 'cashout_smart_goals_hot', 3], ['Chiudi se aspettare vale meno di (punti %)', 'cashout_smart_ev_margin_pct', 1], ['Riprezzo chiusura ogni (s)', 'close_retry_s', 10], ['Tentativi max chiusura', 'close_max_attempts', 20]]],
    ['Uscite HT / 2T', 'uscite in perdita all’intervallo e nel secondo tempo (a modello o regola fissa).', [['Uscita HT attiva', 'ht_loss_exit_enabled', true, 'b'], ['HT: perdita tollerata %', 'ht_loss_pct', 25], ['Decisione di uscita', 'loss_exit_mode', 'model', 's:model|fixed'], ['Premio al rischio (% capitale × P(4))', 'loss_exit_risk_premium_pct', 10], ['P(4) prudente (max modello/mercato)', 'loss_exit_p4_prudent', true, 'b'], ['Non cristallizzare oltre (%)', 'loss_exit_max_pct', 0], ['Casi minimi tabella HT→FT', 'loss_exit_emp_min_n', 200], ['HT: gol min', 'ht_loss_goals_min', 3], ['HT: gol max', 'ht_loss_goals_max', 4], ['Uscita 2T attiva', 'h2_loss_exit_enabled', true, 'b'], ['2T: perdita tollerata %', 'h2_loss_pct', 25], ['2T: dal minuto', 'h2_loss_from_min', 46], ['2T: fino al minuto', 'h2_loss_to_min', 85]]],
    ['Re-ingresso (gol + 3.5)', 're-ingresso sull’Under 4.5 dopo un gol e una chiusura in profitto.', [['Re-ingresso attivo', 'reentry_enabled', true, 'b'], ['Green re-ingresso (+tick)', 'reentry_green_ticks', 2], ['Gol max per il re-ingresso', 'reentry_max_goals', 2], ['Re-ingresso entro il minuto', 'reentry_until_min', 45], ['Chiusura forzata del re-ingresso al minuto', 'reentry_exit_until_min', 0], ['Solo se U4.5 > quota iniziale U3.5', 'reentry_price_min_over_entry', true, 'b'], ['Tieni il re-ingresso se in perdita', 'reentry_hold_if_loss', false, 'b']]],
    ['Rischio', 'tetti e stop: sono l’ultima barriera prima dei soldi veri.', [['Conferma punteggio finale (s)', 'settle_confirm_s', 60], ['Partite aperte max', 'max_open_matches', 10], ['Stop perdita giornaliera (€)', 'daily_loss_stop', 50], ['Cap capitale per partita (€)', 'max_liability_per_match', 0], ['Cap perdita per partita % (NON ATTIVO)', 'event_loss_cap_pct', 100], ['Log skip ogni (s)', 'skip_log_interval_s', 300], ['Rileggi il feed ogni (s)', 'feed_cache_s', 4], ['Rileggi tutte le partite ogni (s)', 'events_reload_s', 60], ['Ricalcola gli aggregati ogni (s)', 'aggregates_cache_s', 20], ['Ripara lo specchio ordini ogni (s)', 'reconcile_every_s', 30], ['Ciclo a riposo ogni (s)', 'idle_cycle_s', 5], ['Battito del servizio ogni (s)', 'heartbeat_min_s', 20]]]
  ] };
  /* 4 bot tennis: registro TENNIS_BOT_REGISTRY (nomi, fase, short, parametri e default reali) */
  S.TBOTS = [
    { key: 'tennis_scalper', name: 'Tennis Scalper', fase: 'pre + in-play', acc: 'hsl(var(--primary))', short: 'Missione tick pre-match: 1 tick di profitto prima del via, poi stop. Maker micro-scalp sul favorito (gamba in-play OFF: bocciata dal backtest di validazione).', f: [['Tick profitto', 'scalp_ticks', 1], ['Tick stop', 'stop_ticks', 3], ['Tick segnale', 'signal_ticks', 1], ['Flusso min €/lato', 'min_flow', 2], ['Size min ai best €', 'min_size', 5], ['Quota min', 'price_min', 1.2], ['Quota max', 'price_max', 6], ['Missione 1 tick/fase', 'one_tick_per_phase', 'on', 's:on|off'], ['Gamba in-play (sperimentale)', 'inplay_tick_enabled', 'off', 's:off|on'], ['Runner operato', 'runner_filter', 'solo favorito', 's:solo favorito|entrambi']] },
    { key: 'tennis_pro', name: 'Tennis Pro', fase: 'in-play', acc: 'hsl(var(--secondary))', short: 'Direzionale score-driven: break point, serving-for-set, doppio break, favorito compresso.', f: [['Break: tick target', 'bp_target_ticks', 5], ['Break: tick stop', 'bp_stop_ticks', 3], ['Fade: tick target', 'fade_target_ticks', 4], ['Matched min €', 'min_matched', 50000], ['Quota max', 'price_max', 3.6], ['Trend-following', 'trend', 'on', 's:on|off'], ['Direzione adattiva', 'adapt', 'on', 's:on|off'], ['Ingresso maker', 'maker', 'on', 's:on|off']] },
    { key: 'tennis_flb', name: 'Tennis FLB', fase: 'in-play', acc: '#22d3ee', short: 'Lay del favorito estremo (favourite-longshot bias), liability minima, exit green/hold/hybrid.', f: [['Lay max (quota)', 'lay_max', 1.1], ['Tick green', 'green_ticks', 8], ['Frazione green', 'green_frac', 0.5], ['Rearm mult', 'rearm_mult', 1.1], ['Matched min €', 'min_matched', 10000], ['Uscita', 'exit_mode', 'hybrid', 's:hybrid|hold|green']] },
    { key: 'tennis_swing', name: 'Tennis Swing', fase: 'in-play', acc: '#e879f9', short: 'Maker fade degli estremi del favorito: z-score robusto + Efficiency-Ratio + RSI.', f: [['Finestra N', 'N', 40], ['Z ingresso', 'zin', 2.0], ['ER max', 'er_max', 0.4], ['Tick stop', 'stop_ticks', 8], ['T max (s)', 'tmax', 90]] }
  ];
  S.TBOTS.forEach(function (b) {
    P[b.key] = { title: 'Parametri ' + b.name, desc: 'Sono gli STESSI parametri che il bot Python legge per ogni evento che arma (verificati chiave per chiave contro il codice del bot). Salvando qui si cambia il servizio: gli eventi già armati li rileggono al giro successivo.', foot: '', groups: [[b.name, b.short, [['Stake €', 'stake', 5]].concat(b.f)]] };
  });
  P.scalper = { title: 'Parametri Scalper calcio', desc: 'Default validati in backtest. Valgono per le partite armate da ora.', foot: '', groups: [['Scalper', '', [['Tick di profitto', 'scalp_ticks', 1], ['Tick di stop', 'stop_ticks', 1], ['Flusso min €/lato (90s)', 'min_flow', 10], ['Size min ai best €', 'min_size', 300], ['Quota min', 'price_min', 1.5], ['Quota max', 'price_max', 4.6], ['Stop ingressi (s pre-KO)', 'entry_stop_before_s', 420], ['Chiusura forzata (s pre-KO)', 'flatten_before_s', 180], ['Target profitto €', 'event_profit_target', 1], ['Tetto perdita €', 'event_loss_cap', 1.5]]]] };
  var alias = { 'safe-base': 'safe', 'safe-esatto': 'safe', 'safe-punta': 'safe', 'safe-tennis': 'safe', 'safe-model': 'safe', 'safe-manual': 'safe' };

  S.openParams = function (key) {
    var p = P[alias[key] || key]; if (!p) { S.toast('Questo bot non espone una scheda parametri', 'Si modifica dalla sua pagina.'); return; }
    var body = p.groups.map(function (g, gi) {
      return '<section class="col" style="gap:8px" data-group="' + g[0] + '"><div><div class="gold" style="font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase">' + g[0] + '</div>' + (g[1] ? '<div class="foot">' + g[1] + '</div>' : '') + '</div>' +
        g[2].map(function (f, fi) {
          var id = 'pf-' + gi + '-' + fi, t = f[3] || 'n';
          if (t === 'b') return '<label class="row" style="font-size:12px;flex-wrap:nowrap" for="' + id + '"><input type="checkbox" id="' + id + '"' + (f[2] ? ' checked' : '') + '> ' + f[0] + '</label>';
          if (t === 'u') return '<div class="row" style="font-size:12px">' + f[0] + ': <b class="' + (f[2] === 'man' ? 'amb' : 'pos') + '">' + (f[2] === 'man' ? 'MANUALI, approvi tu' : 'AUTOMATICHE') + '</b><span class="foot">si applica al bot con "Salva parametri"</span></div>';
          if (t.indexOf('s:') === 0) return '<label class="field" for="' + id + '">' + f[0] + '<select class="inp" id="' + id + '">' + t.slice(2).split('|').map(function (o) { return '<option' + (o.indexOf(f[2]) === 0 ? ' selected' : '') + '>' + o + '</option>'; }).join('') + '</select><span class="foot mono">' + f[1] + '</span></label>';
          return '<label class="field" for="' + id + '">' + f[0] + '<input id="' + id + '" ' + (t === 't' ? '' : 'inputmode="decimal"') + ' value="' + String(f[2]).replace('.', ',') + '"><span class="foot mono">' + f[1] + '</span></label>';
        }).join('') + '</section>';
    }).join('<div class="sep"></div>') + (p.foot ? '<p class="foot">' + p.foot + '</p>' : '');
    S.sheet(p.title, p.desc, body, 'Salva parametri');
  };
  S.on('params', function (t) { S.openParams(t.dataset.bot); });
})();
