/* s_analisi.js - Cruscotto partite calcio (/dashboard), Analytics, Watchlist, Match replay. */
(function () {
  'use strict';
  var S = window.S, D = window.D, M = S.money, chip = S.chip;
  var tile = function (k, v, s, tone) { return S.kpi(k, v, s, tone); };
  var bar = function (l, v, col) { return '<div class="row" style="font-size:11.5px;flex-wrap:nowrap"><span style="width:110px">' + l + '</span><span class="bar" style="flex:1"><i style="width:' + v + '%;' + (col ? 'background:' + col : '') + '"></i></span><b class="mono" style="width:44px;text-align:right">' + v + '%</b></div>'; };

  /* ======================= DASHBOARD CALCIO ======================= */
  var FIX = [['Serie A', '🇮🇹', [['10:52', 'Bologna', 'Udinese'], ['12:22', 'Atalanta', 'Genoa'], ['14:52', 'Napoli', 'Lazio']]], ['Premier League', '🇬🇧', [['11:22', 'Brentford', 'Fulham']]], ['Ligue 1', '🇫🇷', [['11:52', 'Lens', 'Nantes']]]];
  var SHEETS = {
    freq: ['Frequenze Mercati', 'Frequenza storica del mercato nella lega (baseline) + medie mobili MM5/MM10/MM15 in ordine cronologico di kickoff. Le bande ±σ sono calibrate sull’errore standard della MM10.'],
    rit: ['Studio Ritardi', 'Riproduzione 1:1 del file STUDIO RITARDI. DATI MATCH = tutto lo storico della lega. Ogni mercato è un foglio: ritardo attuale vs media storica del mercato scelto.'],
    poi: ['Poisson', 'Probabilità del motore Dixon-Coles (poisson_xg_hybrid_dc) per questa partita, mercato per mercato.'],
    tac: ['Tactical Engine', 'Terzo motore (GSG): forze attacco/difesa inferite per massima verosimiglianza (Dixon-Coles) con simmetria casa/trasferta. Probabilità del modello, non quote.'],
    ml: ['Modelli ML', 'Previsioni calibrate dell’ensemble (rf/lgb/xgb/logreg) per questa partita, mercato per mercato.'],
    dir: ['Direzione', 'La direzione migliore per ogni mercato e quanto è affidabile, dallo storico reale dei motori.'],
    bf: ['Quote Betfair', 'Tutti i mercati Betfair pre-partita, back e lay.']
  };
  function sheetBody(k) {
    if (k === 'freq') return '<div class="row">' + ['Esito Finale 1X2', 'Doppia Chance', 'Draw No Bet', 'Under/Over', 'Entrambe Segnano (GG/NG)', 'Risultato Esatto', 'Primo Tempo 1X2 HT'].map(function (x, i) { return '<button class="chip" style="' + (i === 3 ? 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary))' : '') + '">' + x + '</button>'; }).join('') + '</div><div class="row foot"><span>Selezione</span><b>Over</b><span>Linea</span><b>2.5</b><span>Intervallo</span><b>Ultime 200</b><span>Medie mobili</span><b class="amb">MM5</b><b class="pos">MM10</b><b style="color:var(--back)">MM15</b><span>Bande ±1σ</span></div><div class="strip info">Over 2.5 — Over · Baseline 52,4 % · Serie su 200 esiti validi · σ 3,5 · copertura HT 98 %</div>' + S.spark([50, 54, 49, 56, 58, 55, 52, 57, 61, 59, 55, 53, 58], 640, 180, { label: 'MM10' }) + '<p class="foot">Asse X: partite della lega in ordine cronologico. z-score = (MM10 − baseline) / se(MM10).</p>';
    if (k === 'rit') return '<div class="row">' + ['Risultato Esatto', 'Somma Gol Esatta', 'Over', 'Under', 'Over Primo Tempo', 'Pareggio (X)', 'GG & Over 2.5'].map(function (x, i) { return '<button class="chip" style="' + (i === 1 ? 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary))' : '') + '">' + x + '</button>'; }).join('') + '</div><div class="grid g6">' + [['Quota Oggettiva', '7,4', '= media storica'], ['Media Storica', '7,4', 'ogni 7,4 partite si verifica'], ['Ritardo Attuale', '<span class="amb">9</span>', '1,2× la media'], ['Record', '31', 'serie storica max'], ['% Mercato', '13,5 %', ''], ['Media Rit.', '6,1', 'AVERAGEIF(RIT;≠0)']].map(function (x) { return tile(x[0], x[1], x[2]); }).join('') + '</div>' + S.spark([2, 5, 1, 0, 7, 3, 9, 2, 4, 9], 640, 120) + '<div class="grid g2">' + S.panel('Sotto la media', '<div class="foot">esce in orario o prima · BI · AZ · BE/BF/BG</div><b class="pos" style="font-size:20px">62 %</b> <span class="foot">delle uscite</span>') + S.panel('Sopra la media', '<div class="foot">tarda più del solito · BJ · BL · BT/BU/BV</div><b class="neg" style="font-size:20px">38 %</b>') + '</div><details><summary class="lbl" style="cursor:pointer">DATI MATCH — 1.842 eventi</summary><p class="foot">EVENTO, HOME, AWAY, GC, GA, GCFH, GAFH, GCSH, GASH, W/L, RIT, SUC · Carica altri 500</p></details>';
    if (k === 'poi' || k === 'tac') return '<div class="row foot">' + (k === 'poi' ? chip('✓ calibrato', 'paper') + '<span>λ casa 1,61</span><span>λ trasf. 0,94</span><span>ρ DC −0,08</span><span>partite 38 / 38</span><span>xG attivo</span>' : chip('leakage-free', 'paper') + '<span>λ casa 1,55</span><span>λ trasf. 0,98</span><span>storico 380 partite</span>' + chip('✓ converged', 'paper')) + '</div><div class="strip paper" style="font-size:11.5px">Previsione ' + (k === 'poi' ? 'Poisson' : 'TacticAI') + ': aggiornato al 01/10 06:10 (4 h fa)</div>' + (k === 'tac' ? '<div class="grid g2">' + tile('Gol attesi', '1,55 – 0,98') + tile('Forze inferite (att >1 forte · dif <1 solida)', 'att 1,18 / dif 0,86 · att 0,91 / dif 1,07') + '</div>' : '') + '<div class="row">' + ['1X2', 'Over 1.5', 'Over 2.5', 'Over 3.5', 'BTTS', '1°T Over 0.5', 'HT 1X2'].map(function (x, i) { return '<button class="chip" style="' + (i ? '' : 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary))') + '">' + x + '</button>'; }).join('') + '</div><div class="panel flat" style="padding:12px"><div class="foot">Più probabile: <b>1 (Casa) 52,1 %</b></div>' + bar('1 (Casa)', 52, 'var(--emerald)') + bar('X (Pari)', 26, 'hsl(155 15% 50%)') + bar('2 (Trasf.)', 22, 'var(--amber)') + '</div><p class="foot">Probabilità del modello (non quote). Le linee disponibili sono solo quelle elaborate dal motore.</p>' + (k === 'tac' ? '<div class="strip info">Consiglio: esito più probabile 1; rete di sicurezza 1X; tendenza gol Under 2.5.</div>' : '');
    if (k === 'ml') return '<div class="row foot"><span>ensemble_v2</span>' + chip('affidabilità dati high (0,91)', 'paper') + '<span>feature 96 %</span><span>partite 38 / 38</span></div><div class="lbl">Mercato (24)</div><div class="row">' + ['Esito · 1X2 (FT)', 'HT 1X2', 'Gol totali · Over 2.5', 'BTTS', 'Squadre · Clean Sheet Casa', '1°T · 1° Gol < 30′', 'Statistiche · Calci d’angolo'].map(function (x, i) { return '<button class="chip" style="' + (i ? '' : 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary))') + '">' + x + '</button>'; }).join('') + '</div><div class="panel flat" style="padding:12px"><div class="foot">Previsione: <b>1 (Casa) 49,8 %</b></div>' + bar('1 (Casa)', 50, 'var(--emerald)') + bar('X (Pari)', 27) + bar('2 (Trasf.)', 23, 'var(--amber)') + '</div><div class="grid g2">' + S.panel('Accordo con la Previsione', '<div style="font-size:12px">modelli che votano 1 (Casa) <b>3/4</b></div><div class="row">' + chip('RF 1') + chip('LGB 1') + chip('XGB 1') + chip('LOGREG X') + '</div>') + S.panel('Calibrazione', '<div style="font-size:12px">Brier 0,192 · ECE 0,021</div><div class="pos foot">✓ modello affidabile per questo mercato</div>') + '</div><div class="strip paper" style="flex-direction:column;align-items:flex-start"><b>Segnale di valore — BACK 1</b><span class="foot">prob 49,8 % · quota 2,30 · edge +6,3 % · EV 0,145 · Kelly 2,4 % · grado B</span></div>';
    if (k === 'dir') return '<div class="strip paper" data-testid="direzione-eta" style="font-size:11.5px">Pagella affidabilità: aggiornato al 01/10 05:40 · Quote (analytics_bets): presenti su 7 righe di 7</div><div class="foot">● segnale forte · ● discreto · ● debole / contro — AFFIDABILITÀ = quante volte è andata così nello storico · LIFT = quanto batte la media · VALORE = l’affidabilità (banda bassa) batte la quota Betfair (back). Direzione di partenza, non un segnale di profitto: guarda sempre la quota.</div>' + [['Esito finale', 'Casa', '58 %', '52–64 %', '+12', '2,30 Betfair', 'valore', '3/4', 'pos'], ['Over 2.5', 'Over', '61 %', '55–66 %', '+8', '1,92 Betfair', '', '2/4', 'amb'], ['Gol/Gol (BTTS)', 'No', '49 %', '43–55 %', '−2', 'quota book', '', '2/4', 'neg']].map(function (r) { return '<div class="row" style="padding:8px 10px;border-radius:8px;background:hsl(var(--muted)/.45);font-size:12px"><span class="led" style="background:var(--' + (r[8] === 'pos' ? 'emerald' : r[8] === 'amb' ? 'amber' : 'red') + ')"></span><div style="min-width:140px"><b>' + r[0] + '</b><div class="foot">direzione <b class="prim">' + r[1] + '</b></div></div><div><b style="font-size:16px">' + r[2] + '</b><div class="foot">' + r[3] + '</div></div><div class="foot">lift <b class="' + r[8] + '">' + r[4] + ' punti</b></div><div class="foot"><span style="color:var(--back)">' + r[5] + '</span> ' + (r[6] ? chip(r[6], 'paper') : '') + '</div><div class="foot" style="margin-left:auto">' + r[7] + ' motori ›</div></div>'; }).join('');
    return '<div class="foot"><span style="color:var(--back)">Back</span> · <span style="color:var(--lay)">Lay</span> — tre livelli per lato</div>' + ['MATCH ODDS', 'OVER/UNDER 2.5 GOALS', 'BOTH TEAMS TO SCORE?'].map(function (m, j) { var sels = j === 0 ? [['Bologna', 1.83], ['Udinese', 4.9], ['The Draw', 3.7]] : j === 1 ? [['Under 2.5 Goals', 1.95], ['Over 2.5 Goals', 2.04]] : [['Yes', 1.88], ['No', 2.1]]; return '<div><div class="lbl">' + m + '</div><table class="t"><tbody>' + sels.map(function (s) { return '<tr><td>' + s[0] + '</td>' + [2, 1, 0].map(function (k) { return '<td><span class="o b" style="cursor:default">' + S.odds(s[1] - k * 0.01) + '<small>€' + (1.2 + k) + 'k</small></span></td>'; }).join('') + [0, 1, 2].map(function (k) { return '<td><span class="o l" style="cursor:default">' + S.odds(s[1] + 0.01 + k * 0.01) + '<small>€' + (0.8 + k) + 'k</small></span></td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table></div>'; }).join('');
  }
  S.on('dash-sheet', function (t) {
    var k = t.dataset.v, s = SHEETS[k];
    var L = document.getElementById('layer');
    L.innerHTML = '<div class="scrim" data-act="modal-close-bg" style="place-items:end stretch;padding:0"><section class="panel" role="dialog" aria-modal="true" style="background:hsl(var(--popover));max-height:92vh;overflow:auto;border-radius:16px 16px 0 0;width:100%"><div class="panel-h" style="position:sticky;top:0;background:hsl(var(--popover));z-index:1"><div><h3 style="font-size:16px">' + s[0] + ' · Bologna vs Udinese</h3><div class="foot">' + s[1] + ' Serie A</div></div><div class="r"><button class="btn" data-act="modal-close">Chiudi</button></div></div><div class="panel-b stack" style="max-width:1100px;margin:0 auto;width:100%">' + sheetBody(k) + '</div></section></div>';
  });
  S.reg({
    id: 'dashboard', title: 'Partite del Giorno', group: 'Calcio',
    render: function () {
      var det = S.ui.dashFix, selW = S.ui.dashSel || {};
      if (!det) {
        var nSel = Object.keys(selW).filter(function (k) { return selW[k]; }).length;
        var h = '<div class="ph"><div><h1>Partite del Giorno<em>.</em></h1><p>Tutte le partite in programma oggi</p></div><div class="act"><button class="btn ' + (S.ui.dashBf ? 'gold' : '') + '" data-act="dash-bf">' + S.icon('wallet') + ' Match Betfair</button><select class="inp" id="dash-lg"><option>🌍 Tutti i Campionati</option><option>🇮🇹 Serie A</option><option>🇮🇹 Serie B</option><option>🇬🇧 Premier League</option><option>🇪🇸 La Liga</option><option>🇩🇪 Bundesliga</option><option>🇫🇷 Ligue 1</option></select><span class="chip">5 Match</span><a class="btn gold" data-go="control-room" href="#control-room">CONTROL ROOM</a></div></div>';
        h += FIX.map(function (g) {
          return '<section class="panel" style="padding:0"><div class="row" style="padding:10px 14px;border-bottom:1px solid hsl(var(--border))"><span style="font-size:18px">' + g[1] + '</span><b>' + g[0] + '</b><span class="foot">' + g[2].length + ' partite</span></div>' + g[2].map(function (m) {
            var k = m[1] + m[2];
            return '<div class="row" style="padding:9px 14px;border-bottom:1px solid hsl(var(--border)/.5)"><input type="checkbox" aria-label="Seleziona per la Watchlist" data-act="dash-w" data-v="' + k + '"' + (selW[k] ? ' checked' : '') + '><span class="clock">' + m[0] + '</span><b style="flex:1;text-align:right">' + m[1] + '</b><span class="mut">VS</span><b style="flex:1">' + m[2] + '</b><button class="btn sm pri" data-act="dash-open" data-v="' + m[1] + ' v ' + m[2] + '">ANALIZZA →</button></div>';
          }).join('') + '</section>';
        }).join('');
        if (nSel) h += '<div class="strip warn" style="position:sticky;bottom:10px;z-index:30;background:hsl(var(--popover))"><b>' + nSel + (nSel > 1 ? ' partite selezionate' : ' partita selezionata') + '</b><button class="btn sm ghost" data-act="dash-wx">✕ Annulla</button><button class="btn sm gold" style="margin-left:auto" data-act="dash-wadd">Aggiungi a Watchlist (' + nSel + ')</button></div>';
        return h;
      }
      var h2 = '<div class="row"><button class="btn sm" data-act="dash-back">‹ Torna alle partite</button><a class="btn sm gold" data-go="control-room" href="#control-room">CONTROL ROOM</a></div>';
      h2 += '<section class="panel" style="padding:20px;text-align:center"><div class="lbl">SERIE A • 2026 • ITALIA</div><div class="row" style="justify-content:center;gap:28px;margin:14px 0"><div><div style="width:64px;height:64px;border-radius:50%;margin:0 auto;box-shadow:0 0 0 3px hsl(var(--primary));display:grid;place-items:center;font:800 20px var(--f-display)">BOL</div><b style="font:800 22px var(--f-display);display:block;margin-top:6px">BOLOGNA</b><span class="chip" style="color:hsl(var(--primary))">HOME</span></div><span class="chip">VS</span><div><div style="width:64px;height:64px;border-radius:50%;margin:0 auto;box-shadow:0 0 0 3px hsl(var(--secondary));display:grid;place-items:center;font:800 20px var(--f-display)">UDI</div><b style="font:800 22px var(--f-display);display:block;margin-top:6px">UDINESE</b><span class="chip gold">AWAY</span></div></div><div class="row" style="justify-content:center">' + chip('Fixture ID: 1290118', 'paper') + chip('League ID: 135', 'paper') + '</div></section>';
      h2 += '<div class="row" style="justify-content:center">' + [['freq', 'Frequenze Mercati', '— Serie A'], ['rit', 'Studio Ritardi', '— per-lega'], ['poi', 'Poisson', '— Dixon-Coles'], ['tac', 'Tactical Engine', '— GSG (forze inferite)'], ['ml', 'Modelli ML', '— ensemble'], ['dir', 'Direzione', '— migliore per mercato'], ['bf', 'Quote Betfair', '— back / lay']].map(function (p) { return '<button class="btn" style="height:44px" data-act="dash-sheet" data-v="' + p[0] + '">' + S.icon(p[0] === 'bf' ? 'wallet' : 'chart', p[0] === 'bf' ? 'gold' : '') + ' <b>' + p[1] + '</b> <span class="mut">' + p[2] + '</span></button>'; }).join('') + '</div>';
      h2 += '<div class="grid g3">' + S.panel('% Match Odds', bar('Home', 47, 'var(--emerald)') + bar('Draw', 28, '#34d399') + bar('Away', 25, 'var(--amber)')) + S.panel('Prediction Advice', '<p style="font:600 16px var(--f-display);margin:0">“Double chance : Bologna or draw”</p><p class="foot">🏆 Winner: Bologna (Win or draw)</p>') + S.panel('Goals & Outcome', '<div class="row"><span class="lbl">Under/Over</span><b class="amb" style="font-size:20px">-2.5</b></div><div class="row"><span class="lbl">Win or Draw</span>' + chip('YES', 'paper') + '</div><div class="foot">Predicted: Home 1,4 / Away 0,9</div>') + '</div>';
      h2 += '<h2 style="text-align:center;font-size:22px"><span class="prim">HOME</span> vs <span class="gold">AWAY</span></h2><div class="grid g2">' + ['Bologna', 'Udinese'].map(function (t, i) {
        return '<div class="col">' + S.panel(t + ' <span class="chip ' + (i ? 'gold' : '') + '" style="' + (i ? '' : 'color:hsl(var(--primary))') + '">' + (i ? 'AWAY' : 'HOME') + '</span> <span class="foot">ID: ' + (500 + i) + '</span>', '<div class="lbl">League Form</div><div class="row" style="gap:3px">' + (i ? 'LDWLDLW' : 'WWDLWDW').split('').map(function (c) { return '<span class="chip ' + (c === 'W' ? 'paper' : c === 'D' ? 'amber' : 'red') + '" style="width:20px;justify-content:center;padding:0">' + c + '</span>'; }).join('') + '<span class="foot">Last 7 · ' + (i ? '2W 2D 3L' : '4W 2D 1L') + '</span></div>') +
          S.panel('Last 5 Matches Summary', bar('Form', i ? 40 : 73) + bar('Attack', i ? 55 : 68) + bar('Defense', i ? 48 : 61) + '<div class="grid g2" style="margin-top:6px">' + tile('Goals For', i ? '6' : '9', 'Avg: ' + (i ? '1,2' : '1,8') + ' per match') + tile('Goals Against', i ? '8' : '4', 'Avg: ' + (i ? '1,6' : '0,8') + ' per match') + '</div>') +
          S.panel('Goals by Minute', '<div class="row" style="align-items:flex-end;height:60px;gap:4px;flex-wrap:nowrap">' + [3, 5, 4, 6, 7, 5, 2].map(function (v) { return '<span style="flex:1;height:' + v * 7 + 'px;background:hsl(var(--primary)/.7);border-radius:3px"></span>'; }).join('') + '</div><div class="foot">0-15 · 16-30 · 31-45 · 46-60 · 61-75 · 76-90 · 91-105</div><div class="lbl" style="margin-top:6px">Under/Over Distribution</div><div class="foot">0.5 U:2·O:36 · 1.5 U:9·O:29 · 2.5 U:20·O:18 · 3.5 U:30·O:8 · 4.5 U:35·O:3</div>') +
          S.panel('Cards by Minute · Records & Streaks · Formations · Season Fixtures · Penalty Stats · Clean Sheets', '<div class="grid g3">' + tile('Yellow Cards', i ? '58' : '44') + tile('Win Streak', i ? '2' : '4') + tile('Most Used Formation', i ? '3-5-2' : '4-2-3-1') + tile('Wins / Draws / Losses', i ? '10 / 9 / 19' : '17 / 11 / 10') + tile('Total Penalties', i ? '5' : '7', 'Scored 5 · Missed 2') + tile('Clean Sheets', i ? '8' : '13', 'Failed to Score ' + (i ? '12' : '7')) + '</div>') + '</div>';
      }).join('') + '</div>';
      h2 += S.panel('CONFRONTO DIRETTO', [['Forma Recente', 73, 40], ['Attacco', 68, 55], ['Difesa', 61, 48], ['Dist. Poisson', 52, 22], ['Testa a Testa', 60, 40], ['Goals', 58, 42]].map(function (r) { return '<div class="row" style="font-size:12px;flex-wrap:nowrap"><b class="prim" style="width:40px">' + r[1] + '%</b><span style="flex:1;display:flex;height:7px;border-radius:99px;overflow:hidden;background:hsl(var(--muted))"><i style="width:' + (r[1] / (r[1] + r[2]) * 100) + '%;background:hsl(var(--primary))"></i><i style="flex:1;background:hsl(var(--secondary))"></i></span><b class="gold" style="width:40px;text-align:right">' + r[2] + '%</b><span class="foot" style="width:110px">' + r[0] + '</span></div>'; }).join('') + '<div class="strip info" style="margin-top:8px">Insight AI · Bologna ha un forma recente superiore al 33% · Bologna ha un Dist. Poisson superiore al 30%</div>');
      h2 += S.panel('STORICO H2H', '<div class="grid g3">' + [['12 apr 2026', 'Bologna 2 - 0 Udinese'], ['03 nov 2025', 'Udinese 1 - 1 Bologna'], ['20 feb 2025', 'Bologna 3 - 1 Udinese']].map(function (x) { return '<div class="panel flat" style="padding:10px"><div class="foot">' + x[0] + ' · Serie A</div><b>' + x[1] + '</b></div>'; }).join('') + '</div>');
      return h2;
    }
  });
  S.on('dash-open', function () { S.ui.dashFix = 1; S.rerender(); window.scrollTo(0, 0); });
  S.on('dash-back', function () { S.ui.dashFix = 0; S.rerender(); });
  S.on('dash-bf', function () { S.ui.dashBf = !S.ui.dashBf; S.rerender(); });
  S.on('dash-w', function (t) { var s = S.ui.dashSel = S.ui.dashSel || {}; s[t.dataset.v] = !s[t.dataset.v]; S.rerender(); });
  S.on('dash-wx', function () { S.ui.dashSel = {}; S.rerender(); });
  S.on('dash-wadd', function () { var n = Object.keys(S.ui.dashSel || {}).filter(function (k) { return S.ui.dashSel[k]; }).length; S.ui.dashSel = {}; S.rerender(); S.toast(n + (n > 1 ? ' partite aggiunte' : ' partita aggiunta') + ' alla Watchlist', 'Snapshot pre-match congelato.'); });

  /* ======================= ANALYTICS ======================= */
  S.reg({
    id: 'analytics', title: 'Analytics', group: 'Analisi',
    render: function () {
      var tab = S.tab('analytics', 'perf');
      var h = '<div class="ph"><div><h1>Centro di Controllo <em>Motori</em></h1><p>Pagella per-motore per-mercato sullo storico settlato. 48.211 segnali settlati.</p></div></div>' + S.tabbar('analytics', [['perf', 'Performance Motori'], ['dec', 'Decisioni'], ['crea', 'Crea Strategia'], ['rep', 'Reportistiche'], ['bt', '🧪 Backtest Automatico']], 'perf');
      var sel = function (id, l, opts) { return '<label class="field" for="' + id + '">' + l + '<select class="inp" id="' + id + '">' + opts.map(function (o) { return '<option>' + o + '</option>'; }).join('') + '</select></label>'; };
      if (tab === 'perf') {
        h += S.panel('Filtri', '<div class="grid g4">' + sel('an1', 'Motore', ['Tutti', 'Poisson (12.402)', 'ML (12.380)', 'API (11.120)', 'Tactics (12.309)']) + sel('an2', 'Mercato', ['Tutti', 'Esito Finale (1X2)', 'Esito 1° Tempo', 'Over/Under 1.5', 'Over/Under 2.5', 'Over/Under 3.5', 'Gol/No Gol (BTTS)', 'Gol 1° Tempo (0.5)']) + sel('an3', 'Selezione', ['—']) + sel('an4', 'Lega', ['Tutte', 'Serie A (4.120)']) + sel('an5', 'Stagione', ['Tutte', '2026']) + '<label class="field" for="an6">Confidenza % (min–max)<span class="row"><input id="an6" placeholder="0" style="width:60px"><input id="an6b" placeholder="100" style="width:60px"></span></label>' + sel('an7', 'Concordanza min. motori', ['Qualsiasi', '≥ 2 motori', '≥ 3 motori', '≥ 4 motori']) + sel('an8', 'Frequenza vs baseline', ['Qualsiasi', 'Sopra (mercato "caldo")', 'Sotto (mercato "freddo")']) + '<label class="field" for="an9">Ritardo mercato ≥<input id="an9"></label><label class="field" for="an10" title="filtro RETROSPETTIVO, esito noto">1° gol entro min. ⚠ retrosp.<input id="an10"></label>' + sel('an11', 'Raggruppa per', ['Per fascia di confidenza', 'Totale', 'Per mercato', 'Per selezione', 'Per motore', 'Per lega']) + '<label class="row" style="font-size:12px"><input type="checkbox" id="an12"> Solo segnali piazzati</label></div>', { right: '<button class="btn sm">Reset</button>' });
        h += '<p class="foot" data-testid="analytics-eta-riepilogo">Dati del riepilogo aggiornato il 01/10/2026 (ricalcolato ogni notte dal job dei risultati).</p>';
        h += '<div class="grid" style="grid-template-columns:340px minmax(0,1fr)">' + S.panel('Calibrazione', '<svg viewBox="0 0 320 320" class="spark" role="img" aria-label="Calibrazione"><rect x="20" y="10" width="290" height="290" fill="none" stroke="hsl(160 10% 18%)"/><line x1="20" y1="300" x2="310" y2="10" stroke="#fbbf24" stroke-dasharray="4 4"/>' + [[60, 58, 6, 1], [110, 115, 9, 1], [160, 150, 12, 0], [210, 220, 10, 1], [260, 240, 7, 0]].map(function (p) { return '<circle cx="' + p[0] + '" cy="' + (310 - p[1]) + '" r="' + p[2] + '" fill="' + (p[3] ? '#34d399' : '#f87171') + '" opacity=".75"/>'; }).join('') + '<text x="165" y="316" font-size="10" text-anchor="middle" fill="hsl(155 15% 50%)">prob. media detta dal motore (%)</text></svg><p class="foot">🟢 sottostima · 🔴 sovrastima · ⟍ perfetta · area ∝ N</p>') +
          S.panel('5 gruppi · 48.211 segnali', '<div class="tbl-w"><table class="t"><thead><tr><th>Gruppo</th><th class="r">N</th><th class="r">Hit-rate</th><th>Intervallo 95%</th><th class="r">Prob. media</th><th class="r">Scarto calib.</th></tr></thead><tbody>' + [['50-60%', 12021, 57.2, '56,3–58,1%', 55.1, 2.1], ['60-70%', 14330, 66.8, '66,0–67,6%', 64.9, 1.9], ['70-80%', 11902, 72.4, '71,6–73,2%', 74.6, -2.2], ['80-90%', 7210, 84.9, '84,1–85,7%', 84.1, 0.8], ['90-100%', 2748, 89.1, '87,9–90,2%', 93.2, -4.1]].map(function (r) { return '<tr style="cursor:pointer" data-act="toast" data-t="Drill-down: prime 100 partite" data-d="Partita · Mercato · Prob · Esito · Freq Δ · Ritardo · 1° gol"><td>' + r[0] + '</td><td class="r">' + r[1].toLocaleString('it-IT') + '</td><td class="r ' + (r[2] >= 60 ? 'prim' : r[2] >= 50 ? 'gold' : 'neg') + '"><b>' + r[2].toFixed(1).replace('.', ',') + '%</b></td><td><span class="bar" style="display:inline-block;width:80px;vertical-align:middle"><i style="width:' + r[2] + '%"></i></span> ' + r[3] + '</td><td class="r">' + r[4].toFixed(1).replace('.', ',') + '%</td><td class="r ' + (r[5] > 3 ? 'prim' : r[5] < -3 ? 'neg' : '') + '">' + (r[5] > 0 ? '+' : '−') + Math.abs(r[5]).toFixed(1).replace('.', ',') + ' pt</td></tr>'; }).join('') + '</tbody></table></div>', { flush: true, right: '<span class="foot">CI Wilson 95% · clic = partite</span><button class="btn sm" data-act="toast" data-t="CSV esportato" data-d="Nel prototipo nessun file viene creato.">CSV</button>' }) + '</div>';
        h += '<p class="foot">Nota su hit-rate: motori Poisson/ML/Tactics a 90′, API solo 1X2 a tempo pieno. ⚠ Il filtro “1° gol entro min.” è RETROSPETTIVO. Dati storici, non garanzia di risultati futuri.</p>';
      } else if (tab === 'dec') {
        h += S.panel('Logica decisionale monitorata', sel('dc0', '', ['Google Sheets (reale)', 'Strategia salvata: Under 2.5 Serie A']));
        h += S.panel('Filtri decisioni', '<div class="grid g4">' + sel('dc1', 'Logica decisionale', ['Tutte', 'google_sheets']) + sel('dc2', 'Stato', ['Tutti', 'Piazzate', 'Scartate']) + sel('dc3', 'Motore', ['Tutti']) + sel('dc4', 'Mercato', ['Tutti']) + sel('dc5', 'Motivo scarto', ['Tutti']) + sel('dc6', 'Raggruppa per', ['Per logica decisionale', 'Per motore', 'Per mercato', 'Per motivo scarto', 'Per stato', 'Per selezione', 'Per lega', 'Per fascia confidenza']) + '</div>', { right: '<button class="btn sm">Reset</button>' });
        h += '<div class="grid g3">' + tile('Piazzate', '412') + tile('P&L totale', '<span class="prim">+86,40€</span>') + tile('ROI', '4,2 %') + '</div>' + S.panel('3 gruppi', '<table class="t"><thead><tr><th>Gruppo</th><th class="r">N</th><th class="r">Piazz.</th><th class="r">Scart.</th><th class="r">Hit piazz.</th><th class="r">ROI</th><th class="r">P&L</th><th class="r">Edge med.</th><th class="r">Quota med.</th></tr></thead><tbody><tr><td>google_sheets</td><td class="r">1.204</td><td class="r">412</td><td class="r">792</td><td class="r">61,4 %</td><td class="r pos">4,2 %</td><td class="r pos">+86,40</td><td class="r">3,1 %</td><td class="r">1,84</td></tr></tbody></table><p class="foot">Decisioni. Ogni riga = scelta di una <i>logica decisionale</i> (oggi <b>google_sheets</b>) di piazzare/scartare un segnale.</p>', { flush: true, right: '<button class="btn sm">CSV</button>' });
      } else if (tab === 'crea') {
        h += S.panel('Crea strategia — filtri', '<div class="grid g4">' + [['Data da', '2025-08-01'], ['Data a', '2026-10-01']].map(function (x, i) { return '<label class="field" for="cs' + i + '">' + x[0] + '<input id="cs' + i + '" type="date" value="' + x[1] + '"></label>'; }).join('') + sel('cs2', 'Mercato', ['Over/Under 2.5']) + sel('cs3', 'Selezione', ['Under']) + sel('cs4', 'Lega (una)', ['Serie A']) + sel('cs5', 'Direzione', ['Back (punta)', 'Lay (banca)']) + ['Poisson ≥ %', 'ML ≥ %', 'TacticAI ≥ %', 'Motori concordi ≥', 'Ritardo =', 'Ritardo ≥', 'Quota min', 'Quota max', 'Edge ≥ %', 'Commissione % (def. 5)'].map(function (x, i) { return '<label class="field" for="csn' + i + '">' + x + '<input id="csn' + i + '"></label>'; }).join('') + sel('cs6', 'Frequenza', ['Indifferente', 'Sotto baseline', 'Sopra baseline']) + sel('cs7', 'Fonte quota', ['Betfair → bookmaker', 'Solo Betfair', 'Solo bookmaker']) + sel('cs8', 'Stato', ['Tutte', 'Solo piazzate', 'Solo scartate', 'No signal']) + '</div><div class="row" style="margin-top:8px;font-size:12px"><label class="row"><input type="checkbox"> API dice over (≥ linea) ⓘ</label><label class="row"><input type="checkbox"> Solo ML pulito (no-leak + affidabile) ⓘ</label><button class="btn pri" style="margin-left:auto" data-act="toast" data-t="Backtest eseguito">▶ Esegui backtest</button></div>');
        h += S.panel('Risultato', '<div class="grid g5">' + tile('Scommesse', '214') + tile('Settlate', '214') + tile('Con quota', '201') + tile('ROI netto', '<span class="pos">+3,8 %</span>') + tile('Profitto', '<span class="pos">+7,64 u</span>') + '</div><div class="strip warn" style="margin-top:8px">13 scommesse settlate SENZA quota (6,1 %): contano nel hit-rate ma NON nel ROI.</div><div class="row" style="margin-top:8px"><input class="inp" id="cs-nome" placeholder="Nome strategia…"><button class="btn gold" data-act="toast" data-t="Strategia salvata" data-d="La trovi nel tab Decisioni.">Salva strategia</button></div>');
      } else if (tab === 'rep') {
        h += '<div class="row"><button class="btn gold">Direzioni</button><span class="foot">Performance dei segnali direzione nel tempo</span></div>' + S.panel('Filtri', '<div class="row">' + ['7 giorni', '14 giorni', '30 giorni', '90 giorni', 'Tutto lo storico', 'Personalizza'].map(function (x, i) { return '<button class="chip" style="' + (i ? '' : 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary))') + '">' + x + '</button>'; }).join('') + '<label class="row" style="font-size:12px"><input type="checkbox"> Solo segnali "buoni" (≥ 2 motori concordi)</label><label class="row" style="font-size:12px"><input type="checkbox"> Solo partite Betfair</label></div>', { right: '<button class="btn sm">Reset</button>' });
        h += '<div class="grid g6">' + tile('Direzioni', '842') + tile('Hit reale', '63,1 %', 'IC 95% 59,8–66,3') + tile('Atteso (calibr.)', '61,4 %', 'scarto +1,7') + tile('Buone (≥2 conc.)', '512') + tile('Rendimento (ROI)', '<span class="pos">+4,1 %</span>', 'q.media 1,78') + tile('Quote Betfair', '91 %', '766/842 prezzate') + '</div>' + S.panel('Andamento', S.spark([58, 61, 60, 64, 62, 66, 63], 900, 120) + '<p class="foot">linea reale verde piena vs “atteso” gialla tratteggiata per giorno</p>') + S.panel('Riepilogo per segnale', '<table class="t"><thead><tr><th>Segnale</th><th class="r">N</th><th class="r">Hit</th><th class="r">Atteso</th><th class="r">Buone</th><th class="r">ROI</th><th class="r">Q.media</th></tr></thead><tbody><tr><td>Esito Finale (1X2)</td><td class="r">120</td><td class="r">54 %</td><td class="r">52 %</td><td class="r">71</td><td class="r pos">+5,2 %</td><td class="r">2,04</td></tr><tr><td>Over/Under 2.5</td><td class="r">120</td><td class="r">61 %</td><td class="r">60 %</td><td class="r">80</td><td class="r pos">+2,9 %</td><td class="r">1,79</td></tr></tbody></table>', { flush: true, right: '<button class="btn sm">CSV</button>' });
      } else {
        h += '<div class="grid g2">' + S.panel('Partite registrate', '<div class="col" style="gap:4px;max-height:240px;overflow:auto">' + ['Inter v Torino', 'Napoli v Lazio', 'Atalanta v Genoa', 'Brentford v Fulham'].map(function (x, i) { return '<label class="row" style="font-size:12px;padding:5px;border-radius:6px;background:hsl(var(--muted)/.5)"><input type="checkbox"' + (i < 2 ? ' checked' : '') + '><b>' + x + '</b><span class="foot">Serie A · 2' + (i + 1) + '/09 · 24 mercati · 18.402 snapshot</span></label>'; }).join('') + '</div>', { right: '<span class="foot">2 selezionate</span>' }) +
          S.panel('Configurazione backtest', '<div class="seg"><button aria-pressed="true">Motore Live</button><button aria-pressed="false">Sandbox (regole)</button></div><div class="grid g3" style="margin-top:8px">' + [['Bankroll (£)', 1000], ['Edge min %', 3], ['Frazione Kelly', 0.25], ['Commissione %', 5], ['Latenza piazz. (s)', 0.12], ['Latenza cancel. (s)', 0.17]].map(function (x, i) { return '<label class="field" for="bt' + i + '">' + x[0] + '<input id="bt' + i + '" value="' + String(x[1]).replace('.', ',') + '"></label>'; }).join('') + sel('bt9', 'Inmatchato a fine mercato', ['LAPSE (annulla)', 'PERSIST (porta in-play)', 'MARKET_ON_CLOSE (SP)']) + '</div><label class="row" style="font-size:12px;margin-top:6px"><input type="checkbox"> Matcha anche contro i prezzi disponibili — fill OTTIMISTICI</label><p class="foot">Applica il Motore Live #2 alle partite selezionate.</p><button class="btn pri" data-act="toast" data-t="Backtest in coda" data-d="Il worker locale sta elaborando la simulazione flumine…">▶ Esegui backtest</button>') + '</div>' +
          S.panel('Backtest Completato · #a91f', '<div class="grid g5">' + tile('Scommesse', '38') + tile('Settlate', '38') + tile('Con quota', '38') + tile('ROI netto', '<span class="pos">+2,1 %</span>') + tile('Profitto', '<span class="pos">+0,80 u</span>') + '</div>') + S.panel('Esecuzioni recenti', '<table class="t"><thead><tr><th>Quando</th><th>Modalità</th><th class="r">Partite</th><th>Stato</th></tr></thead><tbody><tr><td>01/10 09:12</td><td>Motore Live</td><td class="r">2</td><td>' + chip('Completato', 'paper') + '</td></tr><tr><td>30/09 21:40</td><td>Sandbox</td><td class="r">6</td><td>' + chip('Completato', 'paper') + '</td></tr></tbody></table>', { flush: true, right: '<span class="foot">clic = rivedi risultati</span>' });
      }
      return h;
    }
  });

  /* ======================= WATCHLIST ======================= */
  S.reg({
    id: 'watchlist', title: 'Watchlist', group: 'Trading',
    render: function () {
      var tab = S.tab('watchlist', 'da');
      var h = '<div class="ph"><div><h1>La mia <span class="amb">Watchlist</span></h1><p>Snapshot pre-match congelati. Decidi se giocare o scartare — il sistema traccia consiglio e scelta.</p></div><div class="act"><a class="btn sm" data-go="report-personale" href="#report-personale">Report</a></div></div>' + S.tabbar('watchlist', [['da', 'Da valutare', 2], ['gio', 'Giocate', 1], ['sca', 'Scartate', 3]], 'da');
      if (tab === 'sca') h += S.panel('ANALISI SCARTATE · PERCHÉ LE SCARTI', '<div class="row">' + [['Quota troppo bassa', 2], ['Edge insufficiente', 1]].map(function (x) { return '<span class="chip">' + x[0] + ' <b class="neg mono">' + x[1] + '</b></span>'; }).join('') + '</div>');
      var cards = tab === 'da' ? [['Bologna', 'Udinese', 'Serie A', '01 ott, 10:52', 0], ['Brentford', 'Fulham', 'Premier League', '01 ott, 11:22', 0]] : tab === 'gio' ? [['Napoli', 'Lazio', 'Serie A', '30 set, 20:45', 2]] : [['Lens', 'Nantes', 'Ligue 1', '01 ott, 11:52', 0]];
      h += cards.map(function (c, i) {
        var open = S.ui['wl' + tab + i], follow = S.ui['wlf' + tab + i];
        return '<article class="panel" style="padding:12px 14px;display:flex;flex-direction:column;gap:8px"><div class="row"><b style="font:700 15px var(--f-display)">' + c[0] + ' <span class="mut">vs</span> ' + c[1] + '</b>' + chip(tab === 'da' ? 'Da valutare' : tab === 'gio' ? 'Giocata' : 'Scartata', tab === 'da' ? 'amber' : tab === 'gio' ? 'paper' : 'red') +
          '<span class="row" style="margin-left:auto"><a class="btn sm pri" data-go="dashboard" href="#dashboard">Vai alle statistiche</a><button class="btn sm gold" data-act="toast" data-t="Quote aggiornate" title="Aggiorna le quote Betfair di questa partita">Aggiorna quote</button><button class="btn sm ' + (follow ? 'teal' : '') + '" data-act="wl-follow" data-v="' + tab + i + '" title="' + (follow ? 'Segui live ATTIVO — clic per disattivare (nessun ordine)' : 'Segui live — iscrivi la partita allo stream (solo dati, nessun ordine)') + '">' + (follow ? 'Segui live ✓' : 'Segui live') + '</button>' + (follow ? '<span class="chip red">● REC</span>' : '') + '<button class="iconbtn" style="width:26px;height:26px" data-act="wl-exp" data-v="' + tab + i + '">' + (open ? '▴' : '▾') + '</button></span></div>' +
          '<div class="row foot">🏆 ' + c[2] + ' · 📅 ' + c[3] + (c[4] ? ' · <span class="prim">' + c[4] + ' trade</span>' : '') + '</div><div class="row">' + chip('Over/Under 2.5 · Under +4,1%', 'amber') + chip('1X2 · 1 +2,8%', 'amber') + '</div>' +
          (c[4] ? '<div class="panel flat" style="padding:8px 10px"><div class="row"><span class="lbl">Ordini piazzati · 2</span><span class="chip paper" style="margin-left:auto">live</span></div><div class="row" style="font-size:12px;margin-top:4px">' + chip('Abbinato', 'paper') + 'Over/Under 2.5 · Under <span style="color:var(--back)">Back</span> @ 1,92 · 10,00 €</div><div class="foot mono">abbinato 10,00 € @ 1,92 · betId 3.2211904</div></div>' : '') +
          (open ? '<div class="panel flat" style="padding:8px 10px"><div class="lbl">Selezioni snapshot · consigli evidenziati</div><table class="t" style="font-size:11.5px"><thead><tr><th></th><th>Mercato · Selezione</th><th class="r">prob</th><th class="r">back / lay</th><th class="r">edge</th><th class="r">motori</th></tr></thead><tbody><tr><td><input type="checkbox"></td><td>✨ Over/Under 2.5 · Under <span class="pos">●</span></td><td class="r">56,1 %</td><td class="r"><span style="color:var(--back)">1,95</span> / <span style="color:var(--lay)">1,97</span></td><td class="r pos">+4,1 %</td><td class="r">3/4</td></tr><tr><td><input type="checkbox"></td><td>1X2 · 1</td><td class="r">57,4 %</td><td class="r"><span style="color:var(--back)">1,83</span> / <span style="color:var(--lay)">1,84</span></td><td class="r amb">+2,8 %</td><td class="r">2/4</td></tr></tbody></table><p class="foot">Spunta una o più selezioni per pre-compilare la Scheda Trade · 1 selezione = 1 giocata. Mercati Betfair disponibili: 38.</p></div>' : '') +
          (tab === 'sca' ? '<div class="strip live">Scartata · Quota troppo bassa <span class="foot">“quota sotto 1,50 sul favorito”</span></div>' : '') +
          '<div class="row">' + (tab !== 'sca' ? '<button class="btn sm pri" data-act="wl-multi">Invia Giocate (1)</button><button class="btn sm" data-act="wl-trade">' + (tab === 'gio' ? 'Aggiungi trade' : 'Giocata') + '</button>' : '') + (tab === 'da' ? '<button class="btn sm danger" data-act="wl-scarta">Scartata</button><button class="iconbtn" style="width:28px;height:28px" title="Elimina dalla watchlist" data-act="wl-del">🗑</button>' : '') + (tab !== 'da' ? '<span class="foot" style="margin-left:auto">Decisa il 30/09/2026</span>' : '') + '</div></article>';
      }).join('');
      return h;
    }
  });
  S.on('wl-exp', function (t) { var k = 'wl' + t.dataset.v; S.ui[k] = !S.ui[k]; S.rerender(); });
  S.on('wl-follow', function (t) { var k = 'wlf' + t.dataset.v; S.ui[k] = !S.ui[k]; S.rerender(); });
  S.on('wl-sel', function () {});
  S.on('wl-scarta', function () { S.modal({ title: 'Scarta partita', body: '<p class="foot" style="margin-top:0">Bologna vs Udinese. Il motivo viene tracciato per l’analisi delle scartate.</p><label class="field" for="ws1">Motivo *<select class="inp" id="ws1">' + ['Quota troppo bassa', 'Edge insufficiente', 'Formazioni', 'Infortuni', 'Non mi fido', 'Troppe operazioni', 'Liquidità scarsa', 'Gestione del rischio', 'Altro'].map(function (o) { return '<option>' + o + '</option>'; }).join('') + '</select></label><label class="field" for="ws2">Nota (opzionale)<input id="ws2" placeholder="dettaglio…"></label>', ok: 'Scarta', onOk: function () { S.toast('Partita scartata'); } }); });
  S.on('wl-del', function () { S.modal({ danger: true, title: 'Elimina partita', body: 'Rimuove definitivamente lo snapshot dalla watchlist. Consentito solo per le partite “Da valutare” senza trade collegati. Operazione non reversibile.', ok: 'Elimina' }); });
  S.on('wl-trade', function () { S.modal({ title: 'Scheda Trade · Bologna vs Udinese', body: '<p class="foot" style="margin-top:0">Serie A · pre-compilata dallo snapshot pre-match. Il contesto (edge, affidabilità, concordi) viene congelato dal sistema per la selezione scelta.</p><div class="strip warn" style="flex-direction:column;align-items:flex-start"><span class="lbl">Selezioni consigliate (clic per pre-compilare)</span><button class="btn sm">Over/Under 2.5 · Under edge 4,1%</button></div><div class="grid g3" style="margin-top:8px">' + ['Strategia *', 'Lato *', 'Timing', 'Mercato', 'Selezione', 'Linea', 'Quota ingresso *', 'Stake (€) *', 'Commissione'].map(function (x, i) { return '<label class="field" for="wt' + i + '">' + x + '<input id="wt' + i + '"></label>'; }).join('') + '</div><p class="foot">Coperture / Hedge / Cash-out (opzionali) · ＋ Aggiungi leg</p>', ok: 'Registra Trade' }); });
  S.on('wl-multi', function () {
    S.modal({ danger: true, title: 'Scheda Trade · Bologna vs Udinese', body: '<div class="strip live" style="margin-bottom:8px">Order-ticket pre-compilato dallo snapshot. Gli ordini diventano operazioni REALI su Betfair.</div><div class="panel flat" style="padding:10px"><b style="font-size:12px">Over/Under 2.5 · Under · linea 2.5</b> ' + chip('prob 56,1 %') + chip('edge +4,1 %', 'paper') + '<div class="grid g3" style="margin-top:8px">' + [['Strategia *', 'Back Under'], ['Quota *', '1,95'], ['Stake (€) *', '10']].map(function (x, i) { return '<label class="field" for="wm' + i + '">' + x[0] + '<input id="wm' + i + '" value="' + x[1] + '"></label>'; }).join('') + '<label class="field" for="wm4">A inizio live<select class="inp" id="wm4"><option>Cancel (annulla a inizio live)</option><option>Keep (mantieni a inizio live)</option><option>Take SP (prezzo di partenza)</option></select></label></div><label class="row" style="font-size:12px"><input type="checkbox"> Fill or Kill</label></div><div class="strip warn" style="margin-top:8px">Stai per piazzare 1 ordine REALE su Betfair con soldi veri, per un totale stake di €10. Controlla ogni riga: partita, mercato, selezione, lato, quota e importo.</div><label class="field" for="wm-cap" style="margin-top:8px">Cap massimo stake per ordine (€) *<input id="wm-cap" placeholder="tripwire anti-errore: es. 25"></label><p class="foot">Nessun ordine sopra questo importo verrà piazzato.</p>', ok: 'Conferma e piazza ordini REALI' });
  });

  /* ======================= MATCH REPLAY ======================= */
  S.reg({
    id: 'match-replay', title: 'Match replay', group: 'Analisi',
    render: function () {
      var loaded = S.ui.rpLoaded, view = S.tab('mr-view', 'mo');
      var h = '<div class="ph"><div><h1>FOOTBALL TRADING <span class="gold">SIMULATOR</span></h1><p>Riproduci i dati di mercato registrati e piazza back/lay simulate alle quote storiche.</p></div><div class="act"><a class="btn sm pri" data-go="segui-live" href="#segui-live">Segui Live</a>' + (loaded ? '<button class="btn sm gold" data-act="mr-end">■ End Simulation</button>' : '') + '</div></div>';
      if (!loaded) return h + [['Serie A', [['Inter', 'Torino', '21/09/2026, 20:45:00', 24, 18402], ['Napoli', 'Lazio', '14/09/2026, 18:00:00', 22, 16120]]], ['Premier League', [['Brentford', 'Fulham', '13/09/2026, 16:00:00', 26, 20330]]]].map(function (g) { return '<section class="col"><div class="row"><b>' + g[0] + '</b></div><div class="lbl">2026</div><div class="grid g2">' + g[1].map(function (m) { return '<article class="panel" style="padding:12px;cursor:pointer" data-act="mr-load"><b><span class="pos">' + m[0] + '</span> vs <span class="amb">' + m[1] + '</span></b><div class="row foot" style="justify-content:space-between"><span>' + m[2] + '</span><span>' + m[3] + ' mercati · ' + m[4].toLocaleString('it-IT') + ' snapshot</span></div></article>'; }).join('') + '</div></section>'; }).join('');
      h += '<div class="row">' + chip('Overall Position: +£2,40', 'paper') + '</div>';
      h += '<section class="panel" style="padding:14px;text-align:center"><div class="lbl">SERIE A</div><b style="font:800 24px var(--f-display)">Inter <span class="gold">1-0</span> Torino</b><div class="foot">58′</div></section>';
      h += '<section class="panel" style="padding:12px;display:flex;flex-direction:column;gap:10px"><div class="row" style="justify-content:center">' + [['⏮', 'Salta all’inizio'], ['⏪', 'Riavvolgi'], ['◀', 'Un passo indietro'], ['⏸', 'Pausa'], ['▶', 'Un passo avanti'], ['⏩', 'Avanti veloce'], ['⏭', 'Salta alla fine']].map(function (b, i) { return '<button class="iconbtn" style="' + (i === 3 ? 'width:42px;height:42px;background:hsl(var(--secondary));color:#111' : '') + '" title="' + b[1] + '" aria-label="' + b[1] + '">' + b[0] + '</button>'; }).join('') + '<span class="lbl" style="margin-left:14px">Velocità</span><div class="seg">' + [1, 2, 3, 4, 5].map(function (v) { return '<button aria-pressed="' + (v === 1) + '">x' + v + '</button>'; }).join('') + '</div></div>' +
        '<div style="position:relative;height:34px"><div style="position:absolute;left:0;right:0;top:16px;height:6px;border-radius:99px;background:hsl(var(--muted))"></div><div style="position:absolute;left:0;width:58%;top:16px;height:6px;border-radius:99px;background:hsl(var(--secondary))"></div><div style="position:absolute;left:30%;width:3%;top:16px;height:6px;background:repeating-linear-gradient(45deg,#f87171 0 3px,transparent 3px 6px)" title="mercato SOSPESO"></div><span style="position:absolute;left:24%;top:0">⚽</span><span style="position:absolute;left:44%;top:2px;width:7px;height:10px;background:#fbbf24;border-radius:1px" title="Giallo"></span><span style="position:absolute;left:58%;top:10px;transform:translateX(-50%);width:26px;height:18px;border-radius:9px;background:hsl(var(--secondary));color:#111;font:700 10px var(--f-body);display:grid;place-items:center">58′</span></div><div class="row foot" style="justify-content:center"><span class="pos">◆ Arbitraggio</span><span>⚽ Gol</span><span class="amb">▮ Giallo</span><span class="neg">▮ Rosso</span><span style="color:var(--back)">⚑ Angolo</span></div></section>';
      h += '<div class="tabs">' + [['mo', 'Match Odds', 3], ['ou', 'Over/Under', 6], ['cs', 'Correct Score', 1], ['fh', 'First Half', 2], ['btts', 'BTTS', 1], ['alt', 'Squadre/Altri', 4]].map(function (t) { return '<button aria-selected="' + (view === t[0]) + '" data-act="tab" data-scr="mr-view" data-v="' + t[0] + '">' + t[1] + ' <span class="cnt">' + t[2] + '</span></button>'; }).join('') + '<button aria-selected="' + (view === 'opp') + '" data-act="tab" data-scr="mr-view" data-v="opp" class="pos">✨ Opportunità 4</button><button aria-selected="' + (view === 'lad') + '" data-act="tab" data-scr="mr-view" data-v="lad" style="color:#c4b5fd">🎓 Ladder TRAINING</button><button aria-selected="' + (view === 'bt') + '" data-act="tab" data-scr="mr-view" data-v="bt" style="color:#22d3ee">⚗ Backtest</button></div>';
      if (view === 'opp') h += S.panel('✨ Opportunità (4)', '<div class="grid g3">' + [['🟢 Rischio ~zero', 'Profitto bloccato qualunque esito', 'Scala Under 3.5 / 4.5', '+£0,42 · 1,1 %'], ['🟡 Rischio basso', 'Quasi sicuro, con rischio residuo dichiarato', 'Copertura Risultato Esatto', '+£0,90 · 2,4 %'], ['🟠 Direzionale', 'Scommessa sul movimento: profitto potenziale', 'PUNTA Under 2.5', '+£1,60 · 8 %']].map(function (f) { return '<div class="panel flat" style="padding:10px"><b>' + f[0] + '</b><div class="foot">' + f[1] + '</div><div class="sep"></div><div style="font-size:12px"><b>' + f[2] + '</b> <span class="pos">' + f[3] + '</span></div><div class="row foot"><span>Affidabilità</span><span class="bar" style="flex:1"><i style="width:72%"></i></span><span>72%</span></div><button class="btn sm">Dettagli</button></div>'; }).join('') + '</div>');
      else if (view === 'lad') h += '<div class="strip info" style="border-color:rgba(167,139,250,.5)"><b style="color:#c4b5fd">🎓 TRAINING</b><span>ordini SIMULATI sul book storico — nessun denaro reale · bet-delay in-play applicato</span><select class="inp" id="mr-lm" aria-label="Mercato del ladder training"><option>Match Odds</option></select><button class="btn sm" title="Azzera TUTTI gli ordini simulati di questa sessione di training">Azzera ordini</button></div>' + S.ladderView({ id: 'mr', market: 'Match Odds', sels: ['Inter', 'Torino', 'The Draw'], ltps: [1.38, 11.5, 5.6], mode: 'PAPER', sport: 'calcio', popout: false, multi: false });
      else if (view === 'bt') h += '<div class="strip info" style="border-color:rgba(34,211,238,.45)"><span><b>Backtest ONESTO</b>: pre-match senza delay · in-play col bet-delay reale (5s) · fill solo dalla liquidità VISIBILE del book registrato · P&L = worst-case dei due esiti · i trade non richiusi sono DICHIARATI. Una singola partita non è un campione.</span></div>' + S.panel('Parametri', '<div class="grid g6">' + [['Mercato', 'Match Odds'], ['Selezione', 'Inter'], ['Entrata', 'BACK'], ['Fase', 'Pre + in-play'], ['offset (t)', 1], ['TP (t)', 2], ['stop (t)', 3], ['stake €', 10], ['TTL (s)', 30], ['hold max (s)', 120], ['ogni (s)', 60]].map(function (x, i) { return '<label class="field" for="mbt' + i + '">' + x[0] + '<input id="mbt' + i + '" value="' + x[1] + '"></label>'; }).join('') + '</div><button class="btn" style="margin-top:8px;color:#22d3ee;border-color:rgba(34,211,238,.45)" data-act="toast" data-t="Backtest eseguito">Esegui backtest</button><div class="row" style="margin-top:10px"><b class="pos" style="font:800 24px var(--f-display)">+£1,20</b><span class="foot">7 trade · 5 win / 2 loss · 12 tentativi · 5 mai abbinati · ⚠ 1 non richiusi (worst-case)</span></div>');
      else h += '<div class="grid g2">' + (view === 'mo' ? [['Match Odds', [['Inter', '72%', 1.38, 1.39, '+£1,95'], ['Torino', '8%', 11.5, 12, '−£5,00'], ['The Draw', '20%', 5.6, 5.7, '−£5,00']]], ['Double Chance', [['Inter or Draw', '92%', 1.08, 1.09, '—'], ['Draw or Torino', '28%', 3.4, 3.5, '—']]]] : [['Over/Under 2.5 Goals', [['Under 2.5 Goals', '61%', 1.62, 1.63, '—'], ['Over 2.5 Goals', '39%', 2.6, 2.62, '—']]], ['Over/Under 3.5 Goals', [['Under 3.5 Goals', '82%', 1.22, 1.23, '—'], ['Over 3.5 Goals', '18%', 5.6, 5.8, '—']]]]).map(function (m) {
        return S.panel(m[0], '<div class="row" style="margin-bottom:8px;font-size:12px"><span class="lbl">Stake</span><select class="inp" id="mr-st-' + m[0].length + '"><option>€10</option><option>€25</option><option>€50</option><option>€100</option></select><input class="inp" style="width:60px" value="10" title="Minimo Betfair €2"><button class="btn sm gold" style="margin-left:auto">Cash out: +£0,46</button></div><table class="t"><thead><tr><th>Selezione</th><th class="r">Win %</th><th class="r">Back</th><th class="r">Lay</th><th class="r">Position</th></tr></thead><tbody>' + m[1].map(function (r) { return '<tr><td>' + r[0] + '</td><td class="r">' + r[1] + '</td><td class="r"><span class="o b">' + S.odds(r[2]) + '</span></td><td class="r"><span class="o l">' + S.odds(r[3]) + '</span></td><td class="r ' + (r[4][0] === '+' ? 'pos' : r[4][0] === '−' ? 'neg' : 'mut') + '">' + r[4] + '</td></tr>'; }).join('') + '</tbody></table>');
      }).join('') + '</div>' + S.panel('Trades (1 aperte · 0 chiuse)', '<table class="t"><thead><tr><th>Min</th><th>Selezione</th><th>Tipo</th><th class="r">Quota</th><th class="r">Stake</th><th class="r">Return/Liab</th><th></th></tr></thead><tbody><tr><td>41′</td><td>Inter <span class="foot">Match Odds</span></td><td style="color:var(--back)">back</td><td class="r">1,52</td><td class="r">£5,00</td><td class="r">£7,60</td><td class="pos">abbinato</td></tr></tbody></table><p class="foot">Nota P&L. Semantica Betfair Exchange. BACK stake S a quota O: vince → +S·(O-1), perde → −S. LAY stake S a quota O: la selezione vince → −S·(O-1) (liability), perde → +S. Simulazione didattica su dati storici.</p>', { flush: false });
      return h;
    }
  });
  S.on('mr-load', function () { S.ui.rpLoaded = true; S.rerender(); window.scrollTo(0, 0); });
  S.on('mr-end', function () { S.ui.rpLoaded = false; S.rerender(); });
})();
