/* s_calcio.js - pagine bot calcio: Omega, Safe Strategy (calcio + tennis), Mike.
   Ordine dei blocchi e testi dall'inventario B_BOT_CALCIO.md (il codice vince sul DESIGN_SYSTEM.md). */
(function () {
  'use strict';
  var S = window.S, D = window.D, C = S.C, M = S.money, mk = S.mk, chip = S.chip;
  var tile = function (k, v, s, tone, tid) { return '<div class="kpi"' + (tid ? ' data-testid="' + tid + '"' : '') + '><div class="k">' + k + '</div><div class="v ' + (tone || '') + '">' + v + '</div>' + (s ? '<div class="s">' + s + '</div>' : '') + '</div>'; };
  var sub = function (scr, items, def) { return S.tabbar(scr, items, def); };
  var altra = function (testid, mode, oggi, tot, liab) {
    var other = mode === 'LIVE' ? 'PAPER' : 'LIVE';
    return '<div class="strip info" data-testid="' + testid + '" style="font-size:11.5px">' + chip(other, other === 'LIVE' ? 'live' : 'sky') + '<span>(contabilità separata, NON inclusa nei numeri ' + mode + ' qui sopra):</span><span>oggi <b class="' + S.tone(oggi) + '">' + M(oggi, { signed: true }) + '</b></span><span>· totale storico <b class="' + S.tone(tot) + '">' + M(tot, { signed: true }) + '</b></span><span>· Liability aperta <b class="ora">' + M(liab) + '</b></span></div>';
  };
  var activity = function (rows) { return C.activity(rows); };

  /* ============================== OMEGA ============================== */
  var OM_MATCH = [
    { ora: '09:41', ko: '09:40', nome: 'Inter v Torino', live: "58′ · 1-0", ht: { side: 'LAY', sel: '0 - 0', q: 8.4, stake: 1, rischio: 7.4, ingr: "22′ 0-0", p: '1,9 %', mp: '11,9 %', stato: 'CHIUSO IN UTILE', pnl: 0.95 }, rht: ['1 - 0', false], ft: { side: 'LAY', sel: '1 - 1', q: 12, stake: 1, rischio: 11, ingr: "51′ 1-0", p: '1,4 %', mp: '8,3 %', stato: 'APERTO', live: 'ora LAY 13,5 / BACK 13', close: 0.08 }, rft: null, pnl: null, nota: '1/2 decise · rischio 11,00 €' },
    { ora: '08:12', ko: '08:00', nome: 'Feyenoord v AZ Alkmaar', live: 'regolata', ht: { side: 'LAY', sel: '2 - 0', q: 26, stake: 1, rischio: 0, ingr: "31′ 0-0", p: '0,9 %', mp: '3,8 %', stato: 'CHIUSO IN GREEN-UP', pnl: 0.62 }, rht: ['0 - 0', false], ft: { side: 'LAY', sel: '0 - 3', q: 34, stake: 1, rischio: 0, ingr: "62′ 1-1", p: '0,6 %', mp: '2,9 %', stato: 'VINTO', pnl: 0.95 }, rft: ['1 - 1', false], pnl: 1.57, nota: 'regolato' },
    { ora: '07:31', ko: '07:30', nome: 'Benfica B v Porto B', live: 'regolata', ht: { side: 'LAY', sel: '0 - 2', q: 22, stake: 1, rischio: 0, ingr: "28′ 0-0", p: '1,1 %', mp: '4,5 %', stato: 'PERSO', pnl: -21 }, rht: ['0 - 2', true], ft: null, rft: ['1 - 3', false], pnl: -21, nota: 'regolato' }
  ];
  function omegaLeg(g) {
    if (!g) return '<span class="foot">in attesa della finestra</span>';
    return '<div class="col" style="gap:3px;min-width:240px;font-size:11.5px"><div class="row" style="gap:6px">' + chip(g.side, g.side === 'LAY' ? 'rose' : 'sky') + '<b style="font-size:14px">' + g.sel + '</b><span class="mono" data-testid="omega-entry-price">@' + S.odds(g.q) + '</span></div>' +
      '<div class="foot">stake <b>' + M(g.stake) + '</b> · rischio <b class="ora">' + M(g.rischio) + '</b> · ingresso ' + g.ingr + ' · <span data-testid="omega-model-p">P(perdita) <b>' + g.p + '</b> · mercato <b>' + g.mp + '</b></span></div>' +
      '<div class="foot mono" data-testid="omega-stato-ordine">' + chip('ABBINATO', 'paper') + ' chiesto <b>' + M(g.stake) + '</b> @' + S.odds(g.q) + ' · abbinato <b class="pos">' + M(g.stake) + '</b> · da Betfair 2 s fa</div>' +
      (g.live ? '<div class="foot" data-testid="omega-leg-live">' + g.live + ' · <span class="pos">feed 1 s</span> · se chiudo ora <b class="' + S.tone(g.close) + '" data-testid="omega-close-now">' + M(g.close, { signed: true }) + '</b> netti</div>' : '') +
      '<div class="row" style="gap:6px">' + chip(g.stato, /PERSO|PERDITA/.test(g.stato) ? 'red' : /APERTO/.test(g.stato) ? 'sky' : 'teal') + (g.pnl != null ? '<b class="' + S.tone(g.pnl) + '" data-testid="omega-leg-pnl">' + M(g.pnl, { signed: true }) + '</b>' : '<span class="foot" data-testid="omega-leg-open">in corso</span>') +
      (g.stato === 'APERTO' ? '<button class="btn sm gold" data-act="cashout-dlg" data-v="omega" data-testid="cashout-trigger">Cash out ' + M(g.close, { signed: true }) + '</button>' : '') + '</div></div>';
  }
  function omegaTable() {
    return '<div class="tbl-w"><table class="t" data-testid="omega-matches-table" style="vertical-align:top"><thead><tr><th>Ora</th><th>Partita</th><th>1° tempo</th><th>Risultato 1T</th><th>2° tempo</th><th>Risultato 2T</th><th class="r">P&L partita</th></tr></thead><tbody>' +
      OM_MATCH.map(function (m) {
        var res = function (r, k) { return r ? '<td data-testid="omega-result-' + k + '"><b style="font-size:15px" class="' + (r[1] ? 'neg' : '') + '">' + r[0] + '</b><div class="foot ' + (r[1] ? 'neg' : 'pos') + '">' + (r[1] ? 'bancato USCITO' : 'bancato non uscito') + '</div></td>' : '<td class="mut" title="in attesa del fischio finale">—</td>'; };
        var bordo = m.pnl == null ? 'var(--back)' : m.pnl >= 0 ? 'var(--emerald)' : 'var(--red)';
        return '<tr data-testid="omega-match-row" style="vertical-align:top"><td style="border-left:3px solid ' + bordo + '"><div class="mono">' + m.ora + '</div><div class="foot">KO ' + m.ko + '</div></td><td style="white-space:normal;min-width:150px"><b>' + m.nome + '</b><div class="foot" data-testid="omega-live-score">' + (m.pnl == null ? '<span class="led on" style="display:inline-block"></span> ' : '') + m.live + '</div>' + (m.pnl == null ? '<div class="foot pos" data-testid="omega-feed-age">feed 1 s</div>' : '') + '</td>' +
          '<td data-testid="omega-leg-ht">' + omegaLeg(m.ht) + '</td>' + res(m.rht, 'ht') + '<td data-testid="omega-leg-ft">' + omegaLeg(m.ft) + '</td>' + res(m.rft, 'ft') +
          '<td class="r" data-testid="omega-match-pnl"><b style="font-size:16px" class="' + S.tone(m.pnl) + '">' + (m.pnl == null ? '—' : M(m.pnl, { signed: true })) + '</b><div class="foot">' + m.nota + '</div></td></tr>';
      }).join('') + '</tbody></table></div>';
  }
  function omegaMissione() {
    var h = '<section class="panel" style="padding:14px;display:flex;gap:18px;flex-wrap:wrap;align-items:flex-end">' +
      '<label class="field" for="om-goal">Obiettivo giornata (€)<span class="row"><input id="om-goal" value="250" style="width:100px"><button class="btn sm" data-act="toast" data-t="Obiettivo salvato sul servizio" data-testid="mission-save-goal">Salva</button></span></label>' +
      '<div><div class="lbl">Partite attivabili</div><b style="font:800 22px var(--f-display)" data-testid="mission-events-count">17</b><div class="foot">elenco aggiornato 4 min fa</div></div>' +
      '<div><div class="lbl">Target / partita</div><b class="gold" style="font:800 22px var(--f-display)" data-testid="mission-target-match">14,70 €</b><div class="foot" data-testid="mission-target-source">dal servizio · 17 partite rimaste</div></div>' +
      '<div><div class="lbl">Missioni</div><b style="font:800 22px var(--f-display)">2 / 3</b><div class="foot">attive / totali</div></div>' +
      '<div class="row" style="margin-left:auto"><label class="row" style="font-size:12px"><input type="checkbox" id="om-solo"> solo attive</label><button class="btn" data-act="toast" data-t="Eventi aggiornati: 17 partite di oggi">↻ Aggiorna eventi</button></div>' +
      '<p class="foot" style="width:100%;margin:0" data-testid="mission-day-note">Avanzamento della giornata e obiettivo: nella barra in cima alla pagina (numeri della RPC). Di quel totale, <b class="pos" data-testid="mission-day-realized">+0,95 €</b> viene dalle missioni attivate oggi.</p></section>';
    var open = S.ui.omMis !== false;
    h += '<article class="panel flat" style="padding:0"><button class="row" data-act="om-mis" style="width:100%;border:0;background:none;padding:10px 12px;cursor:pointer;flex-wrap:wrap">' + (open ? '▾' : '▸') + '<span class="led on"></span><b>Inter v Torino</b>' + chip('2T', 'paper') + '<span class="mono">58′</span><b style="font:800 18px var(--f-display)">1 - 0</b>' +
      '<span class="row" style="margin-left:auto;gap:8px"><a class="btn sm" data-go="dashboard" href="#dashboard">Statistiche</a><a class="btn sm" data-go="segui-live" href="#segui-live">Trading</a><span class="btn sm danger">● REC</span><span class="foot"><span style="color:var(--back)">1 aperta</span> · 1 regolata</span><b class="pos">+0,95 €</b><span class="foot">/ 14,70 €</span><span class="bar" style="width:60px;display:inline-block"><i style="width:7%"></i></span></span></button>';
    if (open) h += '<div style="padding:0 12px 12px;display:flex;flex-direction:column;gap:8px">' +
      // riga SCALP
      '<div class="row" style="padding:8px 10px;border-radius:8px;background:hsl(var(--muted)/.5);font-size:12px"><b>Scalp</b>' + S.icon('bot') + '<span>gap <b class="gold">13,75 €</b></span><span class="foot">bot non attivo su questa partita</span><span class="row" style="margin-left:auto"><select class="inp" id="om-preset" aria-label="Preset scalper"><option>🎯 cecchino (3 step)</option><option>quiete (classico)</option><option>post-gol (overshoot)</option></select><button class="btn sm" style="background:rgba(14,165,233,.85);color:#001018;border-color:transparent" data-act="toast" data-t="SCALPER 1-TICK avviato (paper, cecchino)" data-d="Sempre PAPER da questa UI: stake 25, theta.">⚡ AVVIA SCALPER 1-TICK</button></span></div>' +
      // riga 1T / 2T
      ['1T', '2T'].map(function (g, i) {
        return '<div class="row" style="padding:8px 10px;border-radius:8px;border:1px solid hsl(var(--border));font-size:12px"><b style="width:26px">' + g + '</b><b style="color:var(--lay)">' + (i ? '2 - 1' : '0 - 0') + '</b><span data-testid="mission-lay-price">lay @ <b>' + (i ? '24,00' : '—') + '</b> <span class="led on" style="display:inline-block"></span></span><span class="foot" data-testid="mission-lay-liq">liq. ' + (i ? '38 €' : '—') + '</span><span class="foot">Correct Score</span>' +
          (i ? '<input class="inp" id="om-size-' + g + '" value="1" aria-label="Size lay ' + g + '" style="width:60px;height:26px"><button class="btn sm" style="color:var(--lay);border-color:var(--lay-bd);background:var(--lay-bg)" data-act="om-place">⚡ PIAZZA LAY 1,00 €</button>' : '<span class="foot">gamba già piazzata e chiusa in utile</span>') +
          '<span class="foot" data-testid="mission-leg-risk" style="width:100%">rischio vivo <b class="ora">' + (i ? '0,00 €' : '0,00 €') + '</b> · bloccato <b class="pos">' + (i ? '—' : '+0,95 €') + '</b> · Poisson/lega/H2H — dati nostri, decidi tu</span></div>';
      }).join('') +
      '<div class="row"><button class="btn sm">Pausa</button><button class="btn sm danger" data-act="toast" data-t="Chiudere DEFINITIVAMENTE la missione?" data-d="Nel prodotto chiede conferma.">Chiudi missione</button><span style="margin-left:auto">' + S.media(true) + '</span></div></div>';
    h += '</article>';
    h += '<div class="lbl" style="margin-top:6px">🏆 SERIE A (4)</div>' + ['Bologna v Udinese · 10:52', 'Atalanta v Genoa · 12:22', 'Napoli v Lazio · 14:52'].map(function (e) { return '<div class="row" style="padding:7px 10px;border-radius:8px;background:hsl(var(--muted)/.4);font-size:12px"><b>' + e + '</b><span style="margin-left:auto" class="row"><a class="btn sm" data-go="dashboard" href="#dashboard">Statistiche</a><a class="btn sm" data-go="segui-live" href="#segui-live">Trading</a><button class="btn sm" data-act="toast" data-t="Segui live">Segui live</button><button class="btn sm gold" data-act="om-attiva" data-v="' + e + '">◎ ATTIVA</button></span></div>'; }).join('');
    return h;
  }
  S.on('om-mis', function () { S.ui.omMis = S.ui.omMis === false; S.rerender(); });
  S.on('om-attiva', function (t) { S.modal({ title: '◎ Attiva missione', body: '<p class="foot" style="margin-top:0">' + t.dataset.v + '</p><label class="field" for="om-tgt">Target € della partita<input id="om-tgt" value="14,70"></label><p class="foot" data-testid="mission-target-note">suggerito: 14,70 € (obiettivo diviso per 17 partite in finestra)</p>', ok: 'Attiva', onOk: function () { S.toast('Missione attivata', t.dataset.v + ' · target 14,70 €'); } }); });
  S.on('om-place', function () {
    var live = D.botMode.omega.mode === 'LIVE';
    S.modal({ danger: live, title: live ? 'SOLDI VERI — conferma ordine LIVE' : 'Conferma ordine (PAPER)', body: '<p style="margin-top:0">2T · LAY su 2 - 1 — Correct Score</p><p class="foot">quota 24,00 (live, 1s fa) · importo 1,00 €</p><p style="font:800 20px var(--f-display)" class="' + (live ? 'neg' : '') + '">Rischio massimo: 23,00 €</p><p class="foot" data-testid="mission-draft-net">Se vinci incassi ≈ 0,95 € (netto commissione 5 %)</p>' + (live ? '<div class="strip live">Ordine REALE su Betfair: denaro vero.</div>' : ''), ok: live ? 'Sì, piazza LIVE' : 'Piazza (paper)' });
  });
  function omegaManuale() {
    var b = D.botMode.omega.mode;
    return '<div class="strip warn">Le azioni qui accodano richieste eseguite dal <b>servizio locale</b> (avvia_omega_service.bat). In <b>PAPER</b> è simulato; in <b>LIVE</b> sono soldi veri. Se non vedi eventi/quote, avvia prima il servizio.</div>' +
      '<div class="grid g2"><section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:10px"><div class="row" style="justify-content:space-between"><b>1 · Evento</b><button class="btn sm">↻ Aggiorna eventi</button></div><select class="inp" id="om-ev"><option>— scegli evento (17) —</option><option>Inter v Torino · 09:40 · LIVE 58′ · 1-0</option><option>Bologna v Udinese · 10:52</option></select><p class="foot" style="margin:0" data-testid="manual-events-note">solo le partite ancora operabili (non finite) · elenco di 4 min fa · minuto e punteggio LIVE con 2-3 s di ritardo</p>' +
      '<div class="row" style="justify-content:space-between"><b>2 · Mercato</b><button class="btn sm">Carica mercati</button></div><select class="inp" id="om-mk"><option>— scegli mercato (24) —</option><option>Risultato esatto [CORRECT_SCORE]</option></select><button class="btn" style="justify-content:center">3 · Carica quote del mercato</button></section>' +
      '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:10px"><b>4 · Ordine</b><div class="row"><div class="seg"><button aria-pressed="false" style="color:var(--back)">BACK</button><button aria-pressed="true" style="color:var(--lay)">LAY</button></div><div class="seg mode"><button data-v="PAPER" aria-pressed="' + (b !== 'LIVE') + '">PAPER</button><button data-v="LIVE" aria-pressed="' + (b === 'LIVE') + '">LIVE</button></div></div>' +
      '<div style="font-size:12px">Selezione: <b>2 - 2</b></div><div class="grid g2"><label class="field" for="om-q">Quota<input id="om-q" value="38"></label><label class="field" for="om-t">Target profitto € (incasso se NON esce)<input id="om-t" value="1"></label></div><div class="foot">Dimensiona per <span class="chip">Target €</span> <span class="chip">Stake €</span></div>' +
      '<div class="row" style="font-size:12px"><span data-testid="manual-preview-stake">Stake ≈ <b>1,00 €</b></span><span data-testid="manual-preview-liability">Liability aperta ≈ <b class="ora">37,00 €</b></span></div><div class="foot pos" data-testid="manual-matchable">abbinabile subito al miglior LAY: 22 €</div>' +
      '<button class="btn ' + (b === 'LIVE' ? 'danger' : 'pri') + '" style="justify-content:center;height:36px" data-act="toast" data-t="Richiesta accodata al servizio">Piazza LAY (' + (b === 'LIVE' ? 'SOLDI VERI' : 'paper') + ')</button></section></div>' +
      S.panel('Risultato esatto · IN CORSO', '<div class="tbl-w"><table class="t"><thead><tr><th>Selezione</th><th class="r">Back</th><th class="r">Lay</th><th class="r">Liq. back</th><th class="r">Liq. lay</th><th></th></tr></thead><tbody>' + [['1 - 0', 3.6, 3.7, 412, 230], ['2 - 0', 6.4, 6.6, 120, 88], ['2 - 1', 23, 24, 31, 38], ['2 - 2', 36, 38, 12, 22]].map(function (r) { return '<tr data-testid="manual-runner"><td>' + r[0] + '</td><td class="r" style="color:var(--back)">' + S.odds(r[1]) + '</td><td class="r" style="color:var(--lay)">' + S.odds(r[2]) + '</td><td class="r">' + r[3] + ' €</td><td class="r">' + r[4] + ' €</td><td><button class="btn sm">usa</button></td></tr>'; }).join('') + '</tbody></table></div>', { flush: true, right: '<span class="foot" data-testid="manual-book-age">quote di 3 s</span><button class="btn sm">Suggerisci meno probabile</button>' }) +
      S.panel('Ultime richieste al servizio', [['10:41:02', 'carica quote', 'ESEGUITA', 'paper'], ['10:40:47', 'carica mercati', 'ESEGUITA', 'paper'], ['10:38:10', 'piazza ordine', 'IN ATTESA DI ABBINAMENTO', 'amber']].map(function (r) { return '<div class="row" data-testid="manual-request" style="font-size:12px;padding:3px 0"><span class="mono foot">' + r[0] + '</span>' + r[1] + '<span style="margin-left:auto">' + chip(r[2], r[3]) + '</span></div>'; }).join(''));
  }
  S.reg({
    id: 'omega', title: 'Omega', group: 'Calcio · bot',
    render: function () {
      var mode = D.botMode.omega.mode, tab = S.tab('omega', 'auto');
      var h = C.botHeader({ key: 'omega', name: 'OMEGA', symbol: 'Ω', accent: 'hsl(var(--primary))', sub: 'Correct Score LAY, set-and-forget · obiettivo €/giorno → target per partita → un lay per gamba', params: true, extraChip: chip('canale locale', 'paper'), health: { beat: 'servizio Omega vivo (3 s)', src: '⚡ STREAM 152' }, liveText: 'Omega piazza <b>lay reali</b> sul Correct Score con <b>soldi veri</b>.', paperText: 'simulazione fedele: coda, liquidità, betDelay e protezioni identiche al live, nessun denaro reale.' });
      h += '<div data-testid="omega-daily-mission">' + C.dayBar({ realized: 1.57, goal: 250, ops: 5, v: 3, p: 1, vive: 1, locked: 0.95, total: 412.6, note: 'numeri dalla RPC (giornata Europe/Rome): il realizzato riparte da zero ogni giorno e conta SOLO le posizioni piazzate oggi' }) + '</div>';
      h += '<section class="panel" data-testid="omega-chiuse-dall-utente" style="padding:10px 14px;border-color:rgba(251,191,36,.45)"><div class="amb lbl">Partite che hai chiuso tu — il bot non ci opera più</div><div class="row" data-testid="omega-chiusa-riga" style="font-size:12px;margin-top:6px"><b>Benfica B v Porto B</b><span class="foot">chiusa da te</span><span class="mono foot">08:55</span><button class="btn sm ghost" style="margin-left:auto" data-act="toast" data-t="Partita riportata in carico al bot" title="riporta la partita in carico al bot: e’ l’unico modo di togliere lo stato">↩ Riprendi</button></div></section>';
      h += '<div class="grid g4" data-testid="kpi-row">' + tile('Liability aperta', '<span class="ora">' + M(11) + '</span>', 'rischio vivo adesso: quanto perdi se escono i risultati bancati (copertura completa = 0)<br><span data-testid="omega-liability-bot">su cui decide il bot <b>11,00 €</b></span>', '', 'omega-kpi-liability') + tile('P&L bloccato', '<span class="pos">+0,95 €</span>', 'di oggi +0,95 € · già bloccato sulle posizioni vive: non cambia più', '', 'omega-kpi-locked') + tile('In verifica su Betfair', M(0), 'nessun ordine in sospeso', '', 'omega-kpi-reconciling') + tile('Target / operazione', '<span class="gold">7,35 €</span>', '3 operazioni e 2 partite ancora in finestra (su 41 viste dallo scanner) · 14,70 €/partita', '', 'omega-kpi-target') + '</div>';
      h += altra('omega-altra-modalita', mode, 0, -3.2, 0);
      h += S.tabbar('omega', [['auto', '⚙️ Automatico'], ['missione', '🎯 Missione'], ['manuale', '✋ Manuale'], ['storico', '📅 Storico']], 'auto');
      if (tab === 'auto') {
        var days = D.giorni('omega', 'paper', 1);
        h += C.equityCard([{ iso: 'a', date: new Date(2026, 9, 1, 8), pnl: -21 }, { iso: 'b', date: new Date(2026, 9, 1, 9), pnl: 1.57 }, { iso: 'c', date: new Date(2026, 9, 1, 10), pnl: 0.95 }], 'giornata 1 ottobre');
        h += S.panel('Partite di oggi', '<div class="foot" data-testid="omega-matches-summary" style="margin-bottom:10px">· 5 operazioni oggi · 3V 1P · 1 partite vive · P&L bloccato +0,95 € · Liability aperta 11,00 € · storico 211 partite</div>' +
          C.eventPnl({ testId: 'omega-totali-operazioni', mode: mode, rows: [{ match: 'Inter v Torino', n: 2, inv: 2, liab: 11, closed: false, pnl: 0.95, q: 12, sel: '1 - 1', ora: '09:41' }, { match: 'Feyenoord v AZ Alkmaar', n: 2, inv: 2, liab: 0, closed: true, pnl: 1.57, q: 26, sel: '2 - 0', ora: '08:12', ora2: '08:44' }, { match: 'Benfica B v Porto B', n: 1, inv: 1, liab: 0, closed: true, pnl: -21, q: 22, sel: '0 - 2', ora: '07:31', ora2: '08:15' }] }) + omegaTable(), { icon: 'pulse', count: 3, id: 'omega-matches-card', right: '<span class="foot">ogni riga: gamba 1° tempo + gamba 2° tempo, quote live, risultati reali, P&L della partita</span><button class="btn sm ghost" data-testid="omega-matches-toggle">mostra tutte</button>' });
        h += S.panel('Attività del servizio di oggi', activity([['10:41:22', 'ORDINE', 'sky', 'Inter v Torino · LAY 1 - 1 @12,00 · 1,00 € (gamba 2T)'], ['10:41:24', 'ABBINATO (flumine)', 'paper', 'Inter v Torino · 1,00 € @12,00'], ['10:12:03', 'GREEN-UP', 'teal', 'Feyenoord v AZ · chiuso a mercato +0,62 €'], ['09:58:40', 'SALTO', '', 'Lens v Nantes · P(modello) 2,6 % sopra il tetto 2 %'], ['08:15:00', 'REGOLATA', 'red', 'Benfica B v Porto B · bancato USCITO −21,00 €']]), { icon: 'bolt', count: 60, id: 'omega-activity', right: '<span class="foot">ogni passo del servizio: ingressi, coda ordini, verifiche, green-up, regolamenti · giornata 1 ottobre</span><button class="btn sm ghost" data-testid="omega-activity-more">carica altre (120)</button>' });
      } else if (tab === 'missione') h += omegaMissione();
      else if (tab === 'manuale') h += omegaManuale();
      else h += C.tradingHistory('omega', 'omega-st');
      return h;
    }
  });

  /* ============================== SAFE ============================== */
  var SIGNALS = [
    { strat: 'BASE', col: 'var(--lay)', side: 'LAY', title: 'BANCA Getafe', q: 22, abb: '84 €', liab: '42,00 €', match: 'Real Betis – Getafe', ctx: "58′ · 1-0 al segnale", ago: '12s fa', trade: false },
    { strat: 'R.E. CASA', col: '#c4b5fd', side: 'LAY', title: 'BANCA Altro risultato CASA (Inter)', q: 46, abb: '18 €', liab: '90,00 €', match: 'Inter – Torino', ctx: "58′ · 1-0 al segnale", ago: '41s fa', trade: true },
    { strat: 'PUNTA', col: 'var(--back)', side: 'BACK', title: 'PUNTA Inter', q: 1.06, abb: '1.420 €', liab: '2,00 €', match: 'Inter – Torino', ctx: "70′ · 2-0 al segnale", ago: '3m fa', trade: false, scaduto: true }
  ];
  function investAction(k, side) {
    var live = D.botMode.safe.mode === 'LIVE', armed = S.ui['inv_' + k];
    return '<div class="row" style="gap:8px;font-size:11.5px"><label class="field" for="inv-' + k + '" style="width:120px">STAKE € (da ' + (side === 'LAY' ? 'bancare' : 'puntare') + ')<input id="inv-' + k + '" value="2" style="height:26px"></label>' +
      '<button class="btn sm ' + (live ? 'danger' : 'pri') + '" data-act="inv" data-k="' + k + '" data-testid="invest-place">' + (armed ? 'Confermi? soldi veri' : 'Piazza (' + (live ? 'LIVE' : 'PAPER') + ')') + '</button>' +
      '<span class="foot" data-testid="invest-matchable">abbinabile subito <b>84 €</b> · responsabilità se abbinato <b class="ora">42,00 €</b></span></div>';
  }
  S.on('inv', function (t) { var k = t.dataset.k; if (D.botMode.safe.mode === 'LIVE' && !S.ui['inv_' + k]) { S.ui['inv_' + k] = 1; S.rerender(); setTimeout(function () { S.ui['inv_' + k] = 0; }, 10000); return; } S.ui['inv_' + k] = 0; S.rerender(); S.toast('Ordine in coda', 'Prototipo: nessun ordine reale.'); });
  function signalCard(s, i) {
    return '<article class="panel flat" style="padding:12px;border-left:4px solid ' + s.col + ';display:flex;flex-direction:column;gap:6px;' + (s.scaduto ? 'opacity:.5' : '') + '"><div class="row">' + '<span class="chip" style="color:' + s.col + '">' + s.strat + '</span>' + chip(s.side, s.side === 'LAY' ? 'rose' : 'sky') + '<span class="mono foot" style="margin-left:auto">10:4' + i + ' · ' + s.ago + '</span></div>' +
      '<div class="row"><h3 style="font-size:16px">' + s.title + '</h3><b class="prim" style="font:800 22px var(--f-display);margin-left:auto">@' + S.odds(s.q) + '</b></div><div class="foot">Abbinabile subito <b>' + s.abb + '</b> da ' + (s.side === 'LAY' ? 'bancare' : 'puntare') + ' · Liability aperta ' + s.liab + '</div>' +
      '<div class="foot" data-testid="signal-context">' + s.match + ' · ' + s.ctx + (s.scaduto ? ' <span class="amb">condizioni non più valide</span>' : '') + '</div>' + S.media(false) +
      (s.trade ? '<div class="row" data-testid="signal-trade" style="font-size:12px">' + chip('APERTO', 'sky') + 'LAY 2,00 € @46,00<span class="foot" data-testid="signal-hold">In attesa: P(perdita) 1,8 % sotto la soglia di tenuta</span><button class="btn sm gold" data-act="cashout-dlg" data-v="safe">Cash out +0,30 €</button><span class="chip pos" data-testid="feed-age">feed 1s</span></div>'
        : (s.scaduto ? '' : investAction('sig' + i, s.side) + '<div class="foot mono" data-testid="signal-placement">mercato <b>MATCH_ODDS</b> 1.2345 · selezione 58805 · best lay 22,00 (84 € abbinabili)</div>')) + '</article>';
  }
  function oppGroup(sport) {
    var tn = sport === 'tennis';
    return '<article class="panel flat" data-testid="opp-group" style="padding:12px;display:flex;flex-direction:column;gap:8px"><div class="row"><b style="font-family:var(--f-display)">' + (tn ? 'J. Sinner – J. Draper' : 'Real Betis – Getafe') + '</b><span class="chip" data-testid="opp-score">' + (tn ? 'set 1-0 · game 2-1' : "31′ · 0-0") + '</span>' + (tn ? '' : '<span class="chip">λ 1,21 / 0,84</span><span class="chip" data-testid="opp-lambda-source">λ dal motore della partita</span>') + '<span class="chip" data-testid="opp-age">calcolo 4s fa</span><span class="chip pos" data-testid="opp-feed-age">feed 1s</span><span class="foot" style="margin-left:auto">2 opp.</span></div>' +
      [['MODELLO', 'sky', 'BACK', tn ? 'J. Sinner' : 'Under 2.5 Goals', tn ? 'Match Odds' : 'Under 2.5', tn ? 1.25 : 1.58, '67,9 %', '63,3 %', '+4,6 %', '0,029', 74], [tn ? 'TENNIS' : 'ANOMALIA', tn ? 'gold' : 'amber', 'LAY', tn ? 'J. Draper' : 'Over 3.5 Goals', tn ? 'Match Odds' : 'Over 3.5', tn ? 5.1 : 4.4, '18,1 %', '22,7 %', '+4,6 %', '0,041', 81]].map(function (o, i) {
        return '<div data-testid="opp-row" data-kind="' + o[0] + '" style="padding:8px;border-radius:8px;background:hsl(var(--muted)/.45);display:flex;flex-direction:column;gap:6px"><div class="row">' + chip(o[0], o[1]) + chip(o[2], o[2] === 'BACK' ? 'sky' : 'rose') + '<b>' + o[3] + '</b><span class="foot">' + o[4] + '</span><b class="mono" style="margin-left:auto;font-size:16px">@' + S.odds(o[5]) + '</b></div>' +
          (o[0] === 'ANOMALIA' ? '<div class="foot" data-testid="anomaly-rule">REGOLA scala Under/Over incoerente · scarto +4,1 %</div>' : '') + (o[0] === 'TENNIS' ? '<div class="foot" data-testid="tennis-extra">set 1-0 · game 2-1 · al meglio di 3 · serve: J. Sinner ' + chip('ritiro 2 %') + '</div>' : '') +
          '<div class="grid g4" style="gap:6px">' + tile('Modello', o[6]) + tile('Implicita', o[7]) + tile('Edge', '<span class="pos">' + o[8] + '</span>') + tile('EV', o[9]) + '</div><div class="row foot"><span>Confidenza</span><span class="bar" style="flex:1"><i style="width:' + o[10] + '%"></i></span><b>' + o[10] + ' %</b></div>' + investAction('opp' + sport + i, o[2]) + '</div>';
      }).join('') + '</article>';
  }
  function monitorCard(sport, i) {
    var tn = sport === 'tennis';
    var strat = tn ? [['TENNIS', 2, 5, 1]] : [['BASE', 5, 1, 0], ['R. ESATTO', 3, 2, 1], ['PUNTA', 2, 3, 0]];
    var open = S.ui['mon_' + sport + i];
    return '<article class="panel flat" style="padding:10px 12px"><div class="row"><div><b>' + (tn ? ['J. Sinner – J. Draper', 'I. Swiatek – J. Paolini'][i] : ['Real Betis – Getafe', 'Inter – Torino'][i]) + '</b><div class="foot mono">' + (tn ? 'set 1-0 · game 2-1 · ATP Pechino' : (i ? "58′ · 1-0 · Serie A" : "31′ · 0-0 · La Liga")) + '</div></div><div class="row" style="margin-left:auto;gap:4px">' +
      strat.map(function (s) { return '<span class="chip" data-testid="monitor-variant-chip" title="su ' + (s[1] + s[2] + s[3]) + ' condizioni"><span class="led ' + (s[2] === 0 ? 'on' : s[3] ? 'warn' : 'off') + '"></span>' + s[0] + ' ' + s[1] + ' sì · ' + s[2] + ' no · ' + s[3] + ' n/d</span>'; }).join('') + '<button class="btn sm ghost" data-act="mon" data-v="' + sport + i + '" aria-label="' + (open ? 'Chiudi' : 'Apri') + ' dettaglio condizioni">' + (open ? '▾' : '▸') + '</button></div></div>' +
      (open ? '<div class="grid g2" style="margin-top:8px;font-size:11.5px">' + (tn ? [['✓', 'Match in-play', 'sì'], ['✓', 'Singolare (no doppio)', 'sì'], ['✕', 'Vantaggio di 1+ set', '1-0 → sì, ma game 2-1'], ['✕', '2+ game di vantaggio nel set corrente', '1'], ['✓', 'Al meglio dei 3 set', 'sì'], ['—', 'Quota back leader 1,02–1,10', 'n/d']] : [['✓', 'Dal minuto 55′ in poi', "58′"], ['✓', 'Partita in-play', 'sì'], ['✓', 'Favorita avanti 1-0, 2-0, 2-1', '1-0'], ['✓', 'Punteggio stabile da ≥30s', '412 s'], ['✕', 'Quota banca sfavorita 20–34', '11,5'], ['—', 'Favorita pre-match (banda)', 'n/d']]).map(function (c) { return '<div class="row" style="flex-wrap:nowrap"><b class="' + (c[0] === '✓' ? 'pos' : c[0] === '✕' ? 'neg' : 'amb') + '">' + c[0] + '</b><span>' + c[1] + '</span><span class="mono foot" style="margin-left:auto">' + c[2] + '</span></div>'; }).join('') + '</div>' : '') + '</article>';
  }
  S.on('mon', function (t) { var k = 'mon_' + t.dataset.v; S.ui[k] = !S.ui[k]; S.rerender(); });
  function safeTrades(sport) {
    var mode = D.botMode.safe.mode;
    var rows = sport === 'tennis' ? [{ match: 'J. Sinner – J. Draper', n: 1, inv: 3, liab: 3, closed: false, pnl: 0.2, q: 1.31, sel: 'J. Sinner', ora: '10:02' }] : [{ match: 'Real Betis – Getafe', n: 2, inv: 9, liab: 9.2, closed: false, pnl: 0.18, q: 3.3, sel: 'Pareggio', ora: '10:31' }, { match: 'Feyenoord – AZ Alkmaar', n: 1, inv: 2, liab: 0, closed: true, pnl: -2.2, q: 3.1, sel: 'Pareggio', ora: '08:10', ora2: '09:40' }];
    var tbl = '<div class="tbl-w" style="margin-top:10px"><table class="t" style="font-size:11.5px"><thead><tr><th>Ora (Roma)</th><th>Partita</th><th>Strategia</th><th>Mercato</th><th>Selezione</th><th>Lato</th><th class="r">Quota</th><th class="r">Quota ora</th><th class="r">Δ tick</th><th class="r">Stake</th><th class="r">Liability</th><th class="r">Se chiudo ora</th><th>Live</th><th>Stato</th><th class="r">P&L</th><th>Cash out</th></tr></thead><tbody>' +
      '<tr data-testid="safe-trade-row"><td class="mono">10:31</td><td>Real Betis – Getafe<div class="foot" data-testid="safe-entry-context">ingresso 18′ · 0-0</div></td><td>BASE ' + chip(mode, mode === 'LIVE' ? 'live' : '') + '<div class="foot">P(perdita) ingresso 21,0 %</div></td><td>Esito finale</td><td>Pareggio</td><td>' + chip('LAY', 'rose') + '</td><td class="r">3,30</td><td class="r">3,25</td><td class="r pos">▼ 1</td><td class="r">4,00 €</td><td class="r ora">9,20 €</td><td class="r pos">+0,06 €</td><td><span class="led on" style="display:inline-block"></span> 31′ 0-0</td><td>' + chip('APERTO', 'sky') + '</td><td class="r mut">—</td><td><button class="btn sm gold" data-act="cashout-dlg" data-v="safe">Cash out +0,06 €</button></td></tr>' +
      '<tr><td colspan="16" class="foot mono" data-testid="safe-stato-ordine">' + chip('ABBINATO', 'paper') + ' chiesto <b>4,00 €</b> @3,30 · abbinato <b class="pos">4,00 €</b> @3,30 · da Betfair 2 s fa</td></tr></tbody></table></div>';
    return C.equityCard([{ date: new Date(2026, 9, 1, 9), pnl: -2.2 }, { date: new Date(2026, 9, 1, 10), pnl: 0.18 }], 'giornata 1 ottobre') +
      S.panel('Operazioni di oggi', '<div class="row" style="margin-bottom:8px">' + C.storicoLink(sport, true).replace('btn sm', 'btn sm ghost') + '</div>' +
        '<div class="row" style="margin-bottom:8px">' + '<span class="foot" data-testid="safe-trades-summary">' + rows.length + ' posizioni oggi · 0V 1P · 1 vive</span><span class="foot">giornata operativa 1 ottobre · le giornate passate sono nello Storico</span><button class="btn sm ghost" data-testid="safe-trades-toggle">mostra tutte</button></div>' +
        '<div data-testid="cr-cashout-partita" class="row" style="margin-bottom:8px"><button class="btn sm" style="color:var(--lay);border-color:var(--lay-bd)" data-act="toast" data-t="Cash out globale della partita in coda" data-testid="cr-cashout-partita-avvia">⊗ Cash out Safe</button><span class="foot">chiude TUTTE le posizioni di SAFE su questa partita (non quelle degli altri bot) e gli dice di non fare altro</span></div>' +
        C.eventPnl({ testId: 'safe-trades-card', mode: mode, rows: rows }) + (sport === 'calcio' ? tbl : '') + '<p class="foot">Una riga per PARTITA col netto delle sue operazioni, commissione già tolta. Clicca per aprire le posizioni, le quote, gli stati e i bottoni di Cash out.</p>', { icon: 'pulse', count: rows.length, id: 'safe-trades-card' });
  }
  function oppFilters() {
    return '<div class="col" style="gap:6px"><div class="row" data-testid="opp-kind-filter"><span class="lbl">Tipo</span>' + [['tutte 6', ''], ['Modello 3', 'sky'], ['Anomalia 1', 'amber'], ['Combinazione 1', 'paper'], ['Tennis 1', 'gold']].map(function (x, i) { return '<button class="chip ' + x[1] + '" style="cursor:pointer;' + (i ? '' : 'border-color:hsl(var(--primary)/.6)') + '">' + x[0] + '</button>'; }).join('') + '</div>' +
      '<div class="row"><span class="lbl">Confidenza minima</span>' + ['tutte', '50%', '70%', '85%'].map(function (x, i) { return '<button class="chip" style="cursor:pointer;' + (i ? '' : 'border-color:hsl(var(--primary)/.6)') + '">' + x + '</button>'; }).join('') + '<span class="lbl" style="margin-left:10px">Lato</span>' + ['tutti', 'back', 'lay'].map(function (x, i) { return '<button class="chip" style="cursor:pointer;' + (i ? '' : 'border-color:hsl(var(--primary)/.6)') + '">' + x + '</button>'; }).join('') + '</div></div>';
  }
  function safeSport(sport) {
    var scr = 'safe-' + sport, st = S.tab(scr, 'segnali'), tn = sport === 'tennis';
    var h = sub(scr, [['segnali', 'Segnali', tn ? 0 : 2], ['opp', tn ? 'Opportunità tennis' : 'Opportunità modello', tn ? 2 : 2], ['monitor', 'Monitor', 2], ['trade', 'Trade', tn ? 1 : 2]], 'segnali');
    if (st === 'segnali') h += tn ? '<div class="empty">Nessun segnale attivo in questo momento: il radar continua a osservare.</div>' : '<div class="grid g2">' + SIGNALS.slice(0, 2).map(signalCard).join('') + '</div><details><summary class="lbl" style="cursor:pointer">Storico sessione calcio (1)</summary><div class="grid g2" style="margin-top:8px">' + signalCard(SIGNALS[2], 2) + '</div></details>';
    else if (st === 'opp') h += oppFilters() + '<div class="grid g2">' + oppGroup(sport) + (tn ? '' : '<article class="panel flat" style="padding:12px;display:flex;flex-direction:column;gap:6px"><div class="row"><b style="font-family:var(--f-display)">Inter – Torino</b><span class="chip">58′ · 1-0</span><span class="chip" data-testid="opp-age">calcolo 6s fa</span></div><div data-testid="opp-row" data-kind="COMBINAZIONE" style="padding:8px;border-radius:8px;background:hsl(var(--muted)/.45);display:flex;flex-direction:column;gap:6px"><div class="row">' + chip('COMBINAZIONE', 'paper') + '<b>scala Under</b><span class="foot">· 2 gambe · stake totale 6,00 €</span></div><div class="foot mono" data-testid="combo-legs">' + chip('BACK', 'sky') + ' Under 3.5 @1,22 · 4,20 € · abb. 310 €<br>' + chip('LAY', 'rose') + ' Under 4.5 @1,08 · 1,80 € · abb. 120 €</div><div class="grid g4" style="gap:6px" data-testid="combo-lock">' + tile('Bloccato / €', '0,031') + tile('Bloccato in €', '+0,19 €') + tile('Migliore / €', '0,05') + tile('Migliore in €', '+0,30 €') + '</div>' + investAction('combo', 'BACK') + '<p class="foot" style="margin:0">Piazza <b>tutte le 2 gambe</b> in un colpo (una richiesta per gamba, stessa chiave). Lo stake € è quello TOTALE della combinazione.</p></div></article>') + '</div>';
    else if (st === 'monitor') h += '<div class="col">' + monitorCard(sport, 0) + monitorCard(sport, 1) + '</div>';
    else h += safeTrades(sport);
    return h;
  }
  S.reg({
    id: 'safe-strategy', title: 'Safe Strategy', group: 'Calcio + Tennis · bot',
    render: function () {
      var mode = D.botMode.safe.mode, tab = S.tab('safe-strategy', 'calcio');
      var h = C.botHeader({ key: 'safe', name: 'SAFE STRATEGY', symbol: '🛡️', accent: 'hsl(var(--secondary))', statusPrefix: 'BOT', sub: 'Segnali live calcio + tennis · 4 strategie (BASE, R. ESATTO, PUNTA, TENNIS) + opportunità di modello', params: true, storico: C.storicoLink(tab === 'tennis' ? 'tennis' : 'calcio', true), health: { beat: 'servizio Safe vivo (1 s)', src: '⚡ STREAM 152' }, liveText: 'gli ordini piazzati da questa schermata e dal bot usano <b>soldi veri</b>.', paperText: 'simulazione fedele: coda, liquidità e protezioni identiche al live, nessun denaro reale.' });
      // PannelloBot «Strategie di Safe»
      var righe = S.CR.RIGHE_CALCIO.filter(function (r) { return /^safe/.test(r[0]); });
      h += S.panel('Strategie di Safe', '<p class="foot" style="margin:0 0 6px">Ogni strategia si accende, si spegne e sceglie la sua modalità da sola. <b>Spegnere l’ultima accesa ferma il servizio</b>: una lista di varianti vuota, per il servizio, vuol dire «tutte e quattro».</p>' +
        '<details open><summary class="lbl" style="cursor:pointer">BOT CALCIO (5)</summary>' + righe.map(S.CR.rigaBot).join('') + '</details><details><summary class="lbl" style="cursor:pointer;margin-top:8px">BOT TENNIS (1)</summary>' + S.CR.rigaBot(S.CR.RIGHE_TENNIS[0]) + '</details><p class="foot" style="margin:6px 0 0">Fermare spegne le <b>aperture</b>: le posizioni già a mercato restano sorvegliate e le puoi chiudere da qui.</p>', { id: 'safe-interruttori', right: '<button class="btn sm danger" data-act="cr-ferma-tutti" data-testid="cr-ferma-tutti">' + S.icon('stop') + ' Ferma tutti</button>' });
      h += '<div class="strip info" data-testid="safe-execution-route" role="status" style="font-size:11.5px">esecuzione: <b class="pos">coda flumine</b> — runner vivo e in streaming · runner in streaming (PAPER) · battito 1 s fa · 38 partite agganciate</div>';
      h += C.dayBar({ realized: -2.02, ops: 3, v: 0, p: 1, vive: 2, locked: 0.06, total: 118.4, note: 'modalità ' + mode + ' · al netto della commissione registrata su ogni trade · giorno di PIAZZAMENTO della posizione: gli stessi numeri dei KPI, del tab Trade e dello Storico' });
      h += '<div class="grid g4" data-testid="kpi-row">' + tile('Segnali attivi', '<span class="gold">2</span>', '2 calcio · 0 tennis') + tile('Trade aperti', '2', 'vive adesso', '', 'safe-kpi-open') + tile('P&L oggi · ' + mode, '<span class="neg">' + M(-2.02, { signed: true }) + '</span>', 'giornata operativa 1 ottobre · Europe/Rome · 0V 1P', '', 'safe-kpi-pnl-today') + tile('P&L totale · ' + mode, '<span class="pos">' + M(118.4, { signed: true }) + '</span>', '', '', 'safe-kpi-pnl-total') +
        tile('Liability aperta', '<span class="ora">' + M(12.2) + '</span>', 'rischio vivo ora su 2 posizioni', '', 'safe-kpi-liability') + tile('P&L bloccato', '<span class="tealc">+0,06 €</span>', 'posizioni chiuse a mercato oggi', '', 'safe-kpi-locked') + tile('Partite monitorate', '41', '⚽ 33 · 🎾 8<br><span class="amb" data-testid="safe-pre-ko-missing">2 partite senza riferimento pre-KO → BASE e PUNTA non valutabili su queste</span>', '', 'safe-kpi-monitored') +
        '<div class="kpi" data-testid="risk-panel" data-loss-stop="off"><div class="row" style="justify-content:space-between"><span class="k">' + S.icon('shield') + ' RISCHIO GIORNALIERO</span>' + chip('stop ok', 'paper') + '</div><div class="v" data-testid="risk-liability">14,20 € <span class="foot">impegnato oggi / cap 600,00 € · 2 %</span></div><div class="bar" style="margin:4px 0"><i style="width:2%"></i></div><div class="s" data-testid="risk-liability-bot">su cui decide il bot 14,20 €</div><div class="s" data-testid="risk-explain">somma delle liability PIAZZATE oggi (anche su posizioni già chiuse): è la base dei cap.</div><div class="row" data-testid="risk-opp-counts" style="margin-top:4px">' + chip('MODELLO 3', 'sky') + chip('ANOMALIA 1', 'amber') + chip('COMBINAZIONE 1', 'paper') + chip('TENNIS 1', 'gold') + '</div></div></div>';
      h += altra('safe-altra-modalita', mode, 0, 0, 0);
      h += S.tabbar('safe-strategy', [['calcio', '⚽ Calcio', 2], ['tennis', '🎾 Tennis', 0], ['storico', '📅 Storico']], 'calcio');
      if (tab === 'storico') {
        h += '<div class="row" data-testid="history-sport-filter"><span class="lbl">Sport</span><button class="chip" style="border-color:hsl(var(--primary)/.6)">tutti</button><button class="chip">⚽ calcio</button><button class="chip">🎾 tennis</button><span class="lbl" style="margin-left:10px">Modalità</span><button class="chip paper" data-testid="history-mode-paper">PAPER</button><button class="chip" data-testid="history-mode-live">LIVE</button><span class="foot">mai «tutte»: sommerebbe paper e live</span></div>' + C.tradingHistory('safe', 'safe-st');
      } else h += safeSport(tab);
      h += S.panel('Attività del servizio', '<div class="row" data-testid="activity-kind-filter" style="margin-bottom:8px"><span class="lbl">Tipo</span><button class="chip">tutti 48</button><button class="chip amber" data-testid="activity-kind-quick" title="solo le righe in cui il servizio ha deciso di NON entrare, col motivo">solo NON ENTRATO 31</button><button class="chip">ORDINE PIAZZATO 3</button><button class="chip">USCITA ESEGUITA 1</button></div>' +
        activity([['10:41:05', 'NON ENTRATO', 'amber', 'Lens – Nantes · riferimento quote pre-partita non disponibile: BASE e PUNTA non valutabili su questa partita'], ['10:31:12', 'ORDINE PIAZZATO', 'sky', 'Real Betis – Getafe · BASE · LAY Pareggio 4,00 € @3,30 ' + chip('PAPER')], ['10:22:40', 'BLOCCATO DAL RISCHIO', 'red', 'Inter – Torino · cap per evento raggiunto (3 trade)'], ['09:40:02', 'POSIZIONE REGOLATA', '', 'Feyenoord – AZ · PERSO −2,20 €']]), { icon: 'report', count: 48, id: 'safe-activity-card', note: 'perché il bot è entrato o NON è entrato: salti, blocchi di rischio, uscite, riconciliazioni, feed' }) +
        '<div class="row">' + '<span class="chip" style="color:var(--lay)">BASE</span><span class="chip" style="color:#c4b5fd">R.E. CASA</span><span class="chip" style="color:var(--back)">PUNTA</span><span class="chip gold">TENNIS</span></div>';
      return h;
    }
  });

  /* ============================== MIKE ============================== */
  var PHASE = { WATCH: ['IN ATTESA', 'teal', 'cerca l’ingresso Under 3.5: aspetta quota, liquidità e spread nei limiti'], PRE_OPEN: ['UNDER 3.5 APERTO', 'teal', 'posizione abbinata prima del fischio: aspetta il green-up a +2 tick'], LIVE_COVERED: ['IN GIOCO · COPERTO', 'violet', 'copertura sulla linea 4.5 abbinata: la posizione è protetta fino a 3 gol'], LIVE_UNCOVERED: ['IN GIOCO · SCOPERTO', 'sky', 'nessuna copertura ancora: attende quota migliore sulla linea 4.5'], ERROR: ['ERRORE', 'red', 'il bot si è fermato su questa partita: serve «Riprendi» per rimetterla in gioco'] };
  var MIKE_EV = [
    { id: 'mk1', nome: 'Bologna v Udinese', comp: 'Serie A', grp: 'pre', score: '–', meta: 'KO 10:52 · fra <b data-testid="mike-countdown">14:02</b>', ph: 'PRE_OPEN', feed: 2, live: false, p4m: '7,9 %', p4k: '7,1 %', px: 'P(Over 4.5) modello', pxv: '6,2 %', u35: [1.29, 1.3], o45: [11, 11.5], u45: [1.1, 1.11], pos: [['BACK', 'Under 3.5', 10, '1,30', '1,29 / 1,30', '▼ 1 tick', 0.08]], cash: 0.08, cicli: '1 di 10' },
    { id: 'mk2', nome: 'Inter v Torino', comp: 'Serie A', grp: 'live', score: '1–0', meta: '<b>58′</b> · 1 gol · 1T 1–0', ph: 'LIVE_COVERED', feed: 1, live: true, p4m: '6,1 %', p4k: '5,4 %', px: 'Hazard gol 3′', pxv: 'atl 4,8 % · mod 4,1 %', u35: [1.22, 1.23], o45: [15, 16], u45: [1.07, 1.08], pos: [['BACK', 'Under 3.5', 8, '1,30', '1,22 / 1,23', '▼ 4 tick', 0.46], ['LAY', 'Under 4.5', 7.8, '1,08', '1,07 / 1,08', '= 0 tick', -0.06]], cash: 0.4, cicli: '1 di 10', proposta: true },
    { id: 'mk3', nome: 'Getafe v Celta', comp: 'La Liga', grp: 'fix', score: '–', meta: 'KO 12:00', ph: 'ERROR', feed: null, live: false, p4m: '—', p4k: null, pos: [], cash: null, cicli: '0 di 10' }
  ];
  function mikeCard(e) {
    var ph = PHASE[e.ph], bordo = { pre: 'var(--teal)', live: '#a78bfa', fix: 'var(--red)' }[e.grp];
    var hist = [2, 8, 17, 22, 21, 15, 8, 5, 2];
    var h = '<article class="panel flat" data-testid="mike-match-card" data-event-id="' + e.id + '" data-state="' + e.ph + '" style="border-left:4px solid ' + bordo + ';padding:12px;display:flex;flex-direction:column;gap:9px">';
    h += '<div class="row" style="align-items:flex-start;min-height:54px"><div data-testid="mike-score" style="min-width:52px;text-align:center;padding:6px;border-radius:8px;background:hsl(var(--muted));font:800 18px var(--f-display)">' + e.score + '</div><div style="min-width:0;flex:1"><b>' + e.nome + '</b><div class="foot">' + e.comp + ' · ' + e.meta + '</div></div>' +
      '<div class="row" style="gap:4px"><span class="chip" data-testid="mike-phase" style="color:' + ({ teal: 'var(--teal)', violet: '#c4b5fd', sky: 'var(--back)', red: '#fca5a5' }[ph[1]]) + '">' + ph[0] + '</span>' + (e.feed != null ? chip('feed ' + e.feed + ' s', 'paper') : chip('FEED: NESSUN DATO')) + S.media(true) + '</div></div>';
    h += '<div class="foot" data-testid="mike-phase-what">' + ph[2] + '</div>';
    h += '<div class="row" data-testid="mike-alerts">' + (e.live ? chip('SOLDI VERI', 'live') : '') + (e.ph === 'ERROR' ? chip('NESSUN RIENTRO', 'amber') : '') + '</div>';
    if (e.p4k) h += '<div class="grid g4" data-testid="mike-model" style="gap:6px">' + tile('P(4 gol) modello', e.p4k, 'da quote pre-partita') + tile('P(4 gol) mercato', e.p4m) + tile(e.px, e.pxv) + tile('λ casa / trasferta', '1,62 / 0,71') + '</div>' +
      '<div data-testid="mike-goals-histogram"><div class="lbl">P(totale gol) 0…8 · modello</div><div class="row" style="align-items:flex-end;gap:4px;height:46px;flex-wrap:nowrap">' + hist.map(function (v, k) { return '<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:2px"><span style="width:100%;height:' + v * 1.6 + 'px;border-radius:3px;background:' + (k === 4 ? 'var(--lay)' : 'var(--teal)') + ';opacity:.8" data-testid="mike-goals-bar-' + k + '"></span><span class="foot" style="font-size:9.5px">' + k + '</span></div>'; }).join('') + '</div></div>';
    else h += '<div class="strip warn" data-testid="mike-model-missing">Nessun modello per questa lega: il bot decide con le quote e le soglie fisse.</div>';
    var q = function (lab, v, tid) { return '<div class="kpi" style="padding:6px 8px" data-testid="' + tid + '"><div class="k" style="font-size:9.5px">' + lab + '</div><div class="row" style="gap:4px;margin-top:4px"><span class="o b" style="height:24px;min-width:42px;cursor:default">' + (v ? S.odds(v[0]) : '—') + '</span><span class="o l" style="height:24px;min-width:42px;cursor:default">' + (v ? S.odds(v[1]) : '—') + '</span></div><div class="foot" style="font-size:10px">ritardo scommessa ' + (e.grp === 'live' ? '5' : '0') + ' s</div></div>'; };
    h += '<div class="grid g3" data-testid="mike-quotes" style="gap:6px">' + q('Under 3.5 back / lay', e.u35, 'mike-quote-ou35') + q('Over 4.5 · chiusura della copertura', e.o45, 'mike-quote-ou45') + q('Under 4.5 · copertura (banca) e re-ingresso', e.u45, 'mike-quote-ou45-under') + '</div>';
    h += '<div class="foot" data-testid="mike-meta-line">Volume mercato <b>84.210 €</b> · ingresso <b>@1,30</b> · al fischio <b>@1,32</b> <span class="pos">−1 tick</span> · ciclo <b>' + e.cicli + '</b> · <b>0</b> cicli chiusi · regolato <b>—</b></div>';
    h += '<div data-testid="mike-positions" class="tbl-w"><table class="t" style="font-size:11.5px"><thead><tr><th>Posizione</th><th>Ingresso</th><th>Quota ora</th><th>Δ ingresso</th><th class="r" title="P&L che resta in tasca chiudendo questa selezione adesso, già NETTO della commissione: lo calcola il servizio">Se chiudo ora (netto)</th></tr></thead><tbody>' +
      (e.pos.length ? e.pos.map(function (p) { return '<tr data-testid="mike-pos-row"><td>' + chip(p[0], p[0] === 'BACK' ? 'sky' : 'rose') + ' <b>' + p[1] + '</b> · ' + M(p[2]) + '</td><td class="mono">' + p[3] + '</td><td class="mono">' + p[4] + '</td><td class="' + (/▼/.test(p[5]) ? 'pos' : '') + '">' + p[5] + '</td><td class="r ' + S.tone(p[6]) + '" data-testid="mike-pos-locked">' + M(p[6], { signed: true }) + '</td></tr>'; }).join('') : '<tr><td colspan="5" class="mut">nessuna posizione aperta —</td></tr>') + '</tbody></table></div>';
    h += '<div class="row foot" data-testid="mike-orders"><span class="lbl">Ordini sul book</span>' + (e.grp === 'pre' ? chip('LAY', 'rose') + ' green-up (Under 3.5) · chiesto 10,08 € · abbinato 0,00 € · ' + chip('SUL BOOK') + ' · 2 tick sopra il best' : '—') + '</div>';
    h += '<div data-testid="mike-pnl-by-total" class="row" style="gap:4px">' + [0.6, 0.6, 0.6, 0.6, -2.4, 7.8, 7.8, 7.8, 7.8].map(function (v, k) { return '<span class="chip ' + (v >= 0 ? 'paper' : 'red') + '" data-testid="pnl-total-' + k + '" style="' + (k === 4 ? 'border-color:var(--lay);' : '') + (e.grp === 'live' && k === 1 ? 'box-shadow:0 0 0 1.5px hsl(var(--foreground));' : '') + '">' + k + (k === 8 ? '+' : '') + ': ' + M(v, { signed: true }) + '</span>'; }).join('') + '</div>' +
      '<div class="row foot"><span data-testid="mike-liability">Liability aperta <b class="ora">' + (e.pos.length ? '2,40 €' : '—') + '</b></span><span data-testid="mike-locked">P&L bloccato <b>—</b></span></div>';
    h += '<div class="row" style="min-height:64px;align-items:flex-start;border-top:1px solid hsl(var(--border));padding-top:8px"><div style="flex:1;min-width:200px"><div class="lbl">Se chiudo tutto ora (netto)</div><div data-testid="mike-cashout-value"><b class="' + S.tone(e.cash) + '" style="font:800 20px var(--f-display)">' + (e.cash == null ? 'nessuna posizione' : M(e.cash, { signed: true })) + '</b>' + (e.cash != null ? ' <span class="foot">(' + (e.cash * 12.5).toFixed(1).replace('.', ',') + ' % · chiude da solo a 5 %)</span>' : '') + '</div>' + (e.cash != null ? '<div class="bar" style="margin:4px 0" aria-label="Avanzamento verso la soglia di cash out"><i style="width:' + Math.min(100, e.cash * 250) + '%"></i></div><div class="foot" data-testid="mike-cashout-eseguibile">eseguibile ai prezzi correnti · commissione 5 % già tolta</div>' : '') + '</div>' +
      '<div class="row" style="gap:6px">' + (e.pos.length ? '<button class="btn sm gold" data-act="mike-cashout" data-v="' + e.nome + '" data-testid="mike-cashout-btn">Cash out ' + M(e.cash, { signed: true }) + '</button>' : '') + (e.grp === 'pre' ? '<button class="btn sm ghost amb" data-act="toast" data-t="Annulla ordini" data-d="annulla gli ordini ancora sul book (le posizioni abbinate restano)" data-testid="mike-cancel-btn">Annulla ordini</button>' : '') + (e.pos.length ? '<button class="btn sm ghost" style="color:var(--lay)" data-act="mike-flatten" data-v="' + e.nome + '" data-testid="mike-flatten-btn">Chiudi a mercato</button>' : '') + (!e.pos.length && e.ph !== 'ERROR' ? '<button class="btn sm ghost" data-testid="mike-skip-btn">Salta</button>' : '') + (e.ph === 'ERROR' ? '<button class="btn sm teal" data-act="toast" data-t="Partita ripresa" data-testid="mike-resume-btn">Riprendi</button>' : '') + '</div></div>';
    h += '</article>';
    if (e.proposta) h += S.CR.schedaMike().replace('data-testid="cr-mike"', 'data-testid="mike-proposta-' + e.id + '"');
    return h;
  }
  S.on('mike-cashout', function (t) {
    var live = D.botMode.mike.mode === 'LIVE';
    S.modal({ danger: live, title: 'Cash out', body: '<p style="margin-top:0">Chiusura di <b>' + t.dataset.v + '</b>: il servizio annulla gli ordini sul book e chiude le posizioni nette di Under 3.5 e della copertura sulla linea 4.5. La chiusura è intera: Mike non accetta cash out parziali.</p><div class="kpi"><div class="k">P&L bloccato chiudendo ora (netto commissione, dal servizio)</div><div class="v pos" data-testid="mike-cashout-dialog-net">+0,40 €</div><div class="s">5,0 % della base 8,00 € · soglia automatica 5 %</div></div>' + (live ? '<div class="strip live" style="margin-top:8px">MODALITÀ LIVE: soldi veri.</div>' : ''), ok: live ? 'Chiudi tutto (+0,40 €)' : 'Chiudi tutto (+0,40 €)', onOk: function () { if (live) S.toast('Confermi? soldi veri', 'Nel prodotto il secondo clic conferma (decade in 10 s).'); } });
  });
  S.on('mike-flatten', function (t) {
    var live = D.botMode.mike.mode === 'LIVE';
    S.modal({ danger: true, title: 'Chiudi a mercato', body: '<p style="margin-top:0">Chiusura IMMEDIATA di <b>' + t.dataset.v + '</b> ai prezzi disponibili adesso: il servizio annulla gli ordini sul book e chiude tutte le posizioni <b>senza guardare la soglia di profitto</b>. Se il mercato è contro, la perdita diventa definitiva.</p><div class="kpi"><div class="k">P&L bloccato chiudendo ora (netto commissione, dal servizio)</div><div class="v pos" data-testid="mike-flatten-net">+0,40 €</div></div>' + (live ? '<div class="strip live" style="margin-top:8px">MODALITÀ LIVE: soldi veri.</div>' : ''), ok: 'Chiudi tutto a mercato' });
  });
  S.reg({
    id: 'mike', title: 'Mike', group: 'Calcio · bot',
    render: function () {
      var mode = D.botMode.mike.mode, tab = S.tab('mike', 'partite');
      var h = C.botHeader({ key: 'mike', name: 'MIKE', symbol: '🎯', accent: 'var(--teal)', statusPrefix: 'BOT', sub: 'Under 3.5 / Over 4.5 · green-up e cash-out · paper-first', params: true, extraChip: chip('canale locale', 'paper'), health: { beat: 'servizio Mike vivo (1 s)', src: '⚡ STREAM 152' }, liveText: 'il bot piazza ordini con <b>soldi veri</b>.', paperText: 'simulazione fedele: fill solo al prezzo ancora disponibile, betDelay in-play, protezioni identiche al live.' });
      h += C.dayBar({ realized: 8.12, ops: 2, v: 1, p: 0, vive: 2, locked: null, total: 64.3, note: 'partite con almeno una posizione piazzata oggi · operazioni = cicli aperti oggi · V/P = cicli già chiusi, la loro somma è il realizzato' });
      h += '<div class="grid g4" data-testid="kpi-row">' + tile('Partite seguite ora', '<span class="tealc">3</span>', '1 prima del fischio · 1 in gioco · 2 con posizione aperta', '', 'mike-kpi-matches') + tile('Posizioni aperte', '3', 'cicli con capitale ancora esposto') + tile('P&L oggi', '<span class="pos">' + M(8.12, { signed: true }) + '</span>', '1 ottobre · Europe/Rome · stop a −50,00 €<br><span data-testid="mike-pnl-today-fonte">P&L del conto Betfair (tutte le operazioni: Mike + utente) ' + mk('CONTO') + '</span>', '', 'mike-pnl-today-sub') + tile('P&L totale', '<span class="pos">+64,30 €</span>') +
        tile('Liability aperta', '<span class="ora">2,40 €</span>', 'perdita peggiore sulle posizioni aperte, netta dal servizio', '', 'mike-liability-sub') + tile('P&L bloccato', '—', 'nessuna partita ha ancora un risultato bloccato', '', 'mike-kpi-locked') + tile('Ultimo ciclo', '<span class="mono">10:41:23</span>', 'feed aggiornato 1 s fa', '', 'mike-kpi-cycle') + '</div>';
      h += S.tabbar('mike', [['partite', '⚽ Partite', 3], ['operazioni', '📋 Operazioni', 2], ['pre', '⏱ Risultati Pre-Match', 1], ['live', '🔴 Risultati Live', 1], ['attivita', '🧾 Attività'], ['storico', '📅 Storico']], 'partite');
      if (tab === 'partite') {
        var hid = S.ui.mikeHide || {};
        h += '<div class="row" data-testid="mike-filtro-sezioni"><span class="lbl">Mostra</span><button class="chip teal" data-act="mike-sec" data-v="pre" style="cursor:pointer;' + (hid.pre ? 'opacity:.4;text-decoration:line-through' : '') + '">⏱ Pre-match 1</button><button class="chip" data-act="mike-sec" data-v="live" style="cursor:pointer;color:#c4b5fd;' + (hid.live ? 'opacity:.4;text-decoration:line-through' : '') + '">🔴 Live 1</button></div>';
        if (!hid.pre) h += '<section data-testid="mike-section-pre" class="col"><h3 class="tealc" style="font-size:13px;letter-spacing:.06em">⏱ PRE-MATCH (1) <span class="foot" style="letter-spacing:0">· per calcio d’inizio</span></h3><div class="grid g2">' + mikeCard(MIKE_EV[0]) + '</div></section>';
        if (!hid.live) h += '<section data-testid="mike-section-live" class="col"><h3 style="font-size:13px;letter-spacing:.06em;color:#c4b5fd">🔴 LIVE (1) <span class="foot" style="letter-spacing:0">· in gioco</span></h3><div class="grid g2"><div class="col">' + mikeCard(MIKE_EV[1]) + '</div></div></section>';
        h += '<section data-testid="mike-section-fix" class="col"><h3 class="neg" style="font-size:13px;letter-spacing:.06em">⚠️ DA SISTEMARE (1) <span class="foot" style="letter-spacing:0">· partite in errore o saltate: serve una mano</span></h3><div class="grid g2">' + mikeCard(MIKE_EV[2]) + '</div></section>';
      } else if (tab === 'operazioni' || tab === 'pre' || tab === 'live') {
        var title = { operazioni: 'Operazioni della giornata', pre: 'Risultati Pre-Match', live: 'Risultati Live' }[tab];
        var nota = { operazioni: 'Una riga per PARTITA col netto delle sue operazioni, commissione già tolta. P&L: P&L del conto Betfair. Clicca per aprire i cicli e gli ordini. giornata operativa giovedì 1 ottobre 2026 · 2 cicli in totale.', pre: 'Cicli aperti e chiusi PRIMA del fischio d’inizio: ingresso sull’Under 3.5 e uscita a +2 tick. Una partita che ha operato anche in gioco compare pure in «Risultati Live», con gli euro dell’altra fase.', live: 'Tutto quello che è successo a partita iniziata: la posizione portata in gioco, l’uscita al fischio, la seconda puntata dopo un gol precoce, la copertura sulla linea 4.5 e le chiusure.' }[tab];
        h += S.panel(title, C.eventPnl({ testId: 'mike-operazioni', mode: mode, unit: 'cicli', rows: [{ match: 'Napoli v Lazio (ieri sera, regolata oggi)', n: 1, inv: 10, liab: 0, closed: true, pnl: 8.12, q: 1.42, sel: 'Under 3.5 Goals', ora: '20:45', ora2: '22:41', live: true }, { match: 'Inter v Torino', n: 1, inv: 8, liab: 2.4, closed: false, pnl: 0.4, q: 1.3, sel: 'Under 3.5 Goals', ora: '09:31', live: true }] }) + '<p class="foot">' + nota + '</p>', { icon: 'grid', count: 2, id: 'mike-operazioni' });
        if (tab === 'operazioni') h += C.equityCard([{ date: new Date(2026, 9, 1, 8), pnl: 8.12 }], 'giornata operativa 1 ottobre');
      } else if (tab === 'attivita') {
        h += S.panel('Attività del servizio', activity([['10:41:23', 'COPERTURA LINEA 4.5', 'violet', 'Inter v Torino · banca Under 4.5 7,80 € @1,08 abbinata'], ['10:38:02', 'USCITA PROPOSTA: DECIDI TU', 'red', 'Inter v Torino · cash out della posizione (può chiudere IN PERDITA)'], ['10:31:55', 'CICLO PRE', 'teal', 'Bologna v Udinese · ingresso Under 3.5 10,00 € @1,30'], ['10:12:10', 'ERRORE', 'red', 'Getafe v Celta · linea Over 4.5 assente nel feed'], ['09:40:02', 'ARMATA', 'sky', 'Inter v Torino · modalità LIVE fissata all’armo']]), { icon: 'bolt', count: 112, id: 'mike-activity', note: 'giornata operativa · ora di Roma' });
      } else h += C.tradingHistory('mike', 'mike-st');
      return h + '<p class="foot" data-testid="page-footer">Fonte dati: feed unico dello scanner (linee Over/Under 3.5 e 4.5 pre-match e live). Nessuna chiamata Betfair da questa schermata. Paper-first: il live si attiva solo dal toggle con conferma.</p>';
    }
  });
  S.on('mike-sec', function (t) { var h = S.ui.mikeHide = S.ui.mikeHide || {}; var other = t.dataset.v === 'pre' ? 'live' : 'pre'; if (!h[t.dataset.v] && h[other]) { S.toast('È l’ultima sezione visibile', 'Non si può nascondere anche questa.'); return; } h[t.dataset.v] = !h[t.dataset.v]; S.rerender(); });

  /* ---------- cash out di riga (CashOutButton, Omega e Safe) ---------- */
  S.on('cashout-dlg', function (t) {
    var bot = D.botMode[t.dataset.v], live = bot && bot.mode === 'LIVE';
    S.modal({ danger: live, title: 'Cash out', body: '<p style="margin-top:0" class="foot">Chiusura PUNTANDO (back) a 13,00 · green pieno 0,92 € di stake.</p><div class="grid g2">' + tile('Se vince', '<span class="pos">+0,08 €</span>') + tile('Se perde', '<span class="pos">+0,08 €</span>') + '</div><div class="row" style="margin:10px 0">' + ['25 %', '50 %', '75 %', '100 %'].map(function (x) { return '<button class="btn sm">' + x + '</button>'; }).join('') + '</div><label class="field" for="co-imp">Importo da chiudere (€, stake dell’ordine)<input id="co-imp" value="0,92" aria-label="Importo cash out"></label><div class="kpi" style="margin-top:8px" data-testid="cashout-locked"><div class="k">P&L bloccato (green pieno)</div><div class="v pos">+0,08 €</div><div class="s">al netto della commissione</div></div><p class="foot" data-testid="cashout-min-note">Sotto 2 € Betfair usa il metodo 1000→cancella→sposta: l’ordine viene immesso a quota 1000, cancellato e riposizionato per aggirare il minimo.</p>' + (live ? '<div class="strip live">Modalità LIVE: soldi veri.</div>' : ''), ok: 'Chiudi 0,92 €' });
  });
})();
