/* s_live.js - Segui live (lista + terminal calcio con i 7 strumenti, scalper incluso),
   Multi-ladder, Ladder pop-out, Market watch, Live P&L. */
(function () {
  'use strict';
  var S = window.S, D = window.D, M = S.money, chip = S.chip, C = S.C;
  var tile = function (k, v, s) { return '<div class="kpi" style="padding:7px 9px"><div class="k" style="font-size:9px">' + k + '</div><div class="v" style="font-size:15px">' + v + '</div>' + (s ? '<div class="s">' + s + '</div>' : '') + '</div>'; };
  var FOLLOWS = [
    { id: '34812001', lega: 'Serie A', casa: 'Inter', osp: 'Torino', score: '1 - 0', min: 58, stato: 'In streaming', orig: 'manuale', fonte: 'runner' },
    { id: '34812044', lega: 'La Liga', casa: 'Real Betis', osp: 'Getafe', score: '0 - 0', min: 31, stato: 'In streaming', orig: 'auto', fonte: 'runner' },
    { id: '34812102', lega: 'Serie A', casa: 'Bologna', osp: 'Udinese', score: null, min: null, stato: 'In attesa', orig: 'auto', fonte: '—' }
  ];
  function matchCard(f, sel) {
    return '<article class="panel" data-act="sl-open" data-v="' + f.id + '" style="padding:12px 14px;cursor:pointer;' + (sel ? 'box-shadow:0 0 0 1px hsl(var(--primary)/.6)' : '') + '"><div class="row"><span class="lbl">' + f.lega + '</span><span style="margin-left:auto" class="row">' + chip(f.orig, f.orig === 'auto' ? 'sky' : '') + chip(f.stato === 'In streaming' ? '● In streaming' : f.stato, f.stato === 'In streaming' ? 'paper' : '') + '</span></div>' +
      '<div class="row" style="margin:8px 0;justify-content:center;gap:12px"><b class="pos" style="font-size:15px">' + f.casa + '</b><b style="font:800 22px var(--f-display)">' + (f.score || 'vs') + '</b><b class="amb" style="font-size:15px">' + f.osp + '</b>' + (f.min ? chip(f.min + "'", 'inplay') : '') + '</div><div class="row foot" style="justify-content:space-between"><span>' + (f.min ? 'In gioco' : 'Pre-match') + '</span><span>fonte: ' + f.fonte + '</span></div></article>';
  }
  function habitat() {
    return S.panel('Partite adatte allo scalper', '<div class="col" style="gap:6px">' + [['Brentford v Fulham', '11:22', '402k', '1.240', 1, '0,42', 78], ['Atalanta v Genoa', '12:22', '211k', '880', 1, '0,38', 71]].map(function (r) { return '<div class="row" style="padding:7px 10px;border-radius:8px;background:rgba(16,185,129,.07);border:1px solid rgba(16,185,129,.3);font-size:12px"><b>' + r[0] + '</b><span class="foot">KO ' + r[1] + ' · €' + r[2] + ' scambiati · best €' + r[3] + ' · spread ' + r[4] + 'tk · osc ' + r[5] + '</span><span class="chip paper" style="margin-left:auto">GO ' + r[6] + '</span></div>'; }).join('') + '<div class="foot">Scartate: Lens v Nantes (book sottile) · Feyenoord v AZ (spread largo)</div></div>', { icon: 'target', right: '<span class="foot">scan 10:40:02</span>' });
  }

  /* ---------- strumenti del terminal (colonna destra) ---------- */
  function modeBadge(m) { return m === 'LIVE' ? '<span class="chip live" style="background:#dc2626;color:#fff">🔴 LIVE REALE</span>' : m === 'PAPER' ? '<span class="chip paper">PAPER</span>' : '<span class="chip">OFF</span>'; }
  function tool(name, mode) {
    var head = function (t, extra) { return '<div class="row"><h3 style="font-size:15px">' + t + '</h3>' + modeBadge(mode) + '<span style="margin-left:auto" class="row">' + (extra || '<button class="btn sm" title="Blocca SOLO gli invii di questo pannello (il Kill-switch GLOBALE del runner è nei Controlli)">🛡 Blocco pannello OFF</button>') + '<button class="iconbtn" style="width:26px;height:26px">↻</button></span></div>'; };
    var live = mode === 'LIVE';
    var conf = live ? '<label class="row neg" style="font-size:12px;color:#fca5a5"><input type="checkbox" id="conf-' + name + '"> Confermo ordine REALE (soldi veri)</label>' : '<p class="foot" style="margin:0">Modalità PAPER: nessun denaro reale.</p>';
    var f = function (id, l, v, sel) { return '<label class="field" for="' + id + '">' + l + (sel ? '<select class="inp" id="' + id + '">' + sel.map(function (o) { return '<option>' + o + '</option>'; }).join('') + '</select>' : '<input id="' + id + '" value="' + v + '">') + '</label>'; };
    if (name === 'Trading') return '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:12px">' + head('Live Trading') + '<div class="foot mono">Inter vs Torino · Match Odds · mercato 1.234567812</div><div class="grid g2" style="gap:8px">' + f('lt1', 'Selezione', '', ['Inter (#47999)', 'Torino (#58805)', 'The Draw (#58805)']) + f('lt2', 'Handicap', '0') + f('lt3', 'Lato', '', ['Back (punta)', 'Lay (banca)']) + f('lt4', 'Prezzo (quota)', '1,39') + f('lt5', 'Size (€)', '2,00') + f('lt6', 'Importo come', '', ['Size', 'Liability (solo lay)']) + f('lt7', 'Persistenza', '', ['LAPSE (decade in-play)', 'PERSIST (resta)', 'MARKET_ON_CLOSE']) + f('lt8', 'Cap max stake (€)', '10') + '</div><div class="row" style="font-size:12px"><label class="row"><input type="checkbox" id="lt-fok"> Fill-or-Kill</label><label class="row" title="Place-and-trim: piazza al minimo e riduce alla size target (sotto-minimo)"><input type="checkbox" id="lt-pt"> Place-and-trim (sotto-minimo)</label></div>' + conf + '<div class="row"><button class="btn" style="background:#0ea5e9;color:#001018;border-color:transparent" data-act="toast" data-t="Ordine inviato">Piazza Back</button><button class="btn" style="background:#f43f5e;color:#fff;border-color:transparent" data-act="toast" data-t="Ordine inviato">Piazza Lay</button></div>' +
      '<div class="lbl">Ordini (1)</div><table class="t"><thead><tr><th>Selezione</th><th>Lato</th><th class="r">Prezzo</th><th class="r">Size</th><th>Abbinato</th><th>Stato</th><th></th></tr></thead><tbody><tr><td>Inter</td><td style="color:var(--back)">Back</td><td class="r">1,36</td><td class="r">5,00</td><td class="pos">0,00</td><td>' + chip('Sul book', 'sky') + '</td><td><button class="btn sm ghost" title="Replace (nuovo prezzo)">✎</button><button class="btn sm ghost" title="Cancel">✕</button></td></tr></tbody></table>' +
      '<div class="row"><span class="lbl">Posizioni / P&L (1)</span><span class="chip" data-testid="ltp-fonte-posizioni">canale</span><span class="chip paper">● LIVE</span></div><table class="t"><thead><tr><th>Selezione</th><th class="r">Se vince</th><th class="r">Se perde</th><th class="r">Esposizione</th><th class="r">Netto</th></tr></thead><tbody><tr><td>Inter</td><td class="r pos">+1,95</td><td class="r neg">−5,00</td><td class="r ora">5,00</td><td class="r">5,00</td></tr><tr style="font-weight:700"><td>Totale mercato</td><td colspan="4" class="r">P&L mercato −5,00 / +1,95 worst / best</td></tr></tbody></table></section>';
    if (name === 'Dutching') return '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:12px">' + head('Dutching') + '<div class="foot">Inter vs Torino · Punta più esiti (dutch) · mercato 1.234567812</div><div class="grid g2" style="gap:8px">' + f('du1', 'Lato', '', ['Back (dutch)', 'Lay (bookmaking)']) + f('du2', 'Modalità', '', ['Equal (profitto pari)', 'Variable (peso)', 'Target (profitto obiettivo — solo Back)']) + f('du3', 'Puntata totale (€)', '10') + f('du4', 'Persistenza', '', ['LAPSE (decade in-play)', 'PERSIST (resta)', 'MARKET_ON_CLOSE']) + f('du5', 'Prezzo', '', ['Come impostato', 'Best price live', 'Un tick davanti', 'Nominato']) + '</div><div class="lbl">Selezioni (2 attive · min 2)</div><table class="t"><thead><tr><th></th><th>Selezione</th><th class="r">Quota</th><th class="r">Stake</th><th class="r">Se vince</th></tr></thead><tbody><tr><td><input type="checkbox" checked></td><td>Inter</td><td class="r">1,38</td><td class="r">8,02</td><td class="r pos">+1,07</td></tr><tr><td><input type="checkbox" checked></td><td>The Draw</td><td class="r">5,60</td><td class="r">1,98</td><td class="r pos">+1,09</td></tr><tr><td><input type="checkbox"></td><td>Torino</td><td class="r">11,50</td><td class="r">—</td><td class="r">—</td></tr></tbody></table><div class="row"><div><div class="lbl">Book % (overround)</div><b class="pos" style="font:800 22px var(--f-display)">90,3 %</b><div class="foot">favorevole (&lt; 100)</div></div><div class="foot" style="margin-left:auto;text-align:right">Puntata totale €10 · stake sommati €10<br>Profitto se vince €1,07</div></div>' + conf + '<button class="btn" style="background:#0ea5e9;color:#001018;border-color:transparent;justify-content:center" data-act="toast" data-t="Dutching inviato">Piazza Dutch (2)</button></section>';
    if (name === 'Risk') return '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:12px">' + head('Automazione Rischio', '<button class="btn sm" title="Blocca SOLO l’arming da questo pannello">🛡 Blocco pannello OFF</button>') + '<div class="foot">offset · stop-loss · take-profit · trailing · bracket (OCO) — mercato 1.234567812</div><div class="strip warn">Stop/offset <b>SOFTWARE-SIDE</b>: se il runner si ferma <b>NON sono attivi</b>. Nessuna protezione lato Betfair — servono runner e connessione vivi.</div><div class="grid g2" style="gap:8px">' + f('rr1', 'Selezione', '', ['Inter (#47999)']) + f('rr2', 'Tipo regola', '', ['Offset (presa profitto)', 'Stop-loss', 'Take-profit', 'Trailing-stop', 'Bracket (Offset + Stop OCO)']) + f('rr3', 'Lato ingresso', '', ['Back (punta)', 'Lay (banca)']) + f('rr4', 'Prezzo ingresso *', '1,39') + f('rr5', 'Unità parametro', '', ['Tick', 'Percentuale (%)', 'Importo P&L (€)']) + f('rr6', 'Tick', '3') + f('rr7', 'Attivazione (timing)', '', ['Immediata (arma subito)', 'Al fill (attende l’ingresso)']) + f('rr8', 'Al calcio d’inizio (in-play)', '', ['Mantieni', 'Annulla', 'Ricalcola (rebaseline)']) + '</div><div class="foot">Anteprima Back target offset a 1,36 (3 tick di profitto) (stima; il server è autoritativo)</div>' + conf.replace('ordine REALE', 'regola REALE') + '<button class="btn" style="background:#0ea5e9;color:#001018;border-color:transparent;justify-content:center" data-act="toast" data-t="Regola armata">Arma Offset (presa profitto)</button><div class="lbl">Regole attive (1)</div><table class="t"><thead><tr><th>Selezione</th><th>Tipo</th><th>Lato</th><th class="r">Ingresso</th><th>Parametri</th><th>Stato</th><th></th></tr></thead><tbody><tr><td>Inter</td><td>Offset ' + chip(mode, mode === 'LIVE' ? 'live' : 'paper') + '</td><td style="color:var(--back)">Back</td><td class="r">1,39</td><td>3 tick · green</td><td>' + chip('Armata', 'sky') + '</td><td><button class="btn sm danger">✕ Disarma</button></td></tr></tbody></table></section>';
    if (name === 'X-Hedge') return '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:12px">' + head('X-Hedge (cross-market)', ' ') + '<div class="foot">Copertura sull’intero evento 34812001 · 3 posizioni · agg. 10:41:20 <span data-testid="xhedge-fonte">· fonte canale</span></div><div class="grid g3" style="gap:6px">' + tile('Peggiore', '<span class="neg">−4,20 €</span>', 'risultato 2-2') + tile('Medio', '<span class="pos">+0,61 €</span>', 'su 16 risultati') + tile('Migliore', '<span class="pos">+1,95 €</span>', 'risultato 1-0') + '</div><div class="lbl">P&L per risultato esatto (Casa ↓ / Ospite →)</div><div class="tbl-w"><table class="t" style="font-size:11px;text-align:center"><tr><th>C↓ / O→</th><th>0</th><th>1</th><th>2</th><th>3</th></tr>' + [[1.2, 0.4, -1.1, -2.8], [1.95, 1.1, -0.4, -2.1], [1.5, 0.9, -4.2, -3.0], [1.4, 0.8, -1.6, -3.5]].map(function (r, i) { return '<tr><th>' + i + '</th>' + r.map(function (v) { var a = Math.min(.4, .1 + Math.abs(v) / 12); return '<td style="background:' + (v >= 0 ? 'rgba(16,185,129,' + a + ')' : 'rgba(244,63,94,' + a + ')') + '">' + (v > 0 ? '+' : '−') + Math.abs(v).toFixed(2).replace('.', ',') + '</td>'; }).join('') + '</tr>'; }).join('') + '</table></div><div class="strip warn" style="flex-direction:column;align-items:flex-start"><b><span style="color:var(--back)">BACK</span> Correct Score 2-2 €0,30 @ 15,00</b><span class="foot">Peggiore −4,20 € → −1,00 € · migliore +1,65 €</span><button class="btn sm gold" data-act="toast" data-t="Copertura inviata" data-d="FoK software 10s.">Copri (1-click)</button></div><div class="strip info" style="flex-direction:column;align-items:flex-start;border-color:rgba(168,85,247,.45)"><b style="color:#d8b4fe">Auto-hedge (mantieni il worst-case scoreline)</b><div class="row"><label class="field" for="ah1">Perdita worst-case max<input id="ah1" placeholder="es. 20"></label><label class="field" for="ah2">Max stake/copertura<input id="ah2" placeholder="nessun cap"></label></div><button class="btn sm" style="color:#d8b4fe;border-color:rgba(168,85,247,.5)">Arma auto-hedge</button><span class="foot">copre da solo via coda ordini · mai su matrice incompleta</span></div></section>';
    if (name === 'Scalper') {
      var on = S.ui.slScalper, form = S.ui.slScalperForm;
      var h = '<section class="panel" style="padding:14px;display:flex;flex-direction:column;gap:12px"><div class="row"><span class="pos">' + S.icon('bot') + '</span><b>Scalper Bot</b><span class="foot">pre-match · stop automatico al KO</span><span style="margin-left:auto" class="row">' + (on ? chip('OPERATIVO', 'paper') + chip('servizio ✓', 'paper') : '') + '</span></div>';
      if (on) return h + '<div class="row foot">' + chip('Tradizionale') + ' stake €25</div><div class="grid g3" style="gap:6px">' + [['Ordini (sim)', '14'], ['Cicli', '6'], ['Catture', '4'], ['Scratch', '1'], ['Stop', '1'], ['P&L bloccato (lordo)', '<span class="pos">+0,86</span>']].map(function (x) { return tile(x[0], x[1]); }).join('') + '</div><div class="grid g4" style="gap:6px">' + tile('Tick pre-match', '✓') + tile('Tick intervallo', '—') + tile('P&L pre-match', '+0,61') + tile('P&L intervallo', '—') + '</div><div class="code foot" style="max-height:90px;overflow:auto">10:39:02 cycle {"side":"BACK","ticks":1}<br>10:38:40 scratch {"reason":"flow"}</div><button class="btn danger" style="justify-content:center" data-act="sl-scalper-stop">Ferma lo scalper (chiude flat)</button></section>';
      if (!form) return h + '<button class="btn pri" style="justify-content:center;height:36px" data-act="sl-scalper-form">▶ Attiva Scalper Bot</button><p class="foot" style="margin:0">Ultima sessione: <b>COMPLETATO (KO)</b> — cicli 5, catture 3, P&L bloccato (lordo) €0,71, settlato (lordo) €0,71</p></section>';
      return h + '<div class="grid g3" style="gap:6px">' + [['Tradizionale', 'Maker neutro validato: cattura lo spread dai due lati'], ['Direzionale', 'Solo il lato indicato dai motori (serve consenso ML+Poisson)'], ['Entrambe', 'Maker neutro + direzione sulle selezioni con consenso']].map(function (m, i) { return '<div class="panel flat" style="padding:8px;' + (i ? '' : 'border-color:var(--emerald)') + '"><b style="font-size:12px">' + m[0] + '</b><div class="foot">' + m[1] + '</div></div>'; }).join('') + '</div>' +
        '<label class="field" for="sc-st">Stake €<input id="sc-st" value="25"></label><label class="row amb" style="font-size:12px"><input type="checkbox" checked id="sc-demo"> DEMO · PAPER (ordini SIMULATI, ciclo completo — mai soldi veri)</label><label class="row" style="font-size:12px"><input type="checkbox" checked id="sc-mt"> Missione Tick Pre-Match: al primo ciclo verde il bot smette di aprire (validato: 5/6 eventi col tick in 3-27 min, zero eventi rossi).</label><label class="row" style="font-size:12px"><input type="checkbox" id="sc-ht"> ⚠️ Gamba INTERVALLO (HT, sperimentale)</label><label class="row" style="font-size:12px"><input type="checkbox" checked id="sc-sn"> 🎯 SNIPER in-play (S16): 1 tick sull’Under al momento letto dal book, poi stop. ACCESO di default (decisione utente 25/09).</label><label class="row" style="font-size:12px"><input type="checkbox" id="sc-th"> 🔬 THETA in-play (sperimentale)</label>' +
        '<details><summary class="lbl" style="cursor:pointer">Parametri (default validati in backtest)</summary><div class="grid g2" style="gap:6px;margin-top:6px">' + [['Tick di profitto', 1], ['Tick di stop', 1], ['Flusso min €/lato (90s)', 10], ['Size min ai best €', 300], ['Quota min', '1,5'], ['Quota max', '4,6'], ['Stop ingressi (s pre-KO)', 420], ['Chiusura forzata (s pre-KO)', 180], ['Target profitto €', 1], ['Tetto perdita €', '1,5']].map(function (x, i) { return '<label class="field" for="scp' + i + '">' + x[0] + '<input id="scp' + i + '" value="' + x[1] + '"></label>'; }).join('') + '</div><a class="foot" style="cursor:pointer;text-decoration:underline">Ripristina i default validati</a></details>' +
        '<div class="row"><button class="btn pri" data-act="sl-scalper-on">Attiva in PAPER (simulato)</button><button class="btn" data-act="sl-scalper-form">Annulla</button></div></section>';
    }
    if (name === 'Chart') return '<section class="panel" style="padding:12px">' + '<div class="row" style="margin-bottom:6px"><select class="inp" id="sl-ch" aria-label="Selezione"><option>Inter</option><option>Torino</option><option>The Draw</option></select><div class="seg" aria-label="Timeframe">' + ['5s', '15s', '30s', '1m', '5m'].map(function (x, i) { return '<button aria-pressed="' + (i === 1) + '">' + x + '</button>'; }).join('') + '</div></div>' + S.candles() + '<p class="foot">Aggiornato: 10:41:23 (canale) · storia solo da quando il pannello è aperto</p></section>';
    return S.depthPanel(['Inter', 'Torino', 'The Draw']);
  }
  S.on('sl-scalper-form', function () { S.ui.slScalperForm = !S.ui.slScalperForm; S.rerender(); });
  S.on('sl-scalper-on', function () { S.ui.slScalper = true; S.ui.slScalperForm = false; S.rerender(); S.toast('Scalper ATTIVATO in PAPER (ordini simulati) — Inter v Torino'); });
  S.on('sl-scalper-stop', function () { S.ui.slScalper = false; S.rerender(); S.toast('Stop richiesto: chiusura flat in corso…'); });

  function terminal(f) {
    var mode = S.ui.slMode || 'PAPER', mk = S.tab('sl-mk', 'mo'), tl = S.tab('sl-tool', 'Trading');
    var markets = [['mo', 'Match Odds'], ['ou25', 'Over/Under 2.5 Goals'], ['ou35', 'Over/Under 3.5 Goals'], ['cs', 'Correct Score'], ['ht', 'Half Time']];
    var h = '';
    h += '<section class="panel flat" style="padding:8px 12px;display:flex;flex-wrap:wrap;gap:8px;align-items:center;position:sticky;top:56px;z-index:30;background:hsl(var(--background)/.92)">' +
      (mode === 'LIVE' ? '<span class="chip live" style="background:#dc2626;color:#fff">🔴 LIVE — SOLDI VERI</span>' : mode === 'PAPER' ? '<span class="chip paper">PAPER</span>' : '<span class="chip">OFF</span>') + '<span class="chip paper" title="Canale LOCALE attivo (ws://127.0.0.1:47331)">⚡ LOCALE</span><b class="mono pos" title="Minuto di gioco e punteggio">' + f.min + "' · " + f.score + '</b>' +
      '<span class="mono pos" title="P&L di giornata (settled + MTM)">oggi +€8,12</span><span class="mono">saldo €' + D.conto.disponibile.toFixed(2).replace('.', ',') + '</span><span class="chip paper">♥ runner +wd</span><span class="amb mono">exp evento €10,40</span><span class="mono"><span style="color:var(--back)">99,1%</span> / <span style="color:var(--lay)">101,2%</span></span><span class="foot">agg. 1s fa</span>' +
      '<span class="row" style="margin-left:auto;gap:6px"><button class="btn sm" style="background:#f59e0b;color:#111;border-color:transparent;font-weight:800" data-act="sl-cash" data-v="MERCATO">Cash-out MERCATO (+€0,46)</button><button class="btn sm" style="background:#e11d48;color:#fff;border-color:transparent;font-weight:800" data-act="sl-cash" data-v="EVENTO">Cash-out EVENTO (+€0,40)</button><button class="btn sm danger" data-act="sl-kill" title="KILL-SWITCH GLOBALE del runner: blocca le APERTURE (le chiusure restano possibili) — hotkey Esc">KILL</button><span class="iconbtn" style="width:26px;height:26px" title="Scorciatoie tastiera: G = cash-out mercato attivo · X = cash-out intero evento · Esc = kill-switch globale · PageUp/PageDown = mercato">?</span></span></section>';
    h += '<div class="strip warn">⚠ RISCHIO GOL: P(gol ≤ 5′) ≈ 14 % · modello al 58′<button class="btn sm gold" style="margin-left:auto" data-act="sl-cash" data-v="EVENTO">Copri ora (+€0,40)</button></div>';
    h += '<div class="tabs">' + markets.map(function (m) { return '<button aria-selected="' + (mk === m[0]) + '" data-act="tab" data-scr="sl-mk" data-v="' + m[0] + '">' + m[1] + '</button>'; }).join('') + '<a class="btn sm gold" style="margin-left:auto;align-self:center" data-go="multi-ladder" href="#multi-ladder" title="Workspace Multi-ladder: N ladder affiancati anche di eventi/sport diversi">⧉ Multi-ladder</a></div>';
    var mname = markets.filter(function (m) { return m[0] === mk; })[0][1];
    var sels = mk === 'mo' ? ['Inter', 'Torino', 'The Draw'] : mk === 'cs' ? ['1 - 0', '1 - 1', '2 - 0'] : mk === 'ht' ? ['Inter', 'Torino', 'The Draw'] : ['Under ' + (mk === 'ou25' ? '2.5' : '3.5') + ' Goals', 'Over ' + (mk === 'ou25' ? '2.5' : '3.5') + ' Goals'];
    var ltps = mk === 'mo' ? [1.38, 11.5, 5.6] : mk === 'cs' ? [3.65, 7.2, 6.5] : mk === 'ht' ? [1.12, 30, 9.4] : [mk === 'ou25' ? 1.62 : 1.22, mk === 'ou25' ? 2.6 : 5.6];
    h += '<div class="sl-grid">' +
      '<div class="col" style="gap:10px"><section class="panel" style="padding:10px"><div class="row"><span class="lbl">' + S.icon('wallet') + ' Posizioni · P&L</span><span class="chip" style="margin-left:auto" data-testid="rail-fonte-posizioni">canale</span></div><table class="t" style="font-size:11.5px"><thead><tr><th>Selezione</th><th class="r" title="P&L se la selezione VINCE">Vince</th><th class="r" title="P&L se la selezione PERDE">Perde</th><th class="r" title="Esposizione worst-case">Esp.</th></tr></thead><tbody><tr><td>Inter</td><td class="r pos">+1,95</td><td class="r neg">−5,00</td><td class="r ora">5,00</td></tr></tbody></table></section>' +
      '<section class="panel" style="padding:10px"><div class="lbl">Ordini (1 attivi)</div><div class="row" style="font-size:12px;margin-top:6px">' + chip('BACK', 'sky') + 'Inter <span class="mono" title="residuo ANCORA VIVO sul book @ prezzo chiesto">5,00@1,36</span><button class="btn sm ghost" style="margin-left:auto" aria-label="Annulla ordine BACK su Inter" data-act="toast" data-t="Annulla l’ordine (via coda comandi)">✕</button></div><div class="row" style="font-size:12px;opacity:.75">' + chip('BACK', 'sky') + 'Inter <span class="mono" title="size abbinata @ prezzo MEDIO dichiarato da Betfair">✓ 5,00@1,40</span></div></section></div>' +
      '<div style="min-width:0">' + S.ladderView({ id: 'sl-' + mk, market: mname, sels: sels, ltps: ltps, mode: mode, sport: 'calcio', mine: mk === 'mo', esito: mk === 'mo' ? 'BACK €5,00 @ 1,40 · Lapse · Inter — abbinato' : '' }) + '</div>' +
      '<div class="col" style="gap:8px;min-width:0"><div class="tabs">' + ['Trading', 'Dutching', 'Risk', 'X-Hedge', 'Scalper', 'Chart', 'Depth'].map(function (t) { return '<button aria-selected="' + (tl === t) + '" data-act="tab" data-scr="sl-tool" data-v="' + t + '">' + t + '</button>'; }).join('') + '</div>' + tool(tl, mode) + '</div></div>';
    h += '<details class="panel flat" style="padding:10px 14px"><summary class="lbl" style="cursor:pointer">▸ Controlli runner · limiti · audit</summary><div class="col" style="gap:10px;margin-top:10px"><div class="row"><b>Controlli Runner</b>' + chip('Globale') + '<span class="foot">Kill-switch, limiti operativi e registro eventi — validi per <b>tutti</b> i mercati.</span></div>' +
      '<button class="btn" style="justify-content:space-between;height:44px" data-act="sl-kill"><span>' + (S.ui.slKill ? '🔴 KILL-SWITCH ATTIVO — aperture rifiutate, chiusure permesse' : 'Kill-switch disattivato — runner operativo') + '</span>' + chip(S.ui.slKill ? 'ATTIVO' : 'OFF', S.ui.slKill ? 'live' : '') + '</button>' +
      '<div class="row" style="font-size:12px"><b>P&L giornata (01/10)</b><span class="pos">+8,12 €</span><span class="foot">settled +8,12 · MTM +0,40</span><span class="foot" style="margin-left:auto">stop a −€50</span></div>' +
      '<div class="grid g4" style="gap:8px">' + [['Max esposizione / selezione (€)', '50'], ['Max ordini / min', '30'], ['Poll ordini (s)', '0,15'], ['Poll rischio (s)', '0,15'], ['Stop giornaliero (€ perdita max)', '50'], ['Max esposizione / evento (€)', '100'], ['Max esposizione / campionato (€)', '']].map(function (x, i) { return '<label class="field" for="lc' + i + '">' + x[0] + '<input id="lc' + i + '" value="' + x[1] + '" placeholder="nessun limite"></label>'; }).join('') + '</div><p class="foot" style="margin:0">Le velocità (poll) si applicano al <b>RIAVVIO</b> del runner (come LIVE_ORDER_MODE). Campo vuoto = nessun limite.</p><button class="btn gold" style="align-self:flex-start" data-act="toast" data-t="Impostazioni salvate" data-d="Le velocità di poll si applicano al riavvio del runner.">Salva</button>' +
      '<div class="lbl">Registro eventi (3) <span class="chip paper">● LIVE</span></div><table class="t" style="font-size:11px"><thead><tr><th>Ora</th><th>Modo</th><th>Azione</th><th>Mercato / sel.</th><th>Lato</th><th class="r">Prezzo</th><th class="r">Size</th><th>Stato</th><th>Errore</th></tr></thead><tbody><tr><td class="mono">10:40:51</td><td>PAPER</td><td>place</td><td>MO / Inter</td><td style="color:var(--back)">BACK</td><td class="r">1,40</td><td class="r">5,00</td><td class="pos">EXECUTION_COMPLETE</td><td></td></tr><tr><td class="mono">10:38:02</td><td>PAPER</td><td>place</td><td>MO / Inter</td><td style="color:var(--back)">BACK</td><td class="r">1,36</td><td class="r">5,00</td><td class="amb">EXECUTABLE</td><td></td></tr></tbody></table></div></details>';
    h += '<div class="grid" style="grid-template-columns:minmax(0,2fr) minmax(0,1fr)">' + S.panel('Tabellone mercati', '<div class="row" style="margin-bottom:8px">' + ['Match Odds 3', 'Over/Under 6', 'Correct Score 1', 'First Half 2', 'BTTS 1', 'Squadre/Altri 4'].map(function (x, i) { return '<button class="chip" style="cursor:pointer;' + (i ? '' : 'background:hsl(var(--primary));color:#062;border-color:transparent') + '">' + x + '</button>'; }).join('') + '<span class="foot" style="margin-left:auto">Aggiornato: 10:41:23</span></div><div class="grid g2">' + [['Match Odds', 'MATCH_ODDS', [['Inter', 1.38, 1.39], ['Torino', 11.5, 12], ['The Draw', 5.6, 5.7]]], ['Over/Under 2.5 Goals', 'OVER_UNDER_25', [['Under 2.5 Goals', 1.62, 1.63], ['Over 2.5 Goals', 2.6, 2.62]]]].map(function (m) { return '<div class="panel flat" style="padding:8px"><div class="row"><b style="font-size:12px">' + m[0] + '</b><span class="lbl" style="font-size:9px">' + m[1] + '</span><span class="seg" style="margin-left:auto"><button aria-pressed="false">Ladder</button><button aria-pressed="true">Griglia</button></span></div><table class="t" style="font-size:11.5px"><thead><tr><th>Selezione</th><th class="r">Back</th><th class="r">Lay</th><th class="r">LTP</th></tr></thead><tbody>' + m[2].map(function (r) { return '<tr><td>' + r[0] + '</td><td class="r" style="color:var(--back)">' + S.odds(r[1]) + '</td><td class="r" style="color:var(--lay)">' + S.odds(r[2]) + '</td><td class="r mut">' + S.odds(r[1]) + '</td></tr>'; }).join('') + '</tbody></table></div>'; }).join('') + '</div>') +
      S.panel('Segnali Motore Live', [['Match Odds', 'Inter', 'BACK', 72, '1,33', '1,38', '+3,8%', '£4,20'], ['Over/Under 2.5', 'Under 2.5 Goals', 'BACK', 64, '1,55', '1,62', '+4,3%', '£3,10']].map(function (s) { return '<div class="panel flat" style="padding:8px;margin-bottom:6px"><div class="lbl" style="font-size:9.5px">' + s[0] + '</div><div class="row" style="font-size:12px"><b>' + s[1] + '</b>' + chip('↗ ' + s[2], 'paper') + '<span class="bar" style="flex:1"><i style="width:' + s[3] + '%"></i></span></div><div class="foot">fair ' + s[4] + ' · mkt ' + s[5] + ' · edge <b class="pos">' + s[6] + '</b> · Kelly <b>' + s[7] + '</b></div></div>'; }).join('') + '<p class="foot">1 segnali nascosti (HOLD o mercati chiusi)</p>', { icon: 'bolt', right: '<span class="mono foot">10:41:20</span>' }) + '</div>';
    return h;
  }
  S.on('sl-cash', function (t) {
    var mode = S.ui.slMode || 'PAPER', ev = t.dataset.v === 'EVENTO';
    S.modal({ danger: mode === 'LIVE', title: 'CASH-OUT ' + (mode === 'LIVE' ? 'REALE (soldi veri)' : 'SIMULATO (paper)') + (ev ? ' dell’INTERO EVENTO' : ' del SOLO mercato'), body: ev ? 'Appiattisce TUTTE le selezioni con esposizione aperta su TUTTI i mercati dell’evento «Inter v Torino» (non solo quello attivo).' + (mode === 'LIVE' ? ' <b>SOLDI VERI.</b> Seconda conferma: green-up REALE di TUTTI i mercati dell’evento.' : '') : 'Appiattisce TUTTE le selezioni con esposizione aperta di QUESTO mercato «Match Odds».', ok: 'Cash-out ' + t.dataset.v, onOk: function () { S.toast('Cash-out ' + t.dataset.v + ' inviato', 'Prototipo: nessun ordine.'); } });
  });
  S.on('sl-kill', function () {
    if (S.ui.slKill) { S.modal({ title: 'Disattivare il KILL-SWITCH globale?', body: 'Il runner tornerà a processare gli ordini.', ok: 'Disattiva', onOk: function () { S.ui.slKill = false; S.rerender(); } }); return; }
    S.modal({ danger: true, title: 'KILL-SWITCH', body: 'Blocca immediatamente ogni invio ordini del runner. Attivare?', ok: 'Attiva', onOk: function () { S.ui.slKill = true; S.rerender(); S.toast('Kill-switch ATTIVATO', 'Invio ordini bloccato.'); } });
  });
  S.on('sl-open', function (t) { S.ui.slSel = S.ui.slSel === t.dataset.v ? null : t.dataset.v; S.rerender(); window.scrollTo(0, 0); });
  S.on('sl-mode', function (t) { if (t.dataset.v === 'LIVE') S.confirmLive('Runner calcio', function () { S.ui.slMode = 'LIVE'; S.rerender(); }); else { S.ui.slMode = t.dataset.v; S.rerender(); } });

  S.reg({
    id: 'segui-live', title: 'Segui live · terminal calcio', group: 'Calcio',
    render: function () {
      var sel = FOLLOWS.filter(function (f) { return f.id === S.ui.slSel; })[0];
      var h = '<div class="row"><a class="btn sm" data-go="market-watch" href="#market-watch">Market Watch</a><a class="btn sm" data-go="live-pnl" href="#live-pnl">P&L</a><a class="btn sm" data-go="trade-journal" href="#trade-journal">Journal</a><a class="btn sm gold" data-go="match-replay" href="#match-replay">' + S.icon('replay') + ' Match Replay</a><span class="foot" style="margin-left:auto">scorciatoie verso gli strumenti del terminal (oggi sono qui; nel redesign stanno anche nella sidebar)</span></div>';
      h += '<div class="strip warn"><b>WARN</b><span class="mono foot">[NEW_MATCHES]</span><span>2 nuove partite agganciate dal runner per i bot.</span><button class="btn sm ghost" style="margin-left:auto" aria-label="Ignora avviso" data-act="toast" data-t="Avviso ignorato">✕</button></div>';
      h += '<div class="ph"><div><h1>Segui <em>Live</em></h1><p>Partite sottoscritte allo stream Betfair. Clic su una partita per le quote in tempo reale.</p></div><div class="act">' + (sel ? '<button class="btn sm danger" data-act="toast" data-t="Registrazione attivata" data-d="La partita viene registrata per intero e a fine gara caricata nel Match Replay.">◉ REC</button><button class="btn sm" data-act="sl-open" data-v="' + sel.id + '">‹ Tutte le partite</button>' : '') +
        '<span class="lbl">Prototipo · modo runner</span><div class="seg mode">' + ['OFF', 'PAPER', 'LIVE'].map(function (m) { return '<button data-act="sl-mode" data-v="' + m + '" aria-pressed="' + ((S.ui.slMode || 'PAPER') === m) + '">' + m + '</button>'; }).join('') + '</div></div></div>';
      if (!sel) return h + habitat() + '<div class="grid g2">' + FOLLOWS.map(function (f) { return matchCard(f, false); }).join('') + '</div>';
      return h + '<div class="row">' + matchCard(sel, true).replace('<article class="panel"', '<article class="panel" style="flex:1"') + S.media(false) + '</div>' + terminal(sel);
    }
  });

  /* ---------- Multi-ladder ---------- */
  S.reg({
    id: 'multi-ladder', title: 'Multi-ladder', group: 'Trading',
    render: function () {
      var picker = S.ui.mlPick;
      var h = '<div class="ph"><div><h1>' + S.icon('grid', 'gold') + ' Multi-ladder <span class="cnt">2/8</span></h1><p>Workspace libero con N ladder affiancati, anche di mercati, eventi e sport diversi. Il layout resta su questo computer.</p></div><div class="act"><a class="btn sm" data-go="segui-live" href="#segui-live">← Segui live</a><button class="btn gold" data-act="ml-pick" title="Aggiungi il ladder di un mercato (eventi calcio seguiti)">+ Aggiungi ladder</button></div></div>';
      if (picker) h += S.panel('Aggiungi ladder', '<p class="foot" style="margin-top:0">Eventi calcio seguiti (i mercati <b>tennis</b> si aggiungono dal Trading Terminal tennis col bottone ' + S.icon('grid') + ').</p><div class="row">' + FOLLOWS.slice(0, 2).map(function (f, i) { return '<button class="chip" style="cursor:pointer;' + (i ? '' : 'background:hsl(var(--primary));color:#062') + '">' + f.casa + ' — ' + f.osp + '</button>'; }).join('') + '</div><div class="row" style="margin-top:8px"><button class="btn sm" disabled title="Già nel workspace">✓ Match Odds</button><button class="btn sm">+ Over/Under 2.5 Goals</button><button class="btn sm">+ Correct Score</button></div>');
      h += '<div class="row" style="align-items:flex-start;gap:12px">' +
        '<div style="flex:1;min-width:380px;max-width:640px"><div class="row foot" style="margin-bottom:6px">⚽ <b>Inter v Torino</b> · Match Odds<span style="margin-left:auto" class="row">' + S.media(true) + '<button class="iconbtn" style="width:24px;height:24px" title="Rimuovi dal workspace">✕</button></span></div>' + S.ladderView({ id: 'ml1', market: 'Match Odds', sels: ['Inter', 'The Draw'], ltps: [1.38, 5.6], mode: 'PAPER', sport: 'calcio', mine: true, multi: false }) + '</div>' +
        '<div style="flex:1;min-width:380px;max-width:640px"><div class="row foot" style="margin-bottom:6px">🎾 <b>Sinner v Draper</b> · Match Odds<span style="margin-left:auto" class="row">' + S.media(true) + '<button class="iconbtn" style="width:24px;height:24px" title="Rimuovi dal workspace">✕</button></span></div>' + S.ladderView({ id: 'ml2', market: 'Match Odds', sels: ['J. Sinner', 'J. Draper'], ltps: [1.25, 5.0], mode: 'PAPER', sport: 'tennis', tennis: true, multi: false }) + '</div></div>';
      return h;
    }
  });
  S.on('ml-pick', function () { S.ui.mlPick = !S.ui.mlPick; S.rerender(); });

  /* ---------- Ladder pop-out ---------- */
  S.reg({
    id: 'ladder-popout', title: 'Ladder pop-out', group: 'Trading',
    render: function () {
      return '<div class="strip info"><span class="lbl">Nel prodotto</span><span>questa è una finestra dedicata 560×860 (multi-monitor), aperta dal bottone «Stacca» di un ladder: nessuna barra di navigazione, solo il ladder.</span></div>' +
        '<div style="width:min(560px,100%);margin:0 auto;padding:8px;border:1px solid hsl(var(--glass-border));border-radius:14px;background:hsl(var(--background))"><div class="row foot" style="padding:0 4px 6px;justify-content:space-between"><span>Inter v Torino</span>' + S.media(true) + '</div>' + S.ladderView({ id: 'po', market: 'Match Odds', sels: ['Inter'], ltps: [1.38], mode: 'PAPER', sport: 'calcio', mine: true, popout: false, multi: true }) + '</div>' +
        '<p class="foot" style="text-align:center">Se mancano mercato o evento: «Parametri mancanti: servono market ed event.»</p>';
    }
  });

  /* ---------- Market watch ---------- */
  S.reg({
    id: 'market-watch', title: 'Market watch', group: 'Trading',
    render: function () {
      var row = function (o) {
        return '<section class="panel" style="padding:9px 14px;display:flex;align-items:center;gap:12px;flex-wrap:wrap"><div style="min-width:180px;flex:1"><b>' + o.nome + '</b><div class="foot">' + o.lega + '</div></div>' + chip(o.badge, o.bc) +
          '<div style="width:120px" title="P&L MTM se si greenasse ORA ai prezzi correnti" data-testid="mw-mtm-modi"><div class="lbl" style="font-size:9.5px">MTM</div><div class="foot" data-testid="mw-mtm-live"><span style="color:#fca5a5">live</span> <b class="' + S.tone(o.mtmL) + '">' + (o.mtmL == null ? '—' : M(o.mtmL, { signed: true })) + '</b></div><div class="foot" data-testid="mw-mtm-paper">prova <b class="' + S.tone(o.mtmP) + '">' + (o.mtmP == null ? '—' : M(o.mtmP, { signed: true })) + '</b></div></div>' +
          '<div style="width:130px" title="Esposizione worst-case aggregata, soldi veri e prova separati" data-testid="mw-rischio-modi"><div class="lbl" style="font-size:9.5px">Rischio</div><div class="foot">live <b class="ora">' + M(o.rL) + '</b></div><div class="foot">prova <b>' + M(o.rP) + '</b></div></div>' +
          (o.tennis ? '<span class="mut" title="Cash-out non disponibile: il worker tennis non supporta il cash-out">—</span>' : '<button class="btn sm gold" data-act="sl-cash" data-v="EVENTO">Cash-out EVENTO</button>') + '<a class="btn sm" style="color:var(--back)" data-go="' + (o.tennis ? 'tennis-terminal' : 'segui-live') + '" href="#">' + (o.tennis ? 'Apri terminal tennis' : 'Apri terminal') + '</a>' + S.media(true) + '</section>';
      };
      return '<div class="ph"><div><h1>' + S.icon('eye', 'gold') + ' Market <em>Watch</em></h1><p>Una riga per evento seguito: stato, P&L MTM ed esposizione worst-case. Calcio e tennis in due sezioni separate, soldi veri e prova mai sommati.</p></div><div class="act"><a class="btn sm" data-go="segui-live" href="#segui-live">← Terminal</a><span class="foot">modalità ordini: <b style="color:#6ee7b7">PAPER</b></span></div></div>' +
        '<h2 style="font-size:15px">⚽ Calcio</h2>' + row({ nome: 'Inter – Torino', lega: 'Serie A', badge: "LIVE 58' · 1–0", bc: 'inplay', mtmL: 0.4, mtmP: 1.3, rL: 2.4, rP: 12.4 }) + row({ nome: 'Real Betis – Getafe', lega: 'La Liga', badge: "LIVE 31' · 0–0", bc: 'inplay', mtmL: null, mtmP: 0.18, rL: 0, rP: 9.2 }) + row({ nome: 'Bologna – Udinese', lega: 'Serie A', badge: 'tra 14m', bc: '', mtmL: null, mtmP: 0.08, rL: 0, rP: 10 }) +
        '<h2 style="font-size:15px">🎾 Tennis</h2>' + row({ nome: 'J. Sinner vs J. Draper', lega: 'ATP Pechino', badge: 'LIVE · 6-4 2-1', bc: 'inplay', mtmL: null, mtmP: 0.3, rL: 0, rP: 5, tennis: true }) + row({ nome: 'C. Gauff vs M. Andreeva', lega: 'WTA Pechino', badge: 'FINITA · 6-3 6-4', bc: '', mtmL: null, mtmP: null, rL: 0, rP: 0, tennis: true });
    }
  });

  S.on('lp-mode', function (t) { S.ui.lpMode = t.value; S.rerender(); });
  /* ---------- Live P&L ---------- */
  S.reg({
    id: 'live-pnl', title: 'P&L di giornata', group: 'Trading',
    render: function () {
      var mode = S.ui.lpMode || 'live';
      var eq = [{ date: new Date(2026, 9, 1, 8, 15), pnl: 3.2 }, { date: new Date(2026, 9, 1, 9, 2), pnl: -1.4 }, { date: new Date(2026, 9, 1, 9, 58), pnl: 6.32 }];
      return '<div class="ph"><div><h1>' + S.icon('wallet', 'gold') + ' P&L di <em>giornata</em></h1><p>Fonti tracciabili. Una modalità alla volta (mai «tutte»); il MTM e il totale esistono solo per oggi.</p></div><div class="act"><a class="btn sm" data-go="segui-live" href="#segui-live">← Terminal</a><label class="field" for="lp-day">Giorno<input id="lp-day" type="date" value="2026-10-01"></label><label class="field" for="lp-mode">Mode<select class="inp" id="lp-mode" data-chg="lp-mode"><option' + (mode === 'paper' ? ' selected' : '') + '>paper</option><option' + (mode === 'live' ? ' selected' : '') + '>live</option></select></label></div></div>' +
        '<div class="grid g4">' + S.kpi('P&L realizzato', '<span class="pos">+8,12 €</span>', '3 mercati regolati · get_live_settled', '', mode === 'live' ? 'CONTO' : 'PROVA') + S.kpi('MTM aperto (' + mode + ')', '<span class="pos">+0,40 €</span>', '<span data-testid="livepnl-posizioni">2 posizioni aperte · rischio 2,40 € (' + mode + ')</span> · fonte canale', '', 'STIMA') + S.kpi('Totale giornata (' + mode + ')', '<span class="pos">+8,52 €</span>') + S.kpi('Stop giornaliero', '50,00 €', 'non scattato') + '</div>' +
        S.panel('Equity intraday (P&L realizzato cumulato · punto ambra = totale con MTM)', C.equity(eq, 'Equity intraday'), { icon: 'chart' }) +
        '<div class="grid g2">' + S.panel('Per mercato', '<div class="tbl-w"><table class="t"><thead><tr><th>Mercato</th><th>Evento</th><th class="r">P&L</th><th>Fonte</th><th>Ora</th></tr></thead><tbody><tr><td>Over/Under 3.5</td><td>Napoli v Lazio</td><td class="r pos">+8,12</td><td>' + chip(mode === 'live' ? 'reale' : 'simulato', mode === 'live' ? 'live' : 'sky') + '</td><td class="mono">09:58</td></tr><tr><td>Match Odds</td><td>Feyenoord v AZ</td><td class="r neg">−1,40</td><td>' + chip(mode === 'live' ? 'reale' : 'simulato', mode === 'live' ? 'live' : 'sky') + '</td><td class="mono">09:02</td></tr></tbody></table></div>', { flush: true }) + S.panel('Per evento', '<div class="tbl-w"><table class="t"><thead><tr><th>Evento</th><th class="r">Mercati</th><th class="r">P&L</th></tr></thead><tbody><tr><td>Napoli v Lazio</td><td class="r">1</td><td class="r pos">+8,12</td></tr><tr><td>Feyenoord v AZ</td><td class="r">1</td><td class="r neg">−1,40</td></tr></tbody></table></div>', { flush: true }) + '</div>' +
        S.panel('🎾 Tennis (posizioni aperte)', '<div class="strip warn" style="margin-bottom:8px">il settled tennis non è ancora storicizzato — qui SOLO le esposizioni aperte (get_tennis_live_positions_all)</div><table class="t"><thead><tr><th>Evento</th><th class="r">Posizioni</th><th class="r">Σ esposizione</th><th class="r">Σ net</th></tr></thead><tbody><tr><td>Sinner v Draper</td><td class="r">2</td><td class="r ora">5,00</td><td class="r">4,00</td></tr></tbody></table>');
    }
  });
})();
