/* s_storici.js - Storico calcio / Storico tennis (StoricoSport.tsx), Trade journal, Report personale. */
(function () {
  'use strict';
  var S = window.S, D = window.D, C = S.C;

  /* =================== STORICO SPORT =================== */
  function storico(sport) {
    var scr = 'storico-' + sport;
    var modo = S.ui[scr + '-modo'] || 'live';
    var per = S.ui[scr + '-per'] || '30g';
    var bot = S.ui[scr + '-bot'] || 'tutti';
    var mig = S.ui.migrazione === true; // migrazione storico_sport_2026-09-17 applicata?
    var veri = modo === 'live';
    var nGiorni = { oggi: 1, '7g': 7, '30g': 30, mese: 1, tutto: 60 }[per] || 30;
    var bots = sport === 'calcio' ? [['omega', 'Omega', 'prim'], ['safe', 'Safe Strategy', 'gold'], ['mike', 'Mike', 'tealc']] : [['safe', 'Safe Strategy · tennis', 'gold']];
    var sep = bots.filter(function (b) { return !(b[0] === 'omega' && !mig); });
    var perBot = sep.map(function (b) { var g = D.giorni(b[0] + sport, modo, nGiorni); var pnl = g.reduce(function (a, d) { return a + d.pnl; }, 0); var v = g.reduce(function (a, d) { return a + d.v; }, 0), p = g.reduce(function (a, d) { return a + d.p; }, 0); return { b: b, g: g, pnl: pnl, ops: v + p, v: v, p: p, stake: mig ? (v + p) * 9.4 : null }; });
    var tot = perBot.reduce(function (a, r) { return { pnl: a.pnl + r.pnl, ops: a.ops + r.ops, v: a.v + r.v, p: a.p + r.p, stake: mig ? a.stake + r.stake : null }; }, { pnl: 0, ops: 0, v: 0, p: 0, stake: 0 });
    var giorniSel = (bot === 'tutti' ? D.giorni('tutti' + sport, modo, nGiorni) : D.giorni(bot + sport, modo, nGiorni));
    var mixSel = bot === 'omega' && !mig;
    if (mixSel) giorniSel = [];
    var altro = D.giorni('altro' + sport, veri ? 'paper' : 'live', nGiorni).reduce(function (a, d) { return { pnl: a.pnl + d.pnl, n: a.n + d.n }; }, { pnl: 0, n: 0 });
    var sel = S.ui['day_' + scr] || (giorniSel[giorniSel.length - 1] || {}).iso;
    var day = giorniSel.filter(function (d) { return d.iso === sel; })[0];
    var em = sport === 'calcio' ? '⚽' : '🎾', other = sport === 'calcio' ? 'tennis' : 'calcio';
    var modoSeg = function (id) { return '<div class="seg mode" role="group" aria-label="Modalità dello storico" data-testid="' + id + '"><button data-act="st-modo" data-scr="' + scr + '" data-v="live" aria-pressed="' + veri + '" style="' + (veri ? 'background:rgba(239,68,68,.2);color:#fca5a5;box-shadow:inset 0 0 0 1px rgba(239,68,68,.5)' : '') + '">SOLDI VERI</button><button data-act="st-modo" data-scr="' + scr + '" data-v="paper" aria-pressed="' + !veri + '" style="' + (!veri ? 'background:rgba(16,185,129,.16);color:#6ee7b7;box-shadow:inset 0 0 0 1px rgba(16,185,129,.45)' : '') + '">PROVA</button></div>'; };
    var pill = function (k, v, label, cur, title) { return '<button class="chip" style="cursor:pointer;height:24px;' + (cur === v ? 'border-color:hsl(var(--primary)/.6);color:hsl(var(--primary));background:hsl(var(--primary)/.1)' : '') + '" data-act="st-set" data-scr="' + scr + '" data-k="' + k + '" data-v="' + v + '"' + (title ? ' title="' + title + '"' : '') + '>' + label + '</button>'; };

    var h = '';
    // A. testata
    h += '<section class="panel flat" data-testid="storico-testata" style="padding:10px 14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;border-color:' + (veri ? 'rgba(239,68,68,.35)' : 'hsl(var(--border))') + '">' +
      '<a class="btn sm" data-go="control-room" href="#control-room">← Control Room</a><h1 style="font-size:18px">' + S.icon('history') + ' ' + em + ' STORICO ' + sport.toUpperCase() + '</h1>' +
      '<a class="btn sm ghost" data-go="storico-' + other + '" href="#storico-' + other + '" data-testid="storico-testata-altro">' + (other === 'tennis' ? '🎾' : '⚽') + ' passa al ' + other + '</a>' +
      '<div class="row" style="margin-left:auto">' + S.chip(veri ? 'soldi veri' : 'prova', veri ? 'live' : '') + modoSeg('storico-testata-modi') + '<button class="btn sm" data-act="toast" data-t="Storico ricaricato" data-testid="storico-ricarica">↻ Ricarica</button></div></section>';
    // B. filtri
    h += '<section class="panel" data-testid="storico-filtri" style="padding:10px 14px;display:flex;gap:16px;flex-wrap:wrap;align-items:center">' +
      '<div class="row"><span class="lbl">periodo</span>' + [['oggi', 'Oggi'], ['7g', '7 giorni'], ['30g', '30 giorni'], ['mese', 'Mese corrente'], ['tutto', 'Tutto']].map(function (x) { return pill('per', x[0], x[1], per); }).join('') + '</div>' +
      '<div class="row"><span class="lbl">soldi</span>' + pill('modo', 'live', 'soldi veri', modo, 'solo operazioni con denaro reale') + pill('modo', 'paper', 'prova', modo, 'solo operazioni simulate') + '</div>' +
      '<div class="row"><span class="lbl">bot</span>' + pill('bot', 'tutti', 'tutti', bot) + bots.map(function (b) { return pill('bot', b[0], b[1], bot); }).join('') + '</div>' +
      '<span class="foot" style="margin-left:auto" data-testid="storico-intervallo">2 settembre 2026 → 1 ottobre 2026</span></section>';
    // prototipo: stato migrazione
    if (sport === 'calcio') h += '<div class="strip info"><span class="lbl">Prototipo</span><span>stato della migrazione <span class="mono">storico_sport_2026-09-17.sql</span>:</span><div class="seg"><button data-act="st-mig" data-v="0" aria-pressed="' + !mig + '">da applicare</button><button data-act="st-mig" data-v="1" aria-pressed="' + mig + '">applicata</button></div></div>';
    // D. riepilogo
    h += '<section class="stack"><div class="row" style="justify-content:space-between"><h2 style="font-size:16px">' + em + ' Storico ' + sport + ' · <span class="' + (veri ? 'neg' : '') + '" style="' + (veri ? 'color:#fca5a5' : 'opacity:.7') + '">' + (veri ? 'soldi veri' : 'prova') + '</span></h2><span class="foot">' + { oggi: 'oggi', '7g': '7 giorni', '30g': '30 giorni', mese: 'mese corrente', tutto: 'tutto' }[per] + ' · ' + sep.length + ' bot</span></div>' +
      C.kpiRow([[veri ? 'P&L soldi veri' : 'P&L prova', S.money(tot.pnl, { signed: true }), 'netto di commissione, solo questa modalità', S.tone(tot.pnl), veri ? 'BOT' : 'PROVA'], ['Operazioni', tot.ops, tot.ops + ' regolate'], ['Vinte / perse', '<span class="pos">' + tot.v + '</span> / <span class="neg">' + tot.p + '</span>', S.pct(tot.v / (tot.ops || 1)) + ' vinte'], ['Importo piazzato', mig ? S.money(tot.stake) : '—', mig ? 'somma delle size di apertura' : 'migrazione da applicare'], ['ROI su stake', mig ? S.pct(tot.pnl / tot.stake) : '—', mig ? 'P&L / importo piazzato' : 'serve l’importo piazzato', mig ? S.tone(tot.pnl) : '']]) +
      '<div class="row foot" data-testid="storico-altra-modalita">' + S.chip(veri ? 'prova' : 'soldi veri', veri ? '' : 'live') + '<b class="' + S.tone(altro.pnl) + '">' + S.money(altro.pnl, { signed: true }) + '</b> su ' + altro.n + ' operazioni — <b>non è sommato</b> ai numeri qui sopra: sono due monete diverse.</div>' +
      (!mig ? '<div class="amb" style="font-size:11.5px" data-testid="storico-manca-stake">ROI non calcolabile: serve l’importo piazzato per giornata, che oggi nessuna RPC espone. Lo aggiunge <span class="mono">migrations/storico_sport_2026-09-17.sql</span> — <b>da applicare</b>.</div>' : '') + '</section>';
    // E. non separabile
    if (sport === 'calcio' && !mig) h += '<div class="strip warn" data-testid="storico-modo-non-separabile" style="flex-direction:column;align-items:flex-start;gap:6px"><b class="amb">⚠ Omega: soldi veri e simulati non separabili</b><span style="font-size:12px">La RPC di questo bot non sa filtrare per modalità (verificato sul database il 17/09: <span class="mono">get_omega_daily</span> esiste solo con <span class="mono">p_from</span> e <span class="mono">p_to</span>). Le sue righe sono <b>miste</b> e per questo restano FUORI dai totali qui sopra. La cura è <span class="mono">migrations/storico_sport_2026-09-17.sql</span> — <b>da applicare</b>.</span><span class="mono" style="font-size:11.5px" data-testid="storico-misto-omega">Omega: +38,40 € su 61 operazioni (paper + live insieme)</span></div>';
    // G. per bot
    h += '<section class="panel" data-testid="storico-per-bot"><div class="panel-h"><h3>Per bot</h3><span class="note">' + (veri ? 'soldi veri' : 'prova') + ' · ' + per + '</span></div><div class="tbl-w"><table class="t"><thead><tr><th>bot</th><th class="r">P&L</th><th class="r">operazioni</th><th class="r">vinte / perse</th><th class="r">% vinte</th><th class="r">importo piazzato</th><th class="r">ROI</th></tr></thead><tbody>' +
      perBot.map(function (r) { return '<tr data-testid="storico-bot-riga-' + r.b[0] + '"><td class="' + r.b[2] + '"><b>' + r.b[1] + '</b></td><td class="r ' + S.tone(r.pnl) + '"><b>' + S.money(r.pnl, { signed: true }) + '</b></td><td class="r">' + r.ops + '</td><td class="r"><span class="pos">' + r.v + '</span> / <span class="neg">' + r.p + '</span></td><td class="r">' + S.pct(r.v / (r.ops || 1)) + '</td><td class="r">' + (mig ? S.money(r.stake) : '—') + '</td><td class="r ' + (mig ? S.tone(r.pnl) : '') + '">' + (mig ? S.pct(r.pnl / r.stake) : '—') + '</td></tr>'; }).join('') +
      '<tr data-testid="storico-riga-totale" style="font-weight:700"><td>Totale ' + (veri ? 'soldi veri' : 'prova') + '</td><td class="r ' + S.tone(tot.pnl) + '">' + S.money(tot.pnl, { signed: true }) + '</td><td class="r">' + tot.ops + '</td><td class="r">' + tot.v + ' / ' + tot.p + '</td><td class="r">' + S.pct(tot.v / (tot.ops || 1)) + '</td><td class="r">' + (mig ? S.money(tot.stake) : '—') + '</td><td class="r">' + (mig ? S.pct(tot.pnl / tot.stake) : '—') + '</td></tr></tbody></table></div></section>';
    // H. senza storico
    h += '<section class="panel flat" data-testid="storico-senza-storico" style="padding:12px 14px"><div class="lbl" style="margin-bottom:6px">Non compaiono in questi numeri</div><ul style="margin:0;padding-left:18px;font-size:12px;line-height:1.7">' +
      (sport === 'calcio' ? '<li><b>Scalper calcio</b> — non scrive operazioni regolate con P&L su nessuna tabella di trade: <span class="mono">scalper_activity</span> è un diario di scansioni, non un registro di posizioni.</li>'
        : '<li><b>Tennis Scalper</b> — gli ordini finiscono in <span class="mono">tennis_live_orders</span>, che non ha né P&L né regolamento: nessuna giornata da sommare.</li>' + ['Tennis Pro', 'Tennis FLB', 'Tennis Swing'].map(function (n) { return '<li><b>' + n + '</b> — stessa tabella ordini senza P&L; <span class="mono">tennis_bot_control.stats</span> è la fotografia della sessione in corso, non uno storico per giorno.</li>'; }).join('')) +
      '</ul><p class="foot" style="margin:6px 0 0">Non è uno zero: è un dato che il database non ha. Mostrarli a «0,00 €» direbbe che non hanno guadagnato nulla, che è un’altra cosa.</p></section>';
    if (mixSel) h += '<div class="strip warn" data-testid="storico-bot-scelto-misto">Hai scelto un bot le cui righe sono <b>miste</b> (paper + live): curva, barre e calendario qui sotto restano vuoti apposta. I suoi numeri complessivi sono nel riquadro «modalità non separabile» qui sopra.</div>';
    // J. curva + barre
    h += '<div class="grid g2">' + C.equityCard(giorniSel, (veri ? 'soldi veri' : 'prova') + ' · ' + (bot === 'tutti' ? 'tutti i bot' : bot) + ' · ' + per, 'storico-curva') +
      S.panel('P&L per giornata <span class="mut" style="font-weight:500">· ' + (veri ? 'soldi veri' : 'prova') + '</span>', C.barre(giorniSel, sel, scr) + '<p class="foot" style="margin:6px 0 0">una barra per giornata con operazioni (i giorni senza operazioni non diventano barre a zero: non aver operato non è chiudere in pari) — clic su una barra per aprire il dettaglio</p>', { icon: 'chart', id: 'storico-barre' }) + '</div>';
    // K. calendario + dettaglio
    h += '<div class="grid g2">' + S.panel('Calendario — ' + (veri ? 'soldi veri' : 'prova'), C.calendar(giorniSel, { scr: scr, sel: sel }) + '<p class="foot" style="margin:6px 0 0">Il calendario mostra il MESE scelto; il periodo dei numeri qui sopra è ' + per + '. Una cella vuota fuori dal periodo caricato significa «non letto», non «nessuna operazione».</p>', { icon: 'calendar', id: 'storico-calendario' }) +
      S.panel('Operazioni del giorno', day ? (bot === 'tutti' ? sep : sep.filter(function (b) { return b[0] === bot; })).map(function (b) { return '<div class="lbl" style="margin:4px 0" data-testid="storico-dettaglio-' + b[0] + '">' + b[1] + ' · ' + Math.max(1, Math.round(day.n / sep.length)) + ' operazioni</div>' + C.dayDetail(b[0], { date: day.date, n: Math.max(1, Math.round(day.n / sep.length)), v: Math.max(0, Math.round(day.v / sep.length)), p: Math.max(0, Math.round(day.p / sep.length)), pnl: day[b[0]] || day.pnl }, modo); }).join('<div class="sep"></div>') : '<div class="empty">Scegli una giornata dal calendario o dalle barre per vedere le operazioni.</div>', { icon: 'pulse', id: 'storico-dettaglio-giorno', note: day ? '· ' + C.ggData(day.date) : '' }) + '</div>';
    // L/M
    h += '<div class="row"><a class="btn" data-go="control-room" href="#control-room">← Torna al banco della giornata</a><a class="btn" data-go="storico-' + other + '" href="#storico-' + other + '" data-testid="storico-altro-sport">' + (other === 'tennis' ? '🎾' : '⚽') + ' Storico ' + other + '</a></div>' +
      '<p class="foot" data-testid="page-footer">Le giornate vengono dalle RPC dei bot (motore condiviso trading_daily_history): stessa matematica dello Storico dentro Omega, Safe e Mike. Giornata operativa = giorno di PIAZZAMENTO, fuso Europe/Rome. Questa pagina non ricalcola nessun P&L e non somma mai soldi veri e simulati.</p>';
    return h;
  }
  S.reg({ id: 'storico-calcio', title: 'Storico calcio', group: 'Calcio', render: function () { return storico('calcio'); } });
  S.reg({ id: 'storico-tennis', title: 'Storico tennis', group: 'Tennis', render: function () { return storico('tennis'); } });
  S.on('st-modo', function (t) { S.ui[t.dataset.scr + '-modo'] = t.dataset.v; S.ui['day_' + t.dataset.scr] = null; S.rerender(); });
  S.on('st-set', function (t) { S.ui[t.dataset.scr + '-' + t.dataset.k] = t.dataset.v; if (t.dataset.k !== 'per') S.ui['day_' + t.dataset.scr] = null; S.rerender(); });
  S.on('st-mig', function (t) { S.ui.migrazione = t.dataset.v === '1'; S.rerender(); });

  /* =================== TRADE JOURNAL =================== */
  S.reg({
    id: 'trade-journal', title: 'Trade journal', group: 'Analisi',
    render: function () {
      var f = S.ui.tj || { mode: 'tutte', oggi: true };
      var rows = [
        ['21:14:07', 'LIVE', 'place', 'manuale', 'Over/Under 2.5 Goals', '1.234567890', '47973', 'LAY', '1.92 @ €10.00', "58' 1–0", '1.91 · 1.91/1.92', 'over +3,1%', 12.4, 'scalp', 'entrata pulita'],
        ['21:09:51', 'PAPER', 'stop_loss', 'regola', 'Match Odds', '1.234567812', '58805', 'BACK', '5.70 @ €6.00', "54' 1–0", '5.6 · 5.6/5.7', 'seg.', -6.0, 'stop', ''],
        ['20:47:30', 'LIVE', 'cancel', 'manuale', 'Over/Under 3.5 Goals', '1.234567845', '1222347', 'BACK', '1.38 @ €8.00', 'in-play', '1.39 · 1.38/1.39', 'seg.', null, '', ''],
        ['20:31:02', 'PAPER', 'greenup', 'regola', 'Match Odds', '1.234567900', '47999', 'LAY', '2.04 @ €12.00', "31' 0–0", '2.02 · 2.02/2.04', 'home −1,2%', 3.1, 'green', 'regola tp 2 tick'],
        ['19:58:44', 'LIVE', 'place', 'manuale', 'Correct Score', '1.234567777', '1', 'LAY', '7.40 @ €4.00', 'pre-match', '7.2 · 7.2/7.4', 'seg.', -4.0, '', '']
      ];
      if (f.mode !== 'tutte') rows = rows.filter(function (r) { return r[1].toLowerCase() === f.mode; });
      var h = '<div class="ph"><div><h1>📖 Trade <em>Journal</em></h1><p>Review post-sessione: ogni riga è un’azione loggata dal terminale live (ordini manuali e regole di rischio).</p></div><div class="act"><a class="btn" data-go="segui-live" href="#segui-live">← Terminal</a></div></div>' +
        '<section class="panel" style="padding:10px 14px;display:flex;gap:8px;flex-wrap:wrap;align-items:center">' +
        '<select class="inp" id="tj-mode" data-chg="tj-mode" title="Filtro mode">' + ['tutte', 'paper', 'live'].map(function (m) { return '<option value="' + m + '"' + (f.mode === m ? ' selected' : '') + '>mode: ' + m + '</option>'; }).join('') + '</select>' +
        '<select class="inp" id="tj-az" title="Filtro azione"><option>azione: tutte</option><option>cancel</option><option>greenup</option><option>place</option><option>stop_loss</option></select>' +
        '<select class="inp" id="tj-or" title="Filtro origine"><option>origine: tutte</option><option>manuale</option><option>regola</option></select>' +
        '<input class="inp" id="tj-tag" placeholder="filtro tag…"><label class="row" style="font-size:12px"><input type="checkbox" id="tj-oggi" checked> solo oggi</label>' +
        (f.mode === 'tutte' ? '<span class="chip amber" style="margin-left:auto" title="Oggi il filtro «tutte» somma paper e live nelle statistiche per pattern">tutte = paper + live nella stessa vista</span>' : '') + '</section>' +
        '<section class="panel flat"><div class="tbl-w"><table class="t"><thead><tr><th>Ora</th><th>Mode</th><th>Azione</th><th>Origine</th><th>Evento / Mercato</th><th>Sel.</th><th>Side</th><th class="r">Prezzo@Size</th><th>Min/Score</th><th class="r">LTP · best</th><th>Segnale</th><th class="r">P&L mercato</th><th>Tag</th><th>Nota</th><th></th></tr></thead><tbody>' +
        rows.map(function (r, i) {
          return '<tr><td class="mono">' + r[0] + '</td><td>' + S.chip(r[1], r[1] === 'LIVE' ? 'live' : 'sky') + '</td><td class="mono">' + r[2] + '</td><td>' + S.chip(r[3], r[3] === 'regola' ? '' : '') .replace('chip ', r[3] === 'regola' ? 'chip " style="color:#c4b5fd;border-color:rgba(167,139,250,.5)' : 'chip ') + '</td><td><div class="match"><b>' + r[4] + '</b><small class="mono">' + r[5] + '</small></div></td><td class="mono">' + r[6] + '</td><td>' + S.chip(r[7], r[7] === 'BACK' ? 'sky' : 'rose') + '</td><td class="r mono">' + r[8] + '</td><td>' + r[9] + '</td><td class="r mono" title="book registrato">' + r[10] + '</td><td>' + r[11] + '</td><td class="r ' + S.tone(r[12]) + '">' + (r[12] == null ? '<span title="mercato non ancora regolato">—</span>' : S.money(r[12], { signed: true })) + '</td>' +
            '<td><input class="inp" id="tj-t' + i + '" style="width:80px;height:24px" placeholder="tag" value="' + r[13] + '"></td><td><input class="inp" id="tj-n' + i + '" style="width:140px;height:24px" placeholder="nota" value="' + r[14] + '"></td><td><button class="btn sm gold" data-act="toast" data-t="Salvato ✓">Salva</button></td></tr>';
        }).join('') + '</tbody></table></div></section>' +
        '<h2 style="font-size:16px">Statistiche per pattern</h2><div class="grid g4">' +
        [['Per tag', [['scalp', 1, 10], ['green', 1, 12], ['stop', 1, 6], ['(senza tag)', 2, 12]]], ['Per side', [['LAY', 3, 26], ['BACK', 2, 14]]], ['Per origine', [['manuale', 3, 22], ['regola', 2, 18]]], ['Per minuto', [['45-60', 2, 16], ['30-45', 1, 12], ['pre-match', 1, 4], ['—', 1, 8]]]].map(function (c) {
          return '<div class="panel" style="padding:12px"><div class="lbl" style="margin-bottom:6px">' + c[0] + '</div>' + c[1].map(function (x) { return '<div class="row" style="justify-content:space-between;font-size:12px;padding:2px 0"><span>' + x[0] + '</span><span class="mono mut">' + x[1] + '× · €' + x[2] + '</span></div>'; }).join('') + '</div>';
        }).join('') + '</div>';
      return h;
    }
  });

  S.on('tj-mode', function (t) { S.ui.tj = Object.assign(S.ui.tj || { oggi: true }, { mode: t.value }); S.rerender(); });
  /* =================== REPORT PERSONALE =================== */
  S.reg({
    id: 'report-personale', title: 'Report personale', group: 'Analisi',
    render: function () {
      var days = D.giorni('report', 'live', 40);
      var tot = days.reduce(function (a, d) { return a + d.pnl; }, 0);
      var acc = 0, eq = days.map(function (d) { acc += d.pnl; return acc; });
      var peak = 0, uw = eq.map(function (v) { peak = Math.max(peak, v); return v - peak; });
      var trades = [
        ['30/09/26', '1290012', 'Serie A', '135', 'Italia', '2026', 'Inter', 'Torino', '2-0', 'Lay the Draw', 3.6, 'Resp. 26,00', '1', 8.12, 45, 'WON'],
        ['29/09/26', '1290455', 'La Liga', '140', 'Spagna', '2026', 'Getafe', 'Celta', '1-1', 'Lay the Draw', 3.3, 'Resp. 23,00', '0', -23.0, 90, 'LOST'],
        ['28/09/26', '1289001', 'Premier League', '39', 'Inghilterra', '2026', 'Brentford', 'Everton', '—', 'Back Over 2.5', 1.92, '10,00', '0', null, null, 'OPEN'],
        ['27/09/26', '1288730', 'Serie B', '136', 'Italia', '2026', 'Palermo', 'Bari', '1-0', 'Back Under 2.5', 1.74, '12,00', '1', 6.4, 30, 'PARTIAL'],
        ['26/09/26', '1288112', 'Bundesliga', '78', 'Germania', '2026', 'Mainz', 'Freiburg', '0-0', 'Lay Over 3.5', 4.4, 'Resp. 34,00', '0', 9.5, 90, 'WON']
      ];
      var exp = S.ui.rpExp;
      var h = '<div class="ph"><div><h1>Report <em>Personale</em></h1><p>La tua operatività reale (pre-match + live). Metriche calcolate lato DB.</p></div><div class="act"><a class="btn gold" data-go="watchlist" href="#watchlist">Watchlist</a><button class="btn pri" data-act="rp-add">＋ Inserisci operazione</button><button class="btn danger" data-act="rp-purge">Svuota Report</button></div></div>';
      h += S.panel('Filtri', '<div class="grid g4"><div class="field" style="grid-column:span 2">Periodo<button class="btn" style="justify-content:flex-start" data-act="toast" data-t="Seleziona periodo" data-d="Popover calendario: 1° clic Dal, 2° clic Al.">' + S.icon('calendar') + ' 01/09/26 → 30/09/26 <span class="mut">✕</span></button></div><label class="field" for="rp-str">Strategia<input id="rp-str" placeholder="tutte"></label><label class="field" for="rp-st">Stato<select id="rp-st" class="inp"><option>Tutti (chiusi)</option><option>Vinti</option><option>Persi</option><option>Annullati</option><option>Parziali</option><option>Aperti</option></select></label></div>', { icon: 'filter', right: '<button class="btn sm">Reset</button>' });
      h += S.panel('Cassa (depositi / prelievi)', '<div class="grid g3">' + S.kpi('Depositi', S.money(500), '', 'pos', 'CONTO') + S.kpi('Prelievi', S.money(-200), '', 'neg', 'CONTO') + S.kpi('Netto cassa', S.money(300, { signed: true }), '', 'pos') + '</div><div class="row" style="margin-top:8px">' + S.chip('02/09/26 · Deposito €500') + S.chip('21/09/26 · Prelievo €200') + '</div>', { note: 'non incluso nell’equity curve' });
      h += C.kpiRow([['P&L Totale', S.money(tot, { signed: true }), '', S.tone(tot), 'CONTO'], ['Giorni', days.length, 'giorni operativi'], ['% giorni positivi', S.pct(days.filter(function (d) { return d.pnl > 0; }).length / days.length), '', 'pos'], ['Media/giorno', S.money(tot / days.length, { signed: true }), '', S.tone(tot)], ['Max Drawdown', S.money(Math.min.apply(null, uw)), '', 'neg'], ['Sharpe', '0,21', 'mean / volatilità']], 6);
      h += '<div class="grid g2">' + S.panel('Equity Curve', S.spark(eq, 560, 200, { label: 'Equity' }), { icon: 'chart' }) + S.panel('Underwater (Drawdown)', '<svg viewBox="0 0 560 140" class="spark">' + (function () { var mn = Math.min.apply(null, uw) || -1; var p = uw.map(function (v, i) { return (i ? 'L' : 'M') + (i * 560 / (uw.length - 1)).toFixed(1) + ' ' + (4 + 130 * v / mn).toFixed(1); }).join(' '); return '<path d="' + p + ' L560 4 L0 4Z" fill="#f87171" opacity=".25"/><path d="' + p + '" fill="none" stroke="#f87171" stroke-width="1.5"/>'; })() + '</svg>', { icon: 'chart' }) + '</div>';
      h += S.panel('Metriche di rischio', '<div class="grid g6">' + [['Volatilità', '9,84'], ['Sharpe', '0,21'], ['Sortino', '0,34'], ['Calmar', '1,12'], ['Recovery factor', '2,4'], ['Ulcer index', '4,1'], ['UPI', '0,5'], ['Downside dev', '6,1'], ['CVaR 5%', '−21,8'], ['Max DD', '−38,40'], ['DD max (gg)', '6'], ['Kurtosis', '1,9'], ['Profit factor', '1,38'], ['Mediana giorno', '+1,20'], ['Miglior giorno', '+27,10'], ['Peggior giorno', '−23,00'], ['Profit/stake', '4,1 %'], ['Trade/giorno', '2,3']].map(function (x) { return '<div><div class="lbl" style="font-size:9.5px">' + x[0] + '</div><div class="mono" style="font-size:13px;font-weight:700">' + x[1] + '</div></div>'; }).join('') + '</div>');
      h += '<div class="grid g2">' + S.panel('Consigli seguiti vs fuori-consiglio', '<div class="grid g2"><div class="strip paper" style="flex-direction:column;align-items:flex-start"><span class="lbl">Consiglio seguito</span><b style="font-size:20px">34</b><span class="pos">ROI 6,2 %</span></div><div class="strip warn" style="flex-direction:column;align-items:flex-start"><span class="lbl">Fuori-consiglio</span><b style="font-size:20px">12</b><span class="neg">ROI −3,8 %</span></div></div><p class="foot">Partite scartate nel periodo: 19.</p>') +
        S.panel('Calendario P&L giornaliero', '<div style="display:flex;flex-wrap:wrap;gap:4px">' + days.map(function (d) { var a = Math.min(.6, .12 + Math.abs(d.pnl) / 40); return '<span title="' + C.ggData(d.date) + ' · €' + d.pnl.toFixed(2) + ' · ' + d.n + ' trade" style="width:30px;height:30px;border-radius:6px;display:grid;place-items:center;font-size:10px;background:' + (d.pnl >= 0 ? 'rgba(16,185,129,' + a + ')' : 'rgba(239,68,68,' + a + ')') + '">' + d.date.getDate() + '</span>'; }).join('') + '</div><p class="foot">■ profitto · ■ perdita</p>') + '</div>';
      h += '<div class="grid g2">' + ['Per strategia', 'Per lega'].map(function (t, k) {
        var r = k ? [['Serie A', 18, '61 %', 210, 22.4, '10,7 %', '1,6'], ['La Liga', 9, '44 %', 120, -14.2, '−11,8 %', '0,7'], ['Premier League', 11, '55 %', 140, 6.1, '4,4 %', '1,2']] : [['Lay the Draw', 21, '62 %', 260, 18.3, '7,0 %', '1,5'], ['Back Under 2.5', 10, '50 %', 120, -2.0, '−1,7 %', '0,9'], ['Lay Over 3.5', 7, '71 %', 90, 9.9, '11,0 %', '2,1']];
        return S.panel(t, '<div class="tbl-w"><table class="t"><thead><tr><th>' + (k ? 'Lega' : 'Strategia') + '</th><th class="r">N</th><th class="r">Win%</th><th class="r">Stake</th><th class="r">P&L</th><th class="r">ROI</th><th class="r">PF</th></tr></thead><tbody>' + r.map(function (x) { return '<tr><td>' + x[0] + '</td><td class="r">' + x[1] + '</td><td class="r">' + x[2] + '</td><td class="r">' + x[3] + '</td><td class="r ' + S.tone(x[4]) + '">' + S.money(x[4], { signed: true }) + '</td><td class="r ' + S.tone(x[4]) + '">' + x[5] + '</td><td class="r">' + x[6] + '</td></tr>'; }).join('') + '</tbody></table></div>', { flush: true });
      }).join('') + '</div>';
      h += '<section class="panel flat"><div class="panel-h"><h3>Trade (' + trades.length + ')</h3><span class="amb" style="font-size:12px">· 2 da chiudere</span><span class="note r">clic = dettaglio + “Chiudi trade”</span></div><div class="tbl-w"><table class="t" style="font-size:11.5px"><thead><tr><th>Data</th><th>ID Ev.</th><th>League</th><th>ID Lg.</th><th>Nazione</th><th>Stag.</th><th>Home</th><th>Away</th><th>Ris.</th><th>Strategia</th><th class="r">Quota</th><th class="r">Stake</th><th class="r">Copert.</th><th class="r">Netto</th><th class="r">T.Op</th><th class="r">€/h</th><th>Stato</th></tr></thead><tbody>' +
        trades.map(function (r, i) {
          var open = r[15] === 'OPEN' || r[15] === 'PARTIAL';
          var row = '<tr style="cursor:pointer" data-act="rp-exp" data-i="' + i + '"><td>' + r[0] + '</td><td class="mono">' + r[1] + '</td><td>' + r[2] + '</td><td class="mono">' + r[3] + '</td><td>' + r[4] + '</td><td>' + r[5] + '</td><td>' + r[6] + '</td><td>' + r[7] + '</td><td>' + r[8] + '</td><td style="color:' + (/^Lay/.test(r[9]) ? 'var(--lay)' : 'var(--back)') + '">' + r[9] + '</td><td class="r">' + S.odds(r[10]) + '</td><td class="r">' + r[11] + '</td><td class="r">' + r[12] + '</td><td class="r ' + S.tone(r[13]) + '">' + (r[13] == null ? '—' : S.money(r[13], { signed: true })) + '</td><td class="r"><input class="inp" id="rp-top' + i + '" style="width:52px;height:22px" value="' + (r[14] || '') + '"></td><td class="r">' + (r[13] && r[14] ? (r[13] / r[14] * 60).toFixed(1).replace('.', ',') : '—') + '</td><td>' + (open ? '<button class="btn sm gold" data-act="rp-settle">Chiudi</button>' : r[15]) + '</td></tr>';
          if (exp === i) row += '<tr><td colspan="17" style="white-space:normal;background:hsl(var(--muted)/.5)"><div class="grid g3"><div><div class="lbl">Dettaglio operazione</div><dl class="kv"><dt>Lato</dt><dd>' + (/^Lay/.test(r[9]) ? 'LAY' : 'BACK') + '</dd><dt>Mercato · Sel.</dt><dd>Match Odds · Pareggio</dd><dt>Timing</dt><dd>Live 22\'</dd><dt>Stato</dt><dd>' + r[15] + '</dd><dt>P&L lordo</dt><dd>8,55 €</dd><dt>Commissione</dt><dd>0,43 €</dd><dt>Provenienza</dt><dd class="mono">watchlist · betfair</dd></dl></div><div><div class="lbl">Pronostici (API-Football)</div><dl class="kv"><dt>Pronostico</dt><dd>Double chance: Inter o pareggio</dd><dt>Gol attesi</dt><dd>1,9 / 0,8</dd><dt>% 1X2 (H/D/A)</dt><dd>58 / 25 / 17</dd><dt>Risultato reale</dt><dd>' + r[8] + '</dd></dl></div><div><div class="lbl">Direzioni motori</div><table class="t"><tr><td>1X2</td><td>Casa</td><td>3/4</td><td class="pos">✓</td></tr><tr><td>Over 2.5</td><td>Over</td><td>2/4</td><td class="neg">✗</td></tr></table><div class="lbl" style="margin-top:8px">Coperture / Hedge</div><div class="foot">HEDGE · back · Match Odds · Pareggio · q 2,10 · 12,00 € · <span class="pos">+8,12 €</span></div></div></div></td></tr>';
          return row;
        }).join('') + '</tbody></table></div></section>';
      return h;
    }
  });
  S.on('rp-exp', function (t, e) { if (e.target.closest('input,button')) return; var i = +t.dataset.i; S.ui.rpExp = S.ui.rpExp === i ? null : i; S.rerender(); });
  S.on('rp-settle', function () {
    S.modal({ title: 'Chiudi trade', body: '<p class="mut" style="margin-top:0">Brentford vs Everton · Back Over 2.5. Il P&L viene ricalcolato dal server.</p><div class="grid g2"><label class="field" for="se1">Esito *<select id="se1" class="inp"><option>Vinto</option><option>Perso</option><option>Annullato</option><option>Parziale (cash-out)</option></select></label><label class="field" for="se2">Risultato FT<input id="se2" placeholder="2-1"></label><label class="field" for="se3">Quota uscita<input id="se3" placeholder="cash-out"></label><label class="field" for="se4">Tempo operativo (min)<input id="se4" placeholder="45"></label></div>', ok: 'Chiudi trade', onOk: function () { S.toast('Trade chiuso — Esito Vinto'); } });
  });
  S.on('rp-purge', function () {
    S.modal({ danger: true, title: 'Svuota Report', body: 'Elimina <b>definitivamente</b> tutta la reportistica personale: tutti i <b>trade</b>, le coperture/hedge e l’intera <b>watchlist</b> (Da valutare, Giocate, Scartate). Non tocca nient’altro. Operazione <b>non reversibile</b>.<label class="field" for="pg1" style="margin-top:10px">Scrivi SVUOTA per confermare<input id="pg1" placeholder="SVUOTA"></label>', ok: 'Svuota tutto', onOk: function () { S.toast('Prototipo: nulla è stato eliminato'); } });
  });
  S.on('rp-add', function () {
    S.modal({ title: 'Inserisci operazione passata', body: '<p class="foot" style="margin-top:0">Scegli la data e il match Betfair, poi registra l’operazione. Solo i match <b>agganciati a Betfair</b> sono selezionabili.</p><div class="strip warn" style="flex-direction:column;align-items:stretch"><span class="lbl">Match Betfair</span><div class="grid g2"><label class="field" for="mt1">Data match *<input id="mt1" type="date" value="2026-09-30"></label><label class="field" for="mt2">Partita *<select id="mt2" class="inp"><option>— seleziona —</option><option>Inter vs Torino · Serie A</option></select></label></div></div><div class="grid g3" style="margin-top:10px"><label class="field" for="mt3">Strategia *<input id="mt3" placeholder="Lay the Draw"></label><label class="field" for="mt4">Lato *<select id="mt4" class="inp"><option>Back (punta)</option><option>Lay (banca)</option></select></label><label class="field" for="mt5">Timing<select id="mt5" class="inp"><option>Pre-match</option><option>Live</option></select></label><label class="field" for="mt6">Mercato<input id="mt6" placeholder="over_2_5"></label><label class="field" for="mt7">Selezione<input id="mt7" placeholder="Under"></label><label class="field" for="mt8">Linea<input id="mt8" placeholder="2.5"></label><label class="field" for="mt9">Quota ingresso *<input id="mt9"></label><label class="field" for="mt10">Stake (€) *<input id="mt10"></label><label class="field" for="mt11">Esito *<select id="mt11" class="inp"><option>Vinto</option><option>Perso</option><option>Annullato</option><option>Parziale (cash-out)</option><option>Aperto</option></select></label></div><label class="row" style="font-size:12px;margin-top:10px"><input type="checkbox" id="mt12" checked> Registra P&L reale (Betfair) <span class="foot">netto e commissione presi da Betfair</span></label>', ok: 'Registra operazione' });
  });
})();
