#!/bin/sh
# ambiente NEUTRO: nessun database vero, nessun canale
export SUPABASE_URL=http://127.0.0.1:9 SUPABASE_KEY=x SUPABASE_SERVICE_ROLE_KEY=x
export LIVE_ORDER_MODE=LIVE LIVE_KILL_SWITCH=false LIVE_RECONCILE_POLL_SEC=5
export SAFE_PRE_KO_OU_HOURS=1 MIKE_LIVE_ENABLED=1
export LIVE_MARKET_TYPES=MATCH_ODDS,CORRECT_SCORE,HALF_TIME_SCORE
for v in SAFE_SCAN_CANALE MIKE_CANALE_POSIZIONI OMEGA_CANALE_POSIZIONI SAFE_CANALE_POSIZIONI \
  TENNIS_BOT_CANALE SAFE_BOT_LEGGE_CANALE SAFE_BOT_SVEGLIA_CANALE OMEGA_SVEGLIA_CANALE \
  MIKE_SVEGLIA_CANALE TENNIS_BOT_SVEGLIA_CANALE MIKE_LEGGE_CANALE OMEGA_LEGGE_CANALE \
  PUNTEGGI_CANALE ESITI_ORDINI_CANALE MOTORE_ORDINI_CANALE SCALPER_CANALE \
  SAFE_ORDINI_VIA_CANALE OMEGA_ORDINI_VIA_CANALE MOTORE_ORDINI_CANALE_TENNIS \
  SAFE_TENNIS_ORDINI_VIA_CANALE; do export $v=0; done
export PYTHONPATH="$(pwd)"
PY="/c/Users/Admin/Desktop/PYTHON DATABASE/python-database-automation/.venv/Scripts/python.exe"
"$PY" "$@"
