"""Falsificazione del cantiere J2 (J riportato su master + le strade nuove).

Ogni mutazione rimette UN difetto; il test indicato DEVE diventare rosso.
Ripristino byte-identico verificato con SHA-256 nel finally di ogni mutazione.
Uso (dalla radice del worktree): python AUDIT_2026-09-28/cantiere_j2/falsifica_j2.py [M1 N3 ...]
NON interrompere a meta'. Le mutazioni M1-M30 sono quelle di J
(``cantiere_j/falsifica_j.py``) con le stringhe ritrovate sul codice di master;
N1-N.. sono le strade che J non copriva o che master ha aggiunto; B.. blocco 2.
"""
import hashlib
import subprocess
import sys
from pathlib import Path

PY = str(Path(".venv/Scripts/python.exe"))
T = ["Betfair/safe_strategy/tests/test_flusso_interrotto_cantiere_j_2026_09_28.py",
     "Betfair/safe_strategy/tests/test_flusso_interrotto_cantiere_j_bis_2026_09_28.py",
     "Betfair/safe_strategy/tests/test_flusso_su_master_cantiere_j2_2026_09_28.py",
     "Betfair/mike/tests/test_mike_flusso_cantiere_j2_2026_09_28.py"]
T_EXTRA = [p for p in ("Betfair/stream/tests/test_stream_muto_cantiere_j_2026_09_28.py",
                       "Betfair/stream/tests/test_stream_muto_cablato_cantiere_j2_2026_09_28.py",
                       "Betfair/stream/tests/test_riserva_runner_cantiere_j2_2026_09_28.py",
                       "Betfair/stream/tests/test_banco_flusso_interrotto_cantiere_j2_2026_09_28.py")
           if Path(p).exists()]

MUT = [
    ("M1 scanner: flusso sempre vivo", "Betfair/safe_strategy/service.py",
     "        blk = {\"vivo\": bool(vivo), \"motivo\": motivo, \"dal_ms\": dal_ms, \"mercati_fermi\": fermi}",
     "        blk = {\"vivo\": True, \"motivo\": None, \"dal_ms\": dal_ms, \"mercati_fermi\": fermi}  # MUTAZIONE",
     "test_26_09_punteggio_che_cambia_prezzi_fermi_da_ore_il_bot_non_opera"),
    ("M2 scanner: blocco flusso non pubblicato nella riga", "Betfair/safe_strategy/service.py",
     "                payload[_flusso.CHIAVE] = self.flusso_evento(eid, sport, payload)",
     "                self.flusso_evento(eid, sport, payload)  # MUTAZIONE",
     "test_26_09_punteggio_che_cambia_prezzi_fermi_da_ore_il_bot_non_opera"),
    ("M3 Safe: feed_is_fresh ignora il flusso", "Betfair/safe_strategy/exits.py",
     "    if not flusso_esito(row, scanner_stato, market_id, now_ts).vivo:\n        return False",
     "    if False:  # MUTAZIONE\n        return False",
     "test_26_09_punteggio_che_cambia_prezzi_fermi_da_ore_il_bot_non_opera"),
    ("M4 scanner: heartbeat conferma anche il book della connessione vecchia", "Betfair/safe_strategy/service.py",
     "                if s is None or not s[0] or s[1] < sub_da:",
     "                if s is None or not s[0]:  # MUTAZIONE",
     "test_heartbeat_di_una_connessione_nuova_non_conferma_un_book_della_vecchia"),
    ("M5 scanner: latenza 503 ignorata", "Betfair/safe_strategy/service.py",
     "        latente = mid in self.flusso_latenti\n",
     "        latente = False  # MUTAZIONE\n",
     "test_stream_latente_503_non_conferma"),
    ("M6 shard: conferma anche con status 503", "Betfair/safe_strategy/stream.py",
     "        if self.latente():\n            return None\n        return self._last_msg_mono, self._connesso_mono",
     "        return self._last_msg_mono, self._connesso_mono  # MUTAZIONE",
     "test_shard_conferma_solo_se_connesso_vivo_e_non_latente"),
    ("M7 firma critica senza flusso (freno di 2,5 s sul passaggio)", "Betfair/safe_strategy/scanner.py",
     "    crit[\"flusso\"] = payload.get(\"flusso\")",
     "    pass  # MUTAZIONE",
     "test_il_passaggio_a_fermo_salta_il_freno_di_scrittura"),
    ("M8 Mike: linee ferme non tolte dal book", "Betfair/mike/feed.py",
     "        if fermi and str(blk.get(\"market_id\") or \"\") in fermi:\n            continue",
     "        if False:  # MUTAZIONE\n            continue",
     "test_mike_linea_ferma_via_dal_book_e_order_fresh_falso"),
    ("M9 Mike: order_fresh senza flusso", "Betfair/mike/feed.py",
     "        order_fresh=flusso_vivo and order_fresh(row, now, params, scanner_age_s),",
     "        order_fresh=order_fresh(row, now, params, scanner_age_s),  # MUTAZIONE",
     "test_mike_linea_ferma_via_dal_book_e_order_fresh_falso"),
    ("M10 Omega: prezzi del feed senza flusso", "Betfair/omega/omega_service.py",
     "    if not _flusso_feed(str(event_id)).vivo:\n        return False    # cantiere J: flusso fermo -> prezzi dal book REST o attesa",
     "    if False:  # MUTAZIONE\n        return False",
     "test_omega_flusso_fermo_niente_prezzi_dal_feed"),
    ("M11 stato: giro bloccato non visto", "Betfair/stream/flusso_prezzi.py",
     "        if eta > STATO_CALCOLO_MAX_S:",
     "        if False:  # MUTAZIONE",
     "test_stato_porta_il_flusso_e_il_giro_bloccato_ferma_tutti"),
    ("M12 scanner: dal_ms rigenerato a ogni giro (IO)", "Betfair/safe_strategy/service.py",
     "        if prec is not None and prec.get(\"vivo\") == vivo and prec.get(\"motivo\") == motivo:",
     "        if False:  # MUTAZIONE",
     "test_26_09_rientro_dei_prezzi_riaccende_il_flusso_con_una_sola_riscrittura"),
    ("M13 scanner: nessuna conferma dagli heartbeat", "Betfair/safe_strategy/service.py",
     "                if ultimo_msg > self.flusso_conferma.get(mid, -1e18):\n                    self.flusso_conferma[mid] = ultimo_msg",
     "                if False:  # MUTAZIONE\n                    self.flusso_conferma[mid] = ultimo_msg",
     "test_mercato_fermo_con_heartbeat_vivi_resta_vivo_per_dieci_minuti"),
    ("M14 banco: registrazione che scorre non conferma", "Betfair/stream/backtest/banco_comune.py",
     "        self.scan.conferma_flusso([m for m in self.mercati_visti\n                                   if not (self.buchi_flusso and self.nel_buco(m))])",
     "        pass  # MUTAZIONE",
     "test_banco_la_registrazione_che_scorre_conferma_come_gli_heartbeat"),
    ("M15 Safe: combo incompleta chiusa col flusso fermo", "Betfair/safe_strategy/bot_service.py",
     "        if esito_gamba is not None and not esito_gamba.vivo:",
     "        if False:  # MUTAZIONE",
     "test_safe_combo_incompleta_non_chiude_a_mercato_col_flusso_fermo"),
    ("M16 book senza prezzi trattato come prezzo", "Betfair/safe_strategy/service.py",
     "        if not ultimo[0]:\n            return False, _flusso.MOTIVO_SENZA_PREZZI",
     "        if False:  # MUTAZIONE\n            return False, _flusso.MOTIVO_SENZA_PREZZI",
     "test_book_senza_prezzi_non_e_un_prezzo_operabile"),
    ("M17 per mercato: linea ferma non segnalata", "Betfair/safe_strategy/service.py",
     "            if not ok:\n                fermi.append(mid)",
     "            if False:  # MUTAZIONE\n                fermi.append(mid)",
     "test_linea_ferma_con_match_odds_vivo_va_in_mercati_fermi"),
    ("M18 Safe: _row_is_fresh ignora il mercato", "Betfair/safe_strategy/bot_service.py",
     "                                                      market_id=market_id)",
     "                                                      market_id=None)  # MUTAZIONE",
     "test_linea_ferma_con_match_odds_vivo_va_in_mercati_fermi"),
    ("M19 Mike: giro bloccato non svuota i book", "Betfair/mike/feed.py",
     "        blocks = {}\n",
     "        pass  # MUTAZIONE\n",
     "test_mike_giro_scanner_bloccato_nessun_book"),
    ("M20 Safe apertura: market_id=None al posto del mercato del segnale", "Betfair/safe_strategy/bot_service.py",
     "        if not _row_is_fresh(feed_row, now_ts, scanner_ts, market_id=_sig(s, \"market_id\")):",
     "        if not _row_is_fresh(feed_row, now_ts, scanner_ts, market_id=None):  # MUTAZIONE",
     "test_apertura_esatto_linea_ferma_mo_vivo_non_apre"),
    ("M21 Safe uscita: feed_is_fresh senza market_id", "Betfair/safe_strategy/bot_service.py",
     "    if not XE.feed_is_fresh(row, now_ts, scanner_ts, scanner_stato=_scanner_stato(),\n                            market_id=trade.get(\"market_id\")):",
     "    if not XE.feed_is_fresh(row, now_ts, scanner_ts, scanner_stato=_scanner_stato(),\n                            market_id=None):  # MUTAZIONE",
     "test_uscita_linea_ferma_mo_vivo_non_esce"),
    ("M22 Safe uscita: feed_is_fresh senza scanner_stato", "Betfair/safe_strategy/bot_service.py",
     "    if not XE.feed_is_fresh(row, now_ts, scanner_ts, scanner_stato=_scanner_stato(),\n                            market_id=trade.get(\"market_id\")):",
     "    if not XE.feed_is_fresh(row, now_ts, scanner_ts, scanner_stato=None,  # MUTAZIONE\n                            market_id=trade.get(\"market_id\")):",
     "test_uscita_giro_scanner_bloccato_non_esce"),
    ("M23 Safe cash-out: feed_is_fresh senza market_id", "Betfair/safe_strategy/bot_service.py",
     "                                                         scanner_stato=_scanner_stato(),\n                                                         market_id=trade.get(\"market_id\"))",
     "                                                         scanner_stato=_scanner_stato(),\n                                                         market_id=None)  # MUTAZIONE",
     "test_cashout_linea_ferma_mo_vivo_non_usa_il_feed"),
    ("M24 Omega _feed_fresh_for_decision ignora il flusso", "Betfair/omega/omega_service.py",
     "    if not _flusso_feed(str(event_id)).vivo:\n        return False    # cantiere J: flusso fermo -> niente decisione sui prezzi del feed",
     "    if False:  # MUTAZIONE\n        return False",
     "test_omega_decisione_e_prezzi_col_cs_fermo"),
    ("M25 Omega _feed_prices_fresh ignora il flusso", "Betfair/omega/omega_service.py",
     "    if not _flusso_feed(str(event_id)).vivo:\n        return False    # cantiere J: flusso fermo -> prezzi dal book REST o attesa",
     "    if False:  # MUTAZIONE\n        return False",
     "test_omega_decisione_e_prezzi_col_cs_fermo"),
    ("M26 Omega _cs_from_feed ignora il flusso", "Betfair/omega/omega_service.py",
     "    if not _flusso_feed(event_id).vivo:\n        return None     # cantiere J: flusso fermo -> il chiamante va al book REST",
     "    if False:  # MUTAZIONE\n        return None",
     "test_omega_decisione_e_prezzi_col_cs_fermo"),
    ("M27 dato assente con scanner nuovo = non noto", "Betfair/stream/flusso_prezzi.py",
     "        if blocco_riga(payload) is None and stato_dichiara_flusso(stato):",
     "        if False:  # MUTAZIONE",
     "test_riga_senza_chiave_con_scanner_nuovo_non_e_viva"),
    ("M28 scanner vecchio: avviso a ogni giro", "Betfair/stream/flusso_prezzi.py",
     "    _NON_NOTO_AVVISATO.add(bot)\n",
     "    pass  # MUTAZIONE\n",
     "test_scanner_vecchio_si_dice_una_volta_safe"),
    ("M29 Mike: avviso scanner vecchio mai scritto", "Betfair/mike/service.py",
     "    if F._flusso.primo_avviso_scanner_vecchio(\"mike\", _ULTIMO_STATO_SCANNER[\"v\"]):",
     "    if False:  # MUTAZIONE",
     "test_scanner_vecchio_si_dice_una_volta_mike"),
    ("M30 stato dello scanner senza flusso prima del primo giro", "Betfair/safe_strategy/service.py",
     "            \"flusso\": dict(self.flusso_istantanea),",
     "            **({\"flusso\": dict(self.flusso_istantanea)} if self.flusso_istantanea else {}),  # MUTAZIONE",
     "test_ogni_riga_e_ogni_stato_dello_scanner_nuovo_portano_la_chiave"),
    # ---- J2: strade nuove su master ----
    ("N1 Safe ordine a mano/proposta approvata: veto solo sul MATCH_ODDS", "Betfair/safe_strategy/bot_service.py",
     "    if not _row_is_fresh(row_feed, now.timestamp(), _scanner_ts(db, now.timestamp()),\n                         market_id=market_id):",
     "    if not _row_is_fresh(row_feed, now.timestamp(), _scanner_ts(db, now.timestamp()),\n                         market_id=None):  # MUTAZIONE",
     "test_ordine_approvato_su_linea_ferma_non_parte_e_dice_perche"),
    ("N2 Safe combo approvata: gamba ferma accettata", "Betfair/safe_strategy/bot_service.py",
     "        if isinstance(row_feed, dict) and not XE.flusso_esito(\n                row_feed, _scanner_stato(), market_id, now.timestamp()).vivo:",
     "        if False:  # MUTAZIONE\n",
     "test_combo_approvata_con_una_gamba_su_linea_ferma_nessuna_gamba"),
    ("N3 Safe chiusura solidale: sorella ferma chiusa", "Betfair/safe_strategy/bot_service.py",
     "        if (esito_sorella is not None and not esito_sorella.vivo",
     "        if (False  # MUTAZIONE",
     "test_sorella_su_linea_ferma_non_si_chiude"),
    ("N4 Safe cash-out rifiutato senza motivo", "Betfair/safe_strategy/bot_service.py",
     "                    \"motivo\": _stale_reason(row, trade.get(\"market_id\")),\n",
     "                    # MUTAZIONE\n",
     "test_cashout_rifiutato_dice_il_motivo_del_flusso"),
    ("N5 Omega missione: blocco del feed fermo usato", "Betfair/omega/omega_service.py",
     "    if payload is not None and not _flusso_feed(event_id).vivo:",
     "    if False:  # MUTAZIONE",
     "test_omega_missione_col_cs_fermo_va_al_rest"),
    ("N6 Mike ciclo: stato dello scanner non passato allo snapshot", "Betfair/mike/service.py",
     "                               scanner_stato=_scanner_stato(),\n                               books_rest=books_rest or None)",
     "                               scanner_stato=None,  # MUTAZIONE\n                               books_rest=books_rest or None)",
     "test_giro_dello_scanner_bloccato_nessun_comando"),
    ("N7 Mike ciclo: flusso interrotto non detto", "Betfair/mike/service.py",
     "    if not esito_flusso.vivo:\n        _log_throttled(db, extra, params, now_ts, \"flusso_interrotto\",",
     "    if False:  # MUTAZIONE\n        _log_throttled(db, extra, params, now_ts, \"flusso_interrotto\",",
     "test_linee_ferme_nessuna_apertura_nessun_comando_al_runner"),
    # ---- reperto A (regola unica: aperture mai, chiusure dal ripiego REST) ----
    ("A1 Safe uscita: ripiego REST ignorato", "Betfair/safe_strategy/bot_service.py",
     "            prezzi_rest = _prezzi_ripiego_rest(market=market, trade=trade, now_ts=now_ts)",
     "            prezzi_rest = None  # MUTAZIONE",
     "test_regola_unica_safe_chiusura_col_flusso_fermo_e_rest_vivo_parte_coi_prezzi_rest"),
    ("A2 Safe: riga critica a ogni giro", "Betfair/safe_strategy/bot_service.py",
     "    if not _FLUSSO_CRITICO.dovuto(tid, now_ts):\n        return",
     "    if False:  # MUTAZIONE\n        return",
     "test_regola_unica_safe_flusso_fermo_e_rest_muto_nessun_ordine_e_riga_critica"),
    ("A3 Safe: REST muto senza riga critica", "Betfair/safe_strategy/bot_service.py",
     "                _avviso_critico_flusso(db, trade, row, now_ts, esito_fl.motivo)",
     "                pass  # MUTAZIONE",
     "test_regola_unica_safe_flusso_fermo_e_rest_muto_nessun_ordine_e_riga_critica"),
    ("A4 Mike ciclo: ripiego REST ignorato", "Betfair/mike/service.py",
     "        books_rest = _books_ripiego_rest(market, info, esito_flusso.mercati, now_ts)",
     "        books_rest = {}  # MUTAZIONE",
     "test_regola_unica_mike_flusso_fermo_rest_vivo_la_chiusura_parte_coi_prezzi_rest"),
    ("A5 Mike: apertura sui prezzi REST", "Betfair/mike/service.py",
     "    if fonte_prezzi == F._flusso.FONTE_RIPIEGO_REST and leg.role in APERTURE_MIKE:",
     "    if False:  # MUTAZIONE",
     "test_regola_unica_mike_execute_place_rifiuta_un_apertura_sui_prezzi_rest"),
    ("A6 Mike: riga critica a ogni giro", "Betfair/mike/service.py",
     "                and _FLUSSO_CRITICO.dovuto(str(ev[\"event_id\"]), now_ts):",
     "                and True:  # MUTAZIONE",
     "test_regola_unica_mike_flusso_fermo_rest_muto_nessun_ordine_e_riga_critica"),
    ("A7 Mike: REST letto anche senza posizione", "Betfair/mike/service.py",
     "    if not esito_flusso.vivo and posizione and not dry:",
     "    if not esito_flusso.vivo and not dry:  # MUTAZIONE",
     "test_regola_unica_mike_nessuna_apertura_anche_col_rest_vivo"),
    ("A8 Mike cash-out utente: niente ripiego REST", "Betfair/mike/service.py",
     "        books_rest = _books_ripiego_rest(market, info, esito_flusso.mercati, now.timestamp(),\n                                         con_tetto=False)",
     "        books_rest = {}  # MUTAZIONE",
     "test_regola_unica_mike_cash_out_dell_utente_col_flusso_fermo"),
    ("A9 Omega: apertura col flusso fermo", "Betfair/omega/omega_service.py",
     "                # fermo un'APERTURA non parte mai, nemmeno col book REST vivo\n                return 0, traded_count",
     "                # MUTAZIONE",
     "test_regola_unica_omega_nessuna_apertura_col_flusso_fermo"),
    ("A10 Omega green-up: flusso fermo non detto", "Betfair/omega/omega_service.py",
     "    flusso_fermo = market is _real_market and not _flusso_feed(str(tr.get(\"event_id\") or \"\")).vivo",
     "    flusso_fermo = False  # MUTAZIONE",
     "test_regola_unica_omega_green_up_col_ripiego_rest_e_col_rest_muto"),
    ("A11 Omega: riga critica a ogni giro", "Betfair/omega/omega_service.py",
     "    if not _FLUSSO_CRITICO_OMEGA.dovuto(tid, now_ts):\n        return",
     "    if False:  # MUTAZIONE\n        return",
     "test_regola_unica_omega_green_up_col_ripiego_rest_e_col_rest_muto"),
    ("A12 Safe: apertura letta dal REST", "Betfair/safe_strategy/bot_service.py",
     "        if not _row_is_fresh(feed_row, now_ts, scanner_ts, market_id=_sig(s, \"market_id\")):",
     "        if False:  # MUTAZIONE",
     "test_regola_unica_safe_nessuna_apertura_col_flusso_fermo_anche_col_rest_vivo"),
    ("A13 Safe sorella: ripiego REST ignorato", "Betfair/safe_strategy/bot_service.py",
     "            prices = _prezzi_ripiego_rest(market=market, trade=leg, now_ts=now.timestamp())\n            if not prices:\n                _annuncia_flusso_fermo(db, leg, row,",
     "            prices = None  # MUTAZIONE\n            if not prices:\n                _annuncia_flusso_fermo(db, leg, row,",
     "test_regola_unica_safe_sorella_ferma_col_rest_vivo_si_chiude_coi_prezzi_rest"),
    # ---- blocco 2: stream muto (J: M31-M33; J2: B1-B11) ----
    ("M31 stream muto: 503 non latente", "Betfair/stream/stream_muto.py",
     "        latente, codice = _status_non_ok(st)",
     "        latente, codice = False, None  # MUTAZIONE",
     "test_status_503_e_latente"),
    ("M32 stream muto: soglia ignorata", "Betfair/stream/stream_muto.py",
     "        vivo = eta is not None and eta <= soglia and not latente",
     "        vivo = eta is not None and not latente  # MUTAZIONE",
     "test_nessun_messaggio_oltre_soglia_e_muto"),
    ("M33 stream muto: avviso a ogni giro", "Betfair/stream/stream_muto.py",
     "        if vivo is False and self.muto_dal is None:",
     "        if vivo is False:  # MUTAZIONE",
     "test_episodio_detto_una_volta_inizio_e_fine"),
    ("B1 runner calcio: battito del frammento ignorato (seconda misura)", "Betfair/stream/stream_muto.py",
     "    um = getattr(listener, \"ultimo_msg_mono\", None)",
     "    um = None  # MUTAZIONE",
     "test_runner_calcio_usa_il_battito_del_frammento_non_una_seconda_misura"),
    ("B2 frammento appena aperto dato per interrotto", "Betfair/stream/stream_muto.py",
     "            continue                    # connessione nuova: si sta autenticando",
     "            pass  # MUTAZIONE",
     "test_frammento_appena_aperto_non_e_interrotto_ma_dopo_la_grazia_si"),
    ("B3 frammento chiuso contato", "Betfair/stream/stream_muto.py",
     "        if getattr(s, \"chiuso\", False):\n            continue",
     "        if False:  # MUTAZIONE\n            continue",
     "test_frammento_chiuso_non_conta"),
    ("B4 nessuna grazia all'avvio", "Betfair/stream/stream_muto.py",
     "                and adesso_s - self.nato_s < GRAZIA_CONNESSIONE_S):",
     "                and False):  # MUTAZIONE",
     "test_all_avvio_la_connessione_ha_la_grazia_poi_e_un_episodio"),
    ("B5 scalper: battito senza sorveglianza", "Betfair/stream/scalper/scalper_session.py",
     "            _flusso = sorveglia_flusso_sessione(db, ev, framework, sorv_flusso)",
     "            _flusso = {}  # MUTAZIONE",
     "test_scalper_il_battito_scrive_la_dichiarazione_nelle_stats"),
    ("B6 scalper: posizione non gestita non dichiarata", "Betfair/stream/scalper/scalper_session.py",
     "        posizione = _dichiarazione_non_flat(framework) if st.get(\"vivo\") is False else None",
     "        posizione = None  # MUTAZIONE",
     "test_scalper_episodio_detto_una_volta_con_la_posizione_e_il_rientro"),
    ("B7 runner calcio: battito senza sorveglianza", "Betfair/stream/runner.py",
     "    _sorveglia_flusso_runner(session, flumine)\n",
     "    pass  # MUTAZIONE\n",
     "test_runner_calcio_il_battito_chiama_la_sorveglianza"),
    ("B8 runner calcio: ordini vivi non dichiarati", "Betfair/stream/runner.py",
     "        posizione = (_ordini_vivi_nel_blotter(flumine)\n",
     "        posizione = (None  # MUTAZIONE\n",
     "test_runner_calcio_alert_una_volta_canale_a_ogni_battito"),
    ("B9 tennis: attivita' dei bot non scritta", "Betfair/stream/tennis_live/tennis_runner.py",
     "        for (ev, bot_key) in list(session.hosted.keys())[:_FLUSSO_ATTIVITA_MAX]:",
     "        for (ev, bot_key) in []:  # MUTAZIONE",
     "test_tennis_attivita_di_ogni_bot_e_stats"),
    ("B10 tennis: stats dei bot senza flusso", "Betfair/stream/tennis_live/tennis_runner.py",
     "                    battito[\"flusso\"] = dict(_fl)",
     "                    pass  # MUTAZIONE",
     "test_tennis_lo_stall_worker_sorveglia_e_il_battito_dei_bot_dichiara"),
    # ---- correzioni J2 (reperti 1-4 del revisore) ----
    ("C1 chase: apertura senza riserva non ritirata", "Betfair/stream/risk_engine_worker.py",
     "                _ritira_apertura_appoggiata(sb, rule, res, mode_l, bet_id, rem)\n                return",
     "                return  # MUTAZIONE",
     "test_chase_apertura_senza_riserva_si_ritira_e_non_si_ripiazza"),
    ("C2 chase: chiusura trattata come apertura", "Betfair/stream/risk_engine_worker.py",
     "        return (float(l) - float(w)) > risk_engine.FLAT_EPS",
     "        return False  # MUTAZIONE",
     "test_chase_chiusura_senza_riserva_resta_e_si_grida_una_volta_al_minuto"),
    ("C3 appoggiati: avviso a ogni giro", "Betfair/stream/risk_engine_worker.py",
     "    if prec is not None and ora - prec < _AVVISO_APPOGGIATI_OGNI_S:\n        return False",
     "    if False:  # MUTAZIONE\n        return False",
     "test_chase_chiusura_senza_riserva_resta_e_si_grida_una_volta_al_minuto"),
    ("C4 chase chiusura: niente inseguimento sulla riserva", "Betfair/stream/risk_engine_worker.py",
     "        if not chiude:\n            return      # apertura: nessun ri-prezzamento su prezzi di riserva",
     "        return  # MUTAZIONE",
     "test_chase_chiusura_con_riserva_viva_insegue_sulla_riserva"),
    ("C5 bracket: decide al buio senza riserva", "Betfair/stream/risk_engine_worker.py",
     "        if _stream_muto(rule) and best_back is None and best_lay is None:",
     "        if False:  # MUTAZIONE",
     "test_bracket_senza_riserva_grida_e_non_decide"),
    ("C6 status 500 accettato", "Betfair/stream/stream_muto.py",
     "    return True, (MOTIVO_LATENTE if n == _STATUS_LATENTE else f\"stream_status_{n}\")",
     "    return n == _STATUS_LATENTE, (MOTIVO_LATENTE if n == _STATUS_LATENTE else f\"stream_status_{n}\")  # MUTAZIONE",
     "test_status_diverso_da_null_o_200_non_conferma_col_suo_codice"),
    ("C7 shard scanner: status 500 accettato", "Betfair/safe_strategy/stream.py",
     "            return int(st) != 200",
     "            return int(st) == 503  # MUTAZIONE",
     "test_shard_dello_scanner_fail_closed_sullo_status"),
    ("C8 soglia non calcolata dall'heartbeat vero", "Betfair/stream/stream_muto.py",
     "        return BATTITI_PER_SOGLIA * float(hb) / 1000.0",
     "        return SOGLIA_S  # MUTAZIONE",
     "test_soglia_e_tre_volte_l_heartbeat_chiesto"),
    ("C9 banco senza buchi diverso da prima", "Betfair/stream/backtest/banco_comune.py",
     "        self.scan.conferma_flusso([m for m in self.mercati_visti\n                                   if not (self.buchi_flusso and self.nel_buco(m))])",
     "        self.scan.conferma_flusso([m for m in self.mercati_visti][:0])  # MUTAZIONE",
     "test_banco_senza_buchi_righe_identiche_al_banco_di_prima"),
    # ---- reperto B: il buco dei dati nel banco comune ----
    ("K1 banco: book applicati dentro il buco", "Betfair/stream/backtest/banco_comune.py",
     "        if self.buchi_flusso and self.nel_buco(mid):",
     "        if False:  # MUTAZIONE",
     "test_buco_dichiarato_il_flusso_diventa_fermo_e_rientra"),
    ("K2 banco: registrazione che conferma anche nel buco", "Betfair/stream/backtest/banco_comune.py",
     "        self.scan.conferma_flusso([m for m in self.mercati_visti\n                                   if not (self.buchi_flusso and self.nel_buco(m))])",
     "        self.scan.conferma_flusso(list(self.mercati_visti))  # MUTAZIONE",
     "test_buco_dichiarato_il_flusso_diventa_fermo_e_rientra"),
    # ---- blocco 3: riserva dei prezzi del runner ----
    ("R1 runner: _best_prices ignora la riserva", "Betfair/stream/live_order_worker.py",
     "    back, lay, _fonte = _RP.prezzi_protezione(market, selection_id, handicap,\n                                              _best_prices_stream)",
     "    back, lay = _best_prices_stream(market, selection_id, handicap)  # MUTAZIONE",
     "test_stream_muto_prezzi_dalla_riserva_mai_dal_book_fermo"),
    ("R2 riserva: episodio ignorato", "Betfair/stream/riserva_prezzi.py",
     "        if not _STATO.get(\"interrotto\"):\n            return True",
     "        if True:  # MUTAZIONE\n            return True",
     "test_stream_muto_prezzi_dalla_riserva_mai_dal_book_fermo"),
    ("R3 riserva: feed fermo usato", "Betfair/stream/riserva_prezzi.py",
     "    if not esito.vivo:\n        _esito(mid, f\"nessuna riserva: anche",
     "    if False:  # MUTAZIONE\n        _esito(mid, f\"nessuna riserva: anche",
     "test_riserva_ferma_anche_lei_nessun_prezzo_e_motivo"),
    ("R4 stop-entry apre a stream muto", "Betfair/stream/risk_engine_worker.py",
     "    if _stream_muto(rule):\n        # 28/09 (cantiere J2): uno stop-entry APRE",
     "    if False:  # MUTAZIONE\n        # 28/09 (cantiere J2): uno stop-entry APRE",
     "test_stop_entry_non_scatta_a_stream_muto_ne_apre_poi_al_rientro_si"),
    ("R5 protezioni sull'LTP fermo", "Betfair/stream/risk_engine_worker.py",
     "    if not _stream_muto(rule):\n        return _ltp(market, sel, hcap)",
     "    if True:  # MUTAZIONE\n        return _ltp(market, sel, hcap)",
     "test_stop_loss_a_stream_muto_scatta_sulla_riserva_non_sul_book_fermo"),
    # R6 sostituita da C1-C4 (chase a stream muto: ritiro/avviso/riserva)
    ("R7 runner: stato della riserva mai impostato", "Betfair/stream/runner.py",
     "    _RP.imposta_stato(dich)",
     "    pass  # MUTAZIONE",
     "test_il_battito_del_runner_imposta_lo_stato_della_riserva"),
    ("R8 riserva: handicap non controllato", "Betfair/stream/riserva_prezzi.py",
     "    if abs(float(handicap or 0.0)) > 1e-9:",
     "    if False:  # MUTAZIONE",
     "test_mercato_non_seguito_dal_feed_o_handicap_nessun_prezzo"),
    ("B11 tee tennis: eta' ignorata", "Betfair/stream/stream_muto.py",
     "    eta = max(0.0, (ora - max(ultimi)) / 1000.0) if ultimi else None",
     "    eta = 0.0 if ultimi else None  # MUTAZIONE",
     "test_battiti_del_tee_tennis"),
]


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> int:
    esiti = []
    sel = sys.argv[1:]
    for nome, file, vecchio, nuovo, test in MUT:
        if sel and not any(nome.startswith(x + " ") for x in sel):
            continue
        p = Path(file)
        orig = p.read_bytes()
        h0 = sha(p)
        testo = orig.decode("utf-8")
        crlf = "\r\n" in testo
        v = vecchio.replace("\n", "\r\n") if crlf else vecchio
        n = nuovo.replace("\n", "\r\n") if crlf else nuovo
        if testo.count(v) != 1:
            esiti.append((nome, "MUTAZIONE NON APPLICABILE (%d occorrenze)" % testo.count(v)))
            continue
        try:
            p.write_bytes(testo.replace(v, n).encode("utf-8"))
            r = subprocess.run([PY, "-m", "pytest", *T, *T_EXTRA, "-q", "-p", "no:cacheprovider",
                                "-k", test], capture_output=True, text=True, timeout=600)
            ultima = (r.stdout.strip().splitlines() or ["?"])[-1]
            esiti.append((nome, ("ROSSO" if r.returncode != 0 else "VERDE (!)") + " | " + test
                          + " | " + ultima))
        finally:
            p.write_bytes(orig)
            assert sha(p) == h0, "RIPRISTINO NON IDENTICO: " + file
    for nome, e in esiti:
        print(f"{nome}: {e}")
    return 0 if all(e.startswith("ROSSO") for _, e in esiti) else 1


if __name__ == "__main__":
    sys.exit(main())
