# Rotture minime del modulo atlante_v4 (lette da falsificazioni.py; percorsi relativi a Betfair/stream/scalper)
ROTTURE_V4 = [
    ("V1 pesi di stagione col segno sbagliato", "atlante_v4.py",
     "return 0.5 ** ((rif - stagione) / float(emivita))", "return 0.5 ** ((stagione - rif) / float(emivita))"),
    ("V2 recupero senza condizionare su partita viva", "atlante_v4.py",
     "    vivo = d > j\n", "    vivo = d >= 0\n"),
    ("V3 esponente beta della forza ignorato", "atlante_v4.py",
     "p = 1.0 - (1.0 - p) ** (mult ** b)", "p = 1.0 - (1.0 - p) ** mult"),
    ("V4 recupero 1T anche senza il tempo", "atlante_v4.py",
     "if tempo == 1 and m >= 45:", "if 45 <= m < 90 and tempo != 2:"),
    ("V5 idempotenza tolta", "atlante_v4.py",
     "    if p.fixture_id in visti:\n        return False\n", "    pass\n"),
    ("V6 leghe affidabili senza soglia", "atlante_v4.py",
     "affid = part >= MIN_PARTITE_AFFIDABILE", "affid = part >= 0"),
    ("V7 d2 solo da status.extra", "atlante_v4.py",
     "p.d2 = max(ex, lb2)", "p.d2 = ex"),
    ("V8 shrinkage senza K", "atlante_v4.py",
     "p_lega[k] = (ss + k_celle * pg[None]) / (nn + k_celle)", "p_lega[k] = (ss + 1.0 * pg[None]) / (nn + 1.0)"),
    ("V9 ripiego del recupero sul bucket sbagliato", "atlante_v4.py",
     "[(CA.TC_REC2 + b, 17) for b in range(CA.N_JB)]:\n            vuote",
     "[(CA.TC_REC2 + b, 16) for b in range(CA.N_JB)]:\n            vuote"),
    ("V10 stagione senza recupero registrato contata tutta", "atlante_v4.py",
     "        tieni = (S[\"stop\"] == 0) & (S[\"t\"] <= 41)", "        tieni = S[\"t\"] >= 0"),
    ("V12 recupero 1T sulla cella propria per default", "atlante_v4.py",
     "horizon: str = \"p_goal_next_3min\", usa_cella_recupero_1t: bool = False,",
     "horizon: str = \"p_goal_next_3min\", usa_cella_recupero_1t: bool = True,"),
    ("V11 regola di affidabilita' sempre vera", "atlante_v4.py",
     "return tot < MIN_GOL_BLOCCO or (con / tot) >= SOGLIA_RECUPERO_REGISTRATO", "return True"),
]
