/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Mock data di fallback per development.
 * Struttura identica a raw_json di fixture_predictions (API-Football /predictions).
 */
export const MOCK_RAW_JSON: any = {
    get: "predictions",
    parameters: { fixture: "1451163" },
    errors: [],
    results: 1,
    paging: { total: 1, current: 1 },
    response: [
        {
            predictions: {
                winner: { id: 81, name: "Marseille", comment: "Win or draw" },
                win_or_draw: true,
                under_over: "+1.5",
                goals: { home: "-3.5", away: "-2.5" },
                advice: "Combo Double chance : draw or Marseille and +1.5 goals",
                percent: { home: "10%", draw: "45%", away: "45%" },
            },
            league: {
                id: 2,
                name: "UEFA Champions League",
                country: "World",
                logo: "https://media.api-sports.io/football/leagues/2.png",
                flag: null,
                season: 2025,
            },
            teams: {
                home: {
                    id: 569,
                    name: "Club Brugge KV",
                    logo: "https://media.api-sports.io/football/teams/569.png",
                    last_5: {
                        form: "27%",
                        att: "64%",
                        def: "0%",
                        goals: {
                            for: { total: 7, average: "1.4" },
                            against: { total: 14, average: "2.8" },
                        },
                        played: 5,
                    },
                    league: {
                        form: "WWWWWLLDLLW",
                        fixtures: {
                            played: { home: 5, away: 6, total: 11 },
                            wins: { home: 3, away: 3, total: 6 },
                            draws: { home: 1, away: 0, total: 1 },
                            loses: { home: 1, away: 3, total: 4 },
                        },
                        goals: {
                            for: {
                                total: { home: 16, away: 9, total: 25 },
                                average: { home: "3.2", away: "1.5", total: "2.3" },
                                minute: {
                                    "0-15": { total: 4, percentage: "15.38%" },
                                    "16-30": { total: 2, percentage: "7.69%" },
                                    "31-45": { total: 10, percentage: "38.46%" },
                                    "46-60": { total: 1, percentage: "3.85%" },
                                    "61-75": { total: 5, percentage: "19.23%" },
                                    "76-90": { total: 4, percentage: "15.38%" },
                                    "91-105": { total: null, percentage: null },
                                    "106-120": { total: null, percentage: null },
                                },
                                under_over: {
                                    "0.5": { over: 8, under: 3 },
                                    "1.5": { over: 6, under: 5 },
                                    "2.5": { over: 6, under: 5 },
                                    "3.5": { over: 3, under: 8 },
                                    "4.5": { over: 1, under: 10 },
                                },
                            },
                            against: {
                                total: { home: 9, away: 11, total: 20 },
                                average: { home: "1.8", away: "1.8", total: "1.8" },
                                minute: {
                                    "0-15": { total: 3, percentage: "15.79%" },
                                    "16-30": { total: 3, percentage: "15.79%" },
                                    "31-45": { total: 3, percentage: "15.79%" },
                                    "46-60": { total: 3, percentage: "15.79%" },
                                    "61-75": { total: 3, percentage: "15.79%" },
                                    "76-90": { total: 4, percentage: "21.05%" },
                                    "91-105": { total: null, percentage: null },
                                    "106-120": { total: null, percentage: null },
                                },
                                under_over: {
                                    "0.5": { over: 9, under: 2 },
                                    "1.5": { over: 6, under: 5 },
                                    "2.5": { over: 4, under: 7 },
                                    "3.5": { over: 1, under: 10 },
                                    "4.5": { over: 0, under: 11 },
                                },
                            },
                        },
                        biggest: {
                            streak: { wins: 5, draws: 1, loses: 2 },
                            wins: { home: "6-0", away: "1-4" },
                            loses: { home: "0-3", away: "4-0" },
                            goals: { for: { home: 6, away: 4 }, against: { home: 3, away: 4 } },
                        },
                        clean_sheet: { home: 1, away: 1, total: 2 },
                        failed_to_score: { home: 1, away: 2, total: 3 },
                        penalty: {
                            scored: { total: 0, percentage: "0%" },
                            missed: { total: 0, percentage: "0%" },
                            total: 0,
                        },
                        lineups: [
                            { formation: "4-2-3-1", played: 7 },
                            { formation: "4-3-3", played: 2 },
                            { formation: "4-1-4-1", played: 1 },
                            { formation: "3-4-2-1", played: 1 },
                        ],
                        cards: {
                            yellow: {
                                "0-15": { total: 1, percentage: "8.33%" },
                                "16-30": { total: 1, percentage: "8.33%" },
                                "31-45": { total: 1, percentage: "8.33%" },
                                "46-60": { total: 2, percentage: "16.67%" },
                                "61-75": { total: 4, percentage: "33.33%" },
                                "76-90": { total: 3, percentage: "25.00%" },
                                "91-105": { total: null, percentage: null },
                                "106-120": { total: null, percentage: null },
                            },
                            red: {
                                "0-15": { total: null, percentage: null },
                                "16-30": { total: null, percentage: null },
                                "31-45": { total: null, percentage: null },
                                "46-60": { total: null, percentage: null },
                                "61-75": { total: null, percentage: null },
                                "76-90": { total: null, percentage: null },
                                "91-105": { total: null, percentage: null },
                                "106-120": { total: null, percentage: null },
                            },
                        },
                    },
                },
                away: {
                    id: 81,
                    name: "Marseille",
                    logo: "https://media.api-sports.io/football/teams/81.png",
                    last_5: {
                        form: "40%",
                        att: "55%",
                        def: "18%",
                        goals: {
                            for: { total: 6, average: "1.2" },
                            against: { total: 9, average: "1.8" },
                        },
                        played: 5,
                    },
                    league: {
                        form: "LWLLWWL",
                        fixtures: {
                            played: { home: 4, away: 3, total: 7 },
                            wins: { home: 2, away: 1, total: 3 },
                            draws: { home: 0, away: 0, total: 0 },
                            loses: { home: 2, away: 2, total: 4 },
                        },
                        goals: {
                            for: {
                                total: { home: 6, away: 5, total: 11 },
                                average: { home: "1.5", away: "1.7", total: "1.6" },
                                minute: {
                                    "0-15": { total: 4, percentage: "33.33%" },
                                    "16-30": { total: 2, percentage: "16.67%" },
                                    "31-45": { total: 1, percentage: "8.33%" },
                                    "46-60": { total: 4, percentage: "33.33%" },
                                    "61-75": { total: 1, percentage: "8.33%" },
                                    "76-90": { total: null, percentage: null },
                                    "91-105": { total: null, percentage: null },
                                    "106-120": { total: null, percentage: null },
                                },
                                under_over: {
                                    "0.5": { over: 5, under: 2 },
                                    "1.5": { over: 3, under: 4 },
                                    "2.5": { over: 2, under: 5 },
                                    "3.5": { over: 1, under: 6 },
                                    "4.5": { over: 0, under: 7 },
                                },
                            },
                            against: {
                                total: { home: 5, away: 6, total: 11 },
                                average: { home: "1.3", away: "2.0", total: "1.6" },
                                minute: {
                                    "0-15": { total: 2, percentage: "20.00%" },
                                    "16-30": { total: 1, percentage: "10.00%" },
                                    "31-45": { total: 1, percentage: "10.00%" },
                                    "46-60": { total: null, percentage: null },
                                    "61-75": { total: 2, percentage: "20.00%" },
                                    "76-90": { total: 4, percentage: "40.00%" },
                                    "91-105": { total: null, percentage: null },
                                    "106-120": { total: null, percentage: null },
                                },
                                under_over: {
                                    "0.5": { over: 6, under: 1 },
                                    "1.5": { over: 4, under: 3 },
                                    "2.5": { over: 1, under: 6 },
                                    "3.5": { over: 0, under: 7 },
                                    "4.5": { over: 0, under: 7 },
                                },
                            },
                        },
                        biggest: {
                            streak: { wins: 2, draws: 0, loses: 2 },
                            wins: { home: "4-0", away: "2-3" },
                            loses: { home: "0-3", away: "2-1" },
                            goals: { for: { home: 4, away: 3 }, against: { home: 3, away: 2 } },
                        },
                        clean_sheet: { home: 1, away: 0, total: 1 },
                        failed_to_score: { home: 2, away: 0, total: 2 },
                        penalty: {
                            scored: { total: 0, percentage: "0%" },
                            missed: { total: 0, percentage: "0%" },
                            total: 0,
                        },
                        lineups: [
                            { formation: "4-2-3-1", played: 3 },
                            { formation: "3-4-2-1", played: 1 },
                            { formation: "5-4-1", played: 1 },
                            { formation: "3-4-1-2", played: 1 },
                            { formation: "4-4-2", played: 1 },
                        ],
                        cards: {
                            yellow: {
                                "0-15": { total: 2, percentage: "11.76%" },
                                "16-30": { total: 1, percentage: "5.88%" },
                                "31-45": { total: 2, percentage: "11.76%" },
                                "46-60": { total: 4, percentage: "23.53%" },
                                "61-75": { total: 3, percentage: "17.65%" },
                                "76-90": { total: 4, percentage: "23.53%" },
                                "91-105": { total: 1, percentage: "5.88%" },
                                "106-120": { total: null, percentage: null },
                            },
                            red: {
                                "0-15": { total: null, percentage: null },
                                "16-30": { total: null, percentage: null },
                                "31-45": { total: null, percentage: null },
                                "46-60": { total: 1, percentage: "100.00%" },
                                "61-75": { total: null, percentage: null },
                                "76-90": { total: null, percentage: null },
                                "91-105": { total: null, percentage: null },
                                "106-120": { total: null, percentage: null },
                            },
                        },
                    },
                },
            },
            comparison: {
                form: { home: "40%", away: "60%" },
                att: { home: "54%", away: "46%" },
                def: { home: "39%", away: "61%" },
                poisson_distribution: { home: "60%", away: "40%" },
                h2h: { home: "0%", away: "0%" },
                goals: { home: "0%", away: "0%" },
                total: { home: "48.3%", away: "51.8%" },
            },
            h2h: [],
        },
    ],
};
